#ifndef NXOpen_FEATURES_SHEETMETAL_FLATSOLIDBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_FLATSOLIDBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_FlatSolidBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_SheetMetal_CornerTreatmentBuilder.hxx>
#include <NXOpen/Features_SheetMetal_SheetmetalBaseBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class FlatSolidBuilder;
        }
    }
    class CoordinateSystem;
    namespace Features
    {
        namespace SheetMetal
        {
            class CornerTreatmentBuilder;
        }
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class SheetmetalBaseBuilder;
        }
    }
    class Section;
    class SelectEdge;
    class SelectFace;
    namespace Features
    {
        namespace SheetMetal
        {
            class _FlatSolidBuilderBuilder;
            class FlatSolidBuilderImpl;
            /** Represents a Flat As Solid feature builder.  <br> To create a new instance of this class, use @link NXOpen::Features::SheetMetal::SheetmetalManager::CreateFlatSolidFeatureBuilder  NXOpen::Features::SheetMetal::SheetmetalManager::CreateFlatSolidFeatureBuilder @endlink  <br> 
            Default values.
            <table border="1"> 
             
            <tr><th> 
            Property</th>  <th> 
            Value</th> </tr>
            <tr><td> 
             
            Associative </td> <td> 
             
            true </td> </tr> 

            <tr><td> 
             
            InnerCornerTreatment.TreatmentType </td> <td> 
             
            None </td> </tr> 

            <tr><td> 
             
            InnerCornerTreatment.UseGlobal </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            InnerCornerTreatment.Value.Value </td> <td> 
             
            0 (millimeters part), 0 (inches part) </td> </tr> 

            <tr><td> 
             
            TransformComponents </td> <td> 
             
            None </td> </tr> 

            <tr><td> 
             
            TransformRestrictionAreas </td> <td> 
             
            0 </td> </tr> 

            </table>  

             <br>  Created in NX4.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  FlatSolidBuilder : public NXOpen::Features::SheetMetal::SheetmetalBaseBuilder
            {
                /** The enum defines how to orient flat solid body. 
                 <br>  Created in NX12.0.0.  <br>  
                */
                public: enum OrientationType
                {
                    OrientationTypeDefault/** do not orient flat solid body */,
                    OrientationTypeEdge/** transform flat solid body as per orientation defined by edge */,
                    OrientationTypeCsys/** transform flat solid body as per orientation defined by CSYS */
                };

                /** The enum defines how to represent PCB components on flat solid. 
                 <br>  Created in NX10.0.0.  <br>  
                */
                public: enum TransformComponentsOption
                {
                    TransformComponentsOptionNone/** do not transform components */,
                    TransformComponentsOptionBody/** transform components as bodies */,
                    TransformComponentsOptionCsys/** transform components as CSYS */
                };

                private: FlatSolidBuilderImpl * m_flatsolidbuilder_impl;
                private: friend class  _FlatSolidBuilderBuilder;
                protected: FlatSolidBuilder();
                public: ~FlatSolidBuilder();
                /**Returns  the option which decides if the flattened solid will be transformed to Absolute CSYS.
                            This is applicable to flat solid / flat pattern features created (or renewed) to NX12 and later release.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::FlatSolidBuilder::OrientationType Orientation
                (
                );
                /**Sets  the option which decides if the flattened solid will be transformed to Absolute CSYS.
                            This is applicable to flat solid / flat pattern features created (or renewed) to NX12 and later release.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetOrientation
                (
                    NXOpen::Features::SheetMetal::FlatSolidBuilder::OrientationType orientation /** orientation */ 
                );
                /**Returns  the end of the edge where the tangent will define the x axis for flat as solid.
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: NXOpen::Point3d ReferenceVertex
                (
                );
                /**Sets  the end of the edge where the tangent will define the x axis for flat as solid.
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetReferenceVertex
                (
                    const NXOpen::Point3d & vertex /** One of the end points of the reference edge. */
                );
                /**Returns  the flag which decides if the flattened solid will be transformed to Absolute CSYS.
                            This is applicable to flat solid / flat pattern features created before NX12 release and not yet renewed.
                            The API can not be deprecated because it is required to edit features created before NX12 release.
                            But user should modify automation programs written before NX12 and replace use this option with the orientation option,
                            before using the program to create new features in NX12 or later.
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: bool TransformToAbsoluteCsys
                (
                );
                /**Sets  the flag which decides if the flattened solid will be transformed to Absolute CSYS.
                            This is applicable to flat solid / flat pattern features created before NX12 release and not yet renewed.
                            The API can not be deprecated because it is required to edit features created before NX12 release.
                            But user should modify automation programs written before NX12 and replace use this option with the orientation option,
                            before using the program to create new features in NX12 or later.
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetTransformToAbsoluteCsys
                (
                    bool transformFlag /** True = Transform to ABS, False = Do not transform to ABS. */
                );
                /** Validate the builder data  @return  0 Means no errors. 
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: int ValidateBuilderData
                (
                );
                /**Returns  the stationary face selection 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectFace * StationaryFace
                (
                );
                /**Returns  the x axis edge selection 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectEdge * XAxisEdge
                (
                );
                /**Returns  the added geometry selection 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Section * AddedGeometry
                (
                );
                /**Returns  the outer corner treatment corner object 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::CornerTreatmentBuilder * OuterCornerTreatment
                (
                );
                /**Returns  the inner corner treatment corner object 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::CornerTreatmentBuilder * InnerCornerTreatment
                (
                );
                /**Returns  the setting indicating how to represent transformed components in flat solid.
                            Only applies to the Flexible Printed Circuit Design application and will have no effect in Sheet Metal. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::FlatSolidBuilder::TransformComponentsOption TransformComponents
                (
                );
                /**Sets  the setting indicating how to represent transformed components in flat solid.
                            Only applies to the Flexible Printed Circuit Design application and will have no effect in Sheet Metal. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetTransformComponents
                (
                    NXOpen::Features::SheetMetal::FlatSolidBuilder::TransformComponentsOption transformComponents /** transformcomponents */ 
                );
                /**Returns  the setting indicating whether to transform restriction areas in flat solid.
                            Only applies to the Flexible Printed Circuit Design application and will have no effect in Sheet Metal. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: bool TransformRestrictionAreas
                (
                );
                /**Sets  the setting indicating whether to transform restriction areas in flat solid.
                            Only applies to the Flexible Printed Circuit Design application and will have no effect in Sheet Metal. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetTransformRestrictionAreas
                (
                    bool transformRestrictionAreas /** transformrestrictionareas */ 
                );
                /**Returns  the setting decides whether the flattened solid will be fixed at timestamp.
                            **  This is applicable to flat solid features created in NX12 and later release.
                            **  Cannot change during feature edit if the feature was created as fixed at timestamp.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: bool FixAtTimestamp
                (
                );
                /**Sets  the setting decides whether the flattened solid will be fixed at timestamp.
                            **  This is applicable to flat solid features created in NX12 and later release.
                            **  Cannot change during feature edit if the feature was created as fixed at timestamp.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetFixAtTimestamp
                (
                    bool fixAtTimestamp /** True = Fix at Timestamp, False = Do not Fix at Timestamp. */
                );
                /**Returns  the setting which decides whether the flattened solid will be associative to parent body.
                            **  This is applicable to flat solid features created in NX12 and later release.
                            **  Cannot change during feature edit if the feature was created as non associative.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: bool Associative
                (
                );
                /**Sets  the setting which decides whether the flattened solid will be associative to parent body.
                            **  This is applicable to flat solid features created in NX12 and later release.
                            **  Cannot change during feature edit if the feature was created as non associative.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetAssociative
                (
                    bool associative /** True = Feature is associative, False = Feature is not associative. */
                );
                /**Returns  the orientation csys 
                            **  This is applicable to flat solid features created (or renewed) in NX12 and later release.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CoordinateSystem * OrientationCsys
                (
                );
                /**Sets  the orientation csys 
                            **  This is applicable to flat solid features created (or renewed) in NX12 and later release.
                            
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetOrientationCsys
                (
                    NXOpen::CoordinateSystem * csys /** csys */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
