#ifndef NXOpen_FORMBOARD_SHAPESEGMENTBUILDER_HXX_INCLUDED
#define NXOpen_FORMBOARD_SHAPESEGMENTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Formboard_ShapeSegmentBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_formboard_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Formboard
    {
        class ShapeSegmentBuilder;
    }
    class Builder;
    namespace Routing
    {
        class ControlPoint;
    }
    namespace Routing
    {
        class ISegment;
    }
    class TaggedObject;
    namespace Formboard
    {
        class _ShapeSegmentBuilderBuilder;
        class ShapeSegmentBuilderImpl;
        /** Builder for Face Annotation functionality used in formboard. It allows 
                 importing CGM or Pattern file geometry and placing it on a drawing sheet
                 or model view. As a result of this a group of dumb geometry is placed such
                 that defined origin is located at the lower left hand of the bounding box 
                 containing the group of geometry.
              <br> To create a new instance of this class, use @link NXOpen::Formboard::FormboardManager::CreateShapeSegmentBuilder  NXOpen::Formboard::FormboardManager::CreateShapeSegmentBuilder @endlink  <br> 
         <br>  Created in NX7.5.0.  <br>  
        */
        class NXOPENCPP_FORMBOARDEXPORT  ShapeSegmentBuilder : public NXOpen::Builder
        {
            private: ShapeSegmentBuilderImpl * m_shapesegmentbuilder_impl;
            private: friend class  _ShapeSegmentBuilderBuilder;
            protected: ShapeSegmentBuilder();
            public: ~ShapeSegmentBuilder();
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void ChangeType
            (
                int newType /** newtype */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void NewSegment
            (
                NXOpen::Routing::ISegment * newSegment /** newsegment */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void UpdateLineAngleVec
            (
                const NXOpen::Vector3d & newDir /** newdir */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void GetLineData
            (
                NXOpen::Routing::ISegment ** anchorSeg /** anchorseg */ ,
                NXOpen::Routing::ControlPoint ** anchorRcp /** anchorrcp */ ,
                double* angle /** angle */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void CreateNewRadialBend
            (
                const NXOpen::Point3d & firstPivot /** firstpivot */ ,
                int firstBendMethod /** firstbendmethod */ ,
                double firstBendValue /** firstbendvalue */ ,
                const NXOpen::Point3d & secondPivot /** secondpivot */ ,
                int secondBendMethod /** secondbendmethod */ ,
                double secondBendValue /** secondbendvalue */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void AddRadialPivot
            (
                const NXOpen::Point3d & pivotLocation /** pivotlocation */ ,
                int bendMethod /** bendmethod */ ,
                double bendValue /** bendvalue */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void RemoveRadialPivot
            (
                int pivotIndex /** pivotindex */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void UpdateRadialPivot
            (
                int pivotIndex /** pivotindex */ ,
                const NXOpen::Point3d & newLocation /** newlocation */ ,
                int newBendMethod /** newbendmethod */ ,
                double newBendValue /** newbendvalue */ 
            );
            /**
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void CreateNewSpline
            (
                const NXOpen::Point3d & anchorLocation /** anchorlocation */ ,
                const NXOpen::Point3d & firstPoint /** firstpoint */ ,
                const NXOpen::Point3d & secondPoint /** secondpoint */ 
            );
            /**
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void RemoveSplinePoint
            (
                int pointIndex /** pointindex */ 
            );
            /**
                    Adds a point to the existing spline. 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: int AddSplinePoint
            (
                const NXOpen::Point3d & pointLocation /** pointlocation */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void UpdateSplinePoint
            (
                int pointIndex /** pointindex */ ,
                const NXOpen::Point3d & pointLocation /** pointlocation */ ,
                bool inDrag /** indrag */ 
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void CommitCurrentOperation
            (
            );
            /** 
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void SwapAnchorEnd
            (
            );
            /** Sets the active view for the shape operation.
                    
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : routing_harness ("Routing Harness") */
            public: void SetActiveView
            (
                NXOpen::TaggedObject * view /** view */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
