#ifndef NXOpen_MOTION_BODYCONTACTBUILDER_HXX_INCLUDED
#define NXOpen_MOTION_BODYCONTACTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Motion_BodyContactBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Motion.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_motion_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Motion
    {
        class BodyContactBuilder;
    }
    class Builder;
    namespace Motion
    {
        class BodyContactAdams;
    }
    namespace Motion
    {
        class BodyContactLms;
    }
    namespace Motion
    {
        class BodyContactRecurdyn;
    }
    namespace Motion
    {
        class BodyContactSphereToCAD;
    }
    namespace Motion
    {
        class SelectLink;
    }
    class Point;
    class SelectNXObject;
    class SelectNXObjectList;
    namespace Motion
    {
        class _BodyContactBuilderBuilder;
        class BodyContactBuilderImpl;
        /** Represents a @link NXOpen::Motion::BodyContactBuilder NXOpen::Motion::BodyContactBuilder@endlink   <br> To create a new instance of this class, use @link NXOpen::Motion::BodyContactCollection::CreateBodyContactBuilder  NXOpen::Motion::BodyContactCollection::CreateBodyContactBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        AdamsParameters.CoulombFrictionOption </td> <td> 
         
        Off </td> </tr> 

        <tr><td> 
         
        AdamsParameters.DynamicCoefficientExpression.Value </td> <td> 
         
        0.2 </td> </tr> 

        <tr><td> 
         
        AdamsParameters.ForceExponentExpression.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        AdamsParameters.ForceModelType </td> <td> 
         
        Impact </td> </tr> 

        <tr><td> 
         
        AdamsParameters.FrictionVelocityExpression.Value </td> <td> 
         
        0.1 (millimeters part), 0.003937 (inches part) </td> </tr> 

        <tr><td> 
         
        AdamsParameters.MaterialDampingExpression.Value </td> <td> 
         
        10000.0 (millimeters part), 57.0993 (inches part) </td> </tr> 

        <tr><td> 
         
        AdamsParameters.PenetrationDepthExpression.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        AdamsParameters.RestitutionCoefficentExpression.Value </td> <td> 
         
        0.85 </td> </tr> 

        <tr><td> 
         
        AdamsParameters.StaticCoefficientExpression.Value </td> <td> 
         
        0.3 </td> </tr> 

        <tr><td> 
         
        AdamsParameters.StictionVelocityExpression.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        AdamsParameters.StiffnessExpression.Value </td> <td> 
         
        100000000.0 (millimeters part), 570993.142 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.ActionAngleTolerance.Value </td> <td> 
         
        25 </td> </tr> 

        <tr><td> 
         
        LmsParameters.ActionDistanceTolerance.Value </td> <td> 
         
        0.0 (millimeters part), 0.0 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.ActionEnableMaxFacetSize </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        LmsParameters.ActionMaxFacetSize.Value </td> <td> 
         
        1000 (millimeters part),   39.370078740157 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.ActionUseTessellationFile </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        LmsParameters.BaseAngleTolerance.Value </td> <td> 
         
        25 </td> </tr> 

        <tr><td> 
         
        LmsParameters.BaseDistanceTolerance.Value </td> <td> 
         
        0.0 (millimeters part), 0.0 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.BaseEnableMaxFacetSize </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        LmsParameters.BaseMaxFacetSize.Value </td> <td> 
         
        1000 (millimeters part),   39.370078740157 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.BaseUseTessellationFile </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        LmsParameters.CoulombFrictionOption </td> <td> 
         
        Off </td> </tr> 

        <tr><td> 
         
        LmsParameters.DynamicCoefficient.Value </td> <td> 
         
        0.2 </td> </tr> 

        <tr><td> 
         
        LmsParameters.ForceExponent.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        LmsParameters.ForceModel </td> <td> 
         
        Auto </td> </tr> 

        <tr><td> 
         
        LmsParameters.ForceModelTolerance.Value </td> <td> 
         
        5.0 (millimeters part), 0.196850393700787 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.FrictionVelocity.Value </td> <td> 
         
        0.1 (millimeters part), 0.003937 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.MaterialDamping.Value </td> <td> 
         
        10000.0 (millimeters part),  57.1014715473270000 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.MaxPenetrationDepth.Value </td> <td> 
         
        0.0254 (millimeters part), 0.001 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.StaticCoefficient.Value </td> <td> 
         
        0.3 </td> </tr> 

        <tr><td> 
         
        LmsParameters.StictionVelocity.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        LmsParameters.Stiffness.Value </td> <td> 
         
        100000000.0 (millimeters part), 571014.71547327 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.BufferRadiusFactorExpression.Value </td> <td> 
         
        1.2 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.ContactTypeOption </td> <td> 
         
        Solid </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.CoulombFrictionOption </td> <td> 
         
        Off </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.DynamicCoefficientExpression.Value </td> <td> 
         
        0.2 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryBoundingBufferLengthExpression.Value </td> <td> 
         
        20 (millimeters part),  0.7874 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryMaxFacetSizeFactorExpression.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryMaxFacetSizeFactorFlag </td> <td> 
         
        False </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryMaximumPenetrationExpression.Value </td> <td> 
         
        1.0 (millimeters part), 0.03937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryPlaneToleranceFactorExpression.Value </td> <td> 
         
        5.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FirstGeometryPlaneToleranceFactorSolidContactExpression.Value </td> <td> 
         
        3.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.ForceExponentExpression.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.ForceModelType </td> <td> 
         
        Impact </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.FrictionVelocityExpression.Value </td> <td> 
         
        0.1 (millimeters part), 0.003937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.GlobalMaxPenetrationExpression.Value </td> <td> 
         
        10.0 (millimeters part),  0.3937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.LocalMaxPenetrationExpression.Value </td> <td> 
         
        0.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.MaterialDampingExpression.Value </td> <td> 
         
        10000.0 (millimeters part),  57.0993 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.MaximumStepSizeFactorExpression.Value </td> <td> 
         
        10.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.PenetrationDepthExpression.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.ReboundDampingFactorExpression.Value </td> <td> 
         
        0.25 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.ReboundDampingFactorFlag </td> <td> 
         
        True </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryBoundingBufferLengthExpression.Value </td> <td> 
         
        20 (millimeters part),  0.7874 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryMaxFacetSizeFactorExpression.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryMaxFacetSizeFactorFlag </td> <td> 
         
        False </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryMaximumPenetrationExpression.Value </td> <td> 
         
        1.0 (millimeters part), 0.03937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryPlaneToleranceFactorExpression.Value </td> <td> 
         
        5.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SecondGeometryPlaneToleranceFactorSolidContactExpression.Value </td> <td> 
         
        3.0 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.StaticCoefficientExpression.Value </td> <td> 
         
        0.3 </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.StictionVelocityExpression.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.StiffnessExpression.Value </td> <td> 
         
        100000000.0 (millimeters part), 570993.142 (inches part) </td> </tr> 

        <tr><td> 
         
        RecurdynParameters.SurfaceTypeOption </td> <td> 
         
        Faceted </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.BodyAngleTolerance.Value </td> <td> 
         
        25 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.BodyDistanceTolerance.Value </td> <td> 
         
        0.0 (millimeters part), 0.0 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.BodyEnableMaxFacetSize </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.BodyMaxFacetSize.Value </td> <td> 
         
        1000 (millimeters part),   39.370078740157 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.CoulombFrictionOption </td> <td> 
         
        Off </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.DynamicCoefficient.Value </td> <td> 
         
        0.2 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.ForceExponent.Value </td> <td> 
         
        2.0 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.FrictionVelocity.Value </td> <td> 
         
        0.1 (millimeters part), 0.003937 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.MaterialDamping.Value </td> <td> 
         
        10000.0 (millimeters part),  57.1014715473270000 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.MaxPenetrationDepth.Value </td> <td> 
         
        0.0254 (millimeters part), 0.001 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.SphereMaxFacetSize.Value </td> <td> 
         
        1000 (millimeters part),   39.370078740157 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.SphereRadius.Value </td> <td> 
         
        1000.0 (millimeters part),   39.370078740157 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.StaticCoefficient.Value </td> <td> 
         
        0.3 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.StictionVelocity.Value </td> <td> 
         
        0.01 (millimeters part), 0.0003937 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.Stiffness.Value </td> <td> 
         
        100000000.0 (millimeters part), 571014.71547327 (inches part) </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.SuperElementIncrement </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.SuperElementReportInstance </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SphereToCadParameters.UseTessellationFile </td> <td> 
         
        0 </td> </tr> 

        </table>  

         <br>  Created in NX5.0.0.  <br>  
        */
        class NXOPENCPP_MOTIONEXPORT  BodyContactBuilder : public NXOpen::Builder
        {
            /** the contact type (3D Contact or Sphere to CAD Contact) */
            public: enum ContactTypeOption
            {
                ContactTypeOptionCADToCADContact/** cadto cadcontact */ ,
                ContactTypeOptionSphereToCADContact/** sphere to cadcontact */ 
            };

            private: BodyContactBuilderImpl * m_bodycontactbuilder_impl;
            private: friend class  _BodyContactBuilderBuilder;
            protected: BodyContactBuilder();
            public: ~BodyContactBuilder();
            /**Returns  the type: 3D contact or Sphere to CAD
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::BodyContactBuilder::ContactTypeOption ContactType
            (
            );
            /**Sets  the type: 3D contact or Sphere to CAD
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetContactType
            (
                NXOpen::Motion::BodyContactBuilder::ContactTypeOption type /** type */ 
            );
            /**Returns  the selection of the first contact geometry 
             <br>  @deprecated Deprecated in NX1847.0.0.  Use @link Motion::BodyContactBuilder::FirstContactGeometryObject Motion::BodyContactBuilder::FirstContactGeometryObject@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX1847.0.0.  Use Motion::BodyContactBuilder::FirstContactGeometryObjectinstead.") NXOpen::SelectNXObjectList * FirstContactGeometry
            (
            );
            /**Returns  the selection of the first contact geometry 
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectNXObject * FirstContactGeometryObject
            (
            );
            /**Returns   @brief the override state of the action geometry 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::ParamOverrideState FirstContactGeometryObjectOvrCtrl
            (
            );
            /**Sets   @brief the override state of the action geometry 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetFirstContactGeometryObjectOvrCtrl
            (
                NXOpen::Motion::ParamOverrideState overrideState /** overridestate */ 
            );
            /**Returns  the selection of the second contact geometry 
             <br>  @deprecated Deprecated in NX1847.0.0.  Use @link Motion::BodyContactBuilder::SecondContactGeometryObject Motion::BodyContactBuilder::SecondContactGeometryObject@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX1847.0.0.  Use Motion::BodyContactBuilder::SecondContactGeometryObjectinstead.") NXOpen::SelectNXObjectList * SecondContactGeometry
            (
            );
            /**Returns  the selection of the second contact geometry 
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectNXObject * SecondContactGeometryObject
            (
            );
            /**Returns   @brief the override state of the base geometry 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::ParamOverrideState SecondContactGeometryObjectOvrCtrl
            (
            );
            /**Sets   @brief the override state of the base geometry 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondContactGeometryObjectOvrCtrl
            (
                NXOpen::Motion::ParamOverrideState overrideState /** overridestate */ 
            );
            /**Returns  the selection of sphere motion body for Sphere To CAD 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * SphereLink
            (
            );
            /**Returns   @brief the override state of the sphere motion body 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::ParamOverrideState SphereLinkOvrCtrl
            (
            );
            /**Sets   @brief the override state of the sphere motion body 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSphereLinkOvrCtrl
            (
                NXOpen::Motion::ParamOverrideState overrideState /** overridestate */ 
            );
            /**Returns  the selection of sphere center for Sphere To CAD 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Point * SphereCenter
            (
            );
            /**Sets  the selection of sphere center for Sphere To CAD 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSphereCenter
            (
                NXOpen::Point * sphereCenter /** spherecenter */ 
            );
            /**Returns   @brief the override state of the sphere center 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::ParamOverrideState SphereCenterOvrCtrl
            (
            );
            /**Sets   @brief the override state of the sphere center 

             
                        It should only be used for occurrences
             <br>  Created in NX1847.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSphereCenterOvrCtrl
            (
                NXOpen::Motion::ParamOverrideState overrideState /** overridestate */ 
            );
            /**Returns  the name 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Name
            (
            );
            /**Sets  the name 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetName
            (
                const NXString & name /** name */ 
            );
            /**Sets  the name 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetName
            (
                const char * name /** name */ 
            );
            /**Returns the 3D BodyContact's subobject (the adams parameters)  
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::BodyContactAdams * AdamsParameters
            (
            );
            /**Returns  the 3D BodyContact's subobject (the recurdyn parameters) 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::BodyContactRecurdyn * RecurdynParameters
            (
            );
            /**Returns  the 3D BodyContact's subobject (the lms parameters) 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::BodyContactLms * LmsParameters
            (
            );
            /**Returns  the 3D BodyContact's subobject (the sphere to cad parameters) 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Motion::BodyContactSphereToCAD * SphereToCadParameters
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
