#ifndef NXOpen_CAE_USERDEFINEDSOLIDBEAMSECTIONBUILDER_HXX_INCLUDED
#define NXOpen_CAE_USERDEFINEDSOLIDBEAMSECTIONBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_UserDefinedSolidBeamSectionBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_IBeamSectionBuilder.hxx>
#include <NXOpen/CAE_BeamSection.hxx>
#include <NXOpen/CAE_UserDefinedSolidBeamSectionBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class UserDefinedSolidBeamSectionBuilder;
    }
    namespace CAE
    {
        class IBeamSectionBuilder;
    }
    namespace CAE
    {
        class SelectCAEFace;
    }
    class Direction;
    namespace CAE
    {
        class _UserDefinedSolidBeamSectionBuilderBuilder;
        class UserDefinedSolidBeamSectionBuilderImpl;
        /**
            Represents a @link CAE::UserDefinedSolidBeamSectionBuilder CAE::UserDefinedSolidBeamSectionBuilder@endlink 
             <br> To create a new instance of this class, use @link CAE::BeamSectionCollection::CreateUserDefinedSolidBeamSectionBuilder  CAE::BeamSectionCollection::CreateUserDefinedSolidBeamSectionBuilder @endlink  <br> 
         <br>  Created in NX7.5.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  UserDefinedSolidBeamSectionBuilder : public CAE::IBeamSectionBuilder
        {
            private: UserDefinedSolidBeamSectionBuilderImpl * m_userdefinedsolidbeamsectionbuilder_impl;
            private: friend class  _UserDefinedSolidBeamSectionBuilderBuilder;
            protected: UserDefinedSolidBeamSectionBuilder();
            public: ~UserDefinedSolidBeamSectionBuilder();
            /**Returns  the section descriptor name 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXString DescriptorName
            (
            );
            /**Sets  the section descriptor name 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetDescriptorName
            (
                const NXString & descriptorName /** descriptorname */ 
            );
            /**Sets  the section descriptor name 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            void SetDescriptorName
            (
                const char * descriptorName /** descriptorname */ 
            );
            /**Returns  the solid face 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAE::SelectCAEFace * SolidFace
            (
            );
            /**Returns  the option to define reference vector 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAE::BeamSection::DirectionOption DirectionType
            (
            );
            /**Sets  the option to define reference vector 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetDirectionType
            (
                NXOpen::CAE::BeamSection::DirectionOption directionType /** directiontype */ 
            );
            /**Returns  the reference vector 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * ReferenceVector
            (
            );
            /**Sets  the reference vector 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetReferenceVector
            (
                NXOpen::Direction * referenceVector /** referencevector */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
