#ifndef NXOpen_FEATURES_MOVEFACEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_MOVEFACEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_MoveFaceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_MoveFaceBuilder.hxx>
#include <NXOpen/ModlDirect_SelectBlend.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class MoveFaceBuilder;
    }
    class Axis;
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace ModlDirect
    {
        class SelectBlend;
    }
    class Point;
    class ScCollector;
    namespace Features
    {
        class _MoveFaceBuilderBuilder;
        class MoveFaceBuilderImpl;
        /**
            Represents a builder for a move face feature, don't use it until nx502.
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateMoveFaceBuilder  Features::FeatureCollection::CreateMoveFaceBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        Angle.Value </td> <td> 
         
        10.0 </td> </tr> 

        <tr><td> 
         
        Distance.Value </td> <td> 
         
        10.0 (millimeters part), 0.4 (inches part) </td> </tr> 

        </table>  

         <br>  Created in NX5.0.2.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  MoveFaceBuilder : public Features::FeatureBuilder
        {
            /** the move face types, don't use it until nx502 */
            public: enum Types
            {
                TypesTranslateDirectionAndDistance/** Direction and Distance for moving the faces */,
                TypesTranslateBetweenTwoPoints/** Move faces in the direction and distance defined by the two points */,
                TypesRotateAboutAxis/** Move faces by rotating about an axis */,
                TypesRotateBetweenTwoAxes/** Move faces by rotating the axis from the first to the second */
            };

            private: MoveFaceBuilderImpl * m_movefacebuilder_impl;
            private: friend class  _MoveFaceBuilderBuilder;
            protected: MoveFaceBuilder();
            public: ~MoveFaceBuilder();
            /**Returns  the type, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::MoveFaceBuilder::Types Type
            (
            );
            /**Sets  the type, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetType
            (
                NXOpen::Features::MoveFaceBuilder::Types moveType /** the move face type */
            );
            /**Returns  the face collector holding the faces to move 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * MoveFaceCollector
            (
            );
            /**Returns  the from point in point to point option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * FromPoint
            (
            );
            /**Sets  the from point in point to point option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetFromPoint
            (
                NXOpen::Point * fromPoint /** the from point */
            );
            /**Returns  the to point in point to point option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * ToPoint
            (
            );
            /**Sets  the to point in point to point option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetToPoint
            (
                NXOpen::Point * toPoint /** the to point */
            );
            /**Returns  the from vector in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * FromVector
            (
            );
            /**Sets  the from vector in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetFromVector
            (
                NXOpen::Direction * fromVector /** the from vector */
            );
            /**Returns  the pivot point in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * PivotPoint
            (
            );
            /**Sets  the pivot point in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetPivotPoint
            (
                NXOpen::Point * pivotPoint /** the pivot point */
            );
            /**Returns  the to vector in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * ToVector
            (
            );
            /**Sets  the to vector in axis to axis option in move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetToVector
            (
                NXOpen::Direction * toVector /** the to vector */
            );
            /**Returns  the face collector holding the all the recognized blend faces adjacent to face to move. It is auto recognized blends +
                        user selected blends - user excluded blends, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::ModlDirect::SelectBlend * BlendFaces
            (
            );
            /**Returns  the vector for direction and distance option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * Direction
            (
            );
            /**Sets  the vector for direction and distance option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDirection
            (
                NXOpen::Direction * direction /** direction */ 
            );
            /**Returns  the distance for direction and distance option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Distance
            (
            );
            /**Returns  the axis for axis and angle option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Axis * Axis
            (
            );
            /**Sets  the axis for axis and angle option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAxis
            (
                NXOpen::Axis * axis /** axis */ 
            );
            /**Returns  the angle for axis and angle option, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Angle
            (
            );
            /**Returns  the copy option for move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : None */
            public: bool Copy
            (
            );
            /**Sets  the copy option for move face, don't use it until nx502 
             <br>  Created in NX5.0.2.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetCopy
            (
                bool copyOption /** copy option */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
