#ifndef NXOpen_FEATURES_SHEETMETAL_BEADBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_BEADBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_BeadBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class BeadBuilder;
        }
    }
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        class SketchFeature;
    }
    class Section;
    namespace Features
    {
        namespace SheetMetal
        {
            class _BeadBuilderBuilder;
            class BeadBuilderImpl;
            /** Represents a Bead feature builder.  <br> To create a new instance of this class, use @link NXOpen::Features::SheetMetal::SheetmetalManager::CreateBeadFeatureBuilder  NXOpen::Features::SheetMetal::SheetmetalManager::CreateBeadFeatureBuilder @endlink  <br> 
             <br>  Created in NX4.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  BeadBuilder : public NXOpen::Features::FeatureBuilder
            {
                /** This enum represents the cross section type options for the Bead.*/
                public: enum CrossSectionTypeOptions
                {
                    CrossSectionTypeOptionsCircular/** circular */ ,
                    CrossSectionTypeOptionsUshaped/** ushaped */ ,
                    CrossSectionTypeOptionsVshaped/** vshaped */ 
                };

                /** This enum represents the end type options for the Bead.*/
                public: enum EndTypeOptions
                {
                    EndTypeOptionsPunched/** punched */ ,
                    EndTypeOptionsLanced/** lanced */ ,
                    EndTypeOptionsFormed/** formed */ ,
                    EndTypeOptionsTapered/** tapered */ 
                };

                /** This enum represents the depth direction for the Bead. */
                public: enum HeightSideOptions
                {
                    HeightSideOptionsSectionNormalSide/** Material removed on the side of the section normal. */,
                    HeightSideOptionsSectionReverseNormalSide/** Material removed on the side opposite to that of the section normal */
                };

                private: BeadBuilderImpl * m_beadbuilder_impl;
                private: friend class  _BeadBuilderBuilder;
                protected: BeadBuilder();
                public: ~BeadBuilder();
                /**Returns  the Section used by the bead. section should be open.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Section * Section
                (
                );
                /**Sets  the Section used by the bead. section should be open.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetSection
                (
                    NXOpen::Section * section /** section */ 
                );
                /**Returns  the height of the bead.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * Height
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Height NXOpen::Features::SheetMetal::BeadBuilder::Height@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::Height instead.") void SetHeight
                (
                    const NXString & beadHeight /** bead height */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Height NXOpen::Features::SheetMetal::BeadBuilder::Height@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetHeight
                (
                    const char * beadHeight /** bead height */ 
                );
                /**Returns  the width of the bead.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * Width
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Width NXOpen::Features::SheetMetal::BeadBuilder::Width@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::Width instead.") void SetWidth
                (
                    const NXString & beadWidth /** bead width */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Width NXOpen::Features::SheetMetal::BeadBuilder::Width@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetWidth
                (
                    const char * beadWidth /** bead width */ 
                );
                /**Returns  the angle of the bead.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * Angle
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Angle NXOpen::Features::SheetMetal::BeadBuilder::Angle@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::Angle instead.") void SetAngle
                (
                    const NXString & beadAngle /** bead angle */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Angle NXOpen::Features::SheetMetal::BeadBuilder::Angle@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetAngle
                (
                    const char * beadAngle /** bead angle */ 
                );
                /**Returns  the radius of the bead.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * Radius
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Radius NXOpen::Features::SheetMetal::BeadBuilder::Radius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::Radius instead.") void SetRadius
                (
                    const NXString & beadRadius /** bead radius */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::Radius NXOpen::Features::SheetMetal::BeadBuilder::Radius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetRadius
                (
                    const char * beadRadius /** bead radius */ 
                );
                /**Returns  the Punched width of the bead.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * PunchedWidth
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::PunchedWidth NXOpen::Features::SheetMetal::BeadBuilder::PunchedWidth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::PunchedWidth instead.") void SetPunchedWidth
                (
                    const NXString & punchedWidth /** punched width */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::PunchedWidth NXOpen::Features::SheetMetal::BeadBuilder::PunchedWidth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetPunchedWidth
                (
                    const char * punchedWidth /** punched width */ 
                );
                /**Returns  the bead punch radius.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * PunchRadius
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::PunchRadius NXOpen::Features::SheetMetal::BeadBuilder::PunchRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::PunchRadius instead.") void SetPunchRadius
                (
                    const NXString & punchRadius /** punch radius */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::PunchRadius NXOpen::Features::SheetMetal::BeadBuilder::PunchRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetPunchRadius
                (
                    const char * punchRadius /** punch radius */ 
                );
                /**Returns  the bead die radius.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * DieRadius
                (
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::DieRadius NXOpen::Features::SheetMetal::BeadBuilder::DieRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public:  NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from NXOpen::Features::SheetMetal::BeadBuilder::DieRadius instead.") void SetDieRadius
                (
                    const NXString & beadDieRadius /** bead die radius */ 
                );
                /** 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link NXOpen::Features::SheetMetal::BeadBuilder::DieRadius NXOpen::Features::SheetMetal::BeadBuilder::DieRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                void SetDieRadius
                (
                    const char * beadDieRadius /** bead die radius */ 
                );
                /**Returns  the Height side for the bead.
                             <br> 
                                This is used to specify the direction in which the Bead is created. If Bead creation must happen in the
                                direction of the Section Normal (specified using the @link NXOpen::Features::SheetMetal::BeadBuilder::Section NXOpen::Features::SheetMetal::BeadBuilder::Section @endlink and @link NXOpen::Features::SheetMetal::BeadBuilder::SetSection NXOpen::Features::SheetMetal::BeadBuilder::SetSection @endlink ) then
                                pass the value of @link NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionNormalSide NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionNormalSide@endlink 
                                If Bead creation must happen in the opposite direction to that of Section Normal, set the value to be
                                @link NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionReverseNormalSide NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionReverseNormalSide@endlink 
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptions HeightSide
                (
                );
                /**Sets  the Height side for the bead.
                             <br> 
                                This is used to specify the direction in which the Bead is created. If Bead creation must happen in the
                                direction of the Section Normal (specified using the @link NXOpen::Features::SheetMetal::BeadBuilder::Section NXOpen::Features::SheetMetal::BeadBuilder::Section @endlink and @link NXOpen::Features::SheetMetal::BeadBuilder::SetSection NXOpen::Features::SheetMetal::BeadBuilder::SetSection @endlink ) then
                                pass the value of @link NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionNormalSide NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionNormalSide@endlink 
                                If Bead creation must happen in the opposite direction to that of Section Normal, set the value to be
                                @link NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionReverseNormalSide NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptionsSectionReverseNormalSide@endlink 
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetHeightSide
                (
                    NXOpen::Features::SheetMetal::BeadBuilder::HeightSideOptions heightSide /** height side */ 
                );
                /**Returns  the rounding type .
                             <br> 
                                Specify true to Round the Sharp edges.
                                Specify false to avoid rounding.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: bool IncludeRounding
                (
                );
                /**Sets  the rounding type .
                             <br> 
                                Specify true to Round the Sharp edges.
                                Specify false to avoid rounding.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetIncludeRounding
                (
                    bool rounding /** rounding */ 
                );
                /**Returns  the bead end type .
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsFormed  NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsFormed @endlink  to have ends of bead feature be formed.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsLanced  NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsLanced @endlink  to have ends of bead feature be Lanced.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsPunched NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsPunched@endlink  to have ends of bead feature be Punched.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsTapered NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsTapered@endlink  to have ends of bead feature be Tapered.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptions EndType
                (
                );
                /**Sets  the bead end type .
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsFormed  NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsFormed @endlink  to have ends of bead feature be formed.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsLanced  NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsLanced @endlink  to have ends of bead feature be Lanced.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsPunched NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsPunched@endlink  to have ends of bead feature be Punched.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsTapered NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptionsTapered@endlink  to have ends of bead feature be Tapered.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetEndType
                (
                    NXOpen::Features::SheetMetal::BeadBuilder::EndTypeOptions beadEndOptions /** bead end options */ 
                );
                /**Returns  the bead profile type .
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsCircular NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsCircular@endlink  to have profile of half circle.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsUshaped NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsUshaped@endlink  to have profile of U shape.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsVshaped NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsVshaped@endlink  to have profile of V shape.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptions CrossSectionType
                (
                );
                /**Sets  the bead profile type .
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsCircular NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsCircular@endlink  to have profile of half circle.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsUshaped NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsUshaped@endlink  to have profile of U shape.
                                Specify @link NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsVshaped NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptionsVshaped@endlink  to have profile of V shape.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetCrossSectionType
                (
                    NXOpen::Features::SheetMetal::BeadBuilder::CrossSectionTypeOptions crossSectionOption /** cross section option */ 
                );
                /**Returns  the Slave Sketch used by the Bead, If one exists.
                             <br> 
                                If the Sketch is created internally as part of the Bead command in the UI, then it shall be consumed by the Bead and shall not show up as a separate feature in the Part Navigator.
                                If such a behaviour is deired, then specify the Sketch here.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Features::SketchFeature * Sketch
                (
                );
                /**Sets  the Slave Sketch used by the Bead, If one exists.
                             <br> 
                                If the Sketch is created internally as part of the Bead command in the UI, then it shall be consumed by the Bead and shall not show up as a separate feature in the Part Navigator.
                                If such a behaviour is deired, then specify the Sketch here.
                             <br> 
                        
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetSketch
                (
                    NXOpen::Features::SketchFeature * sketch /** sketch */ 
                );
                /** Verify whether the builder data is valid for creating a Bead or not.
                             <br> 
                                 If the Builder data is valid, returned value shall be 0

                             <br> 
                         @return  Data Validity Flag.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: int ValidateBuilderData
                (
                );
                /**Returns  
                         the Minimum tool clearance expression.           
                        
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * MinimumToolClearance
                (
                );
                /**Returns  the taper distance of the bead.
                 <br>  Created in NX8.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: NXOpen::Expression * TaperDistance
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
