#ifndef NXOpen_FEATURES_SNIPSURFACEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SNIPSURFACEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SnipSurfaceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_SnipSurfaceBuilder.hxx>
#include <NXOpen/GeometricUtilities_RefitControlBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class SnipSurfaceBuilder;
    }
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class ProjectionOptions;
    }
    namespace GeometricUtilities
    {
        class RefitControlBuilder;
    }
    class Plane;
    class Section;
    class SelectFace;
    class SelectTaggedObject;
    namespace Features
    {
        class _SnipSurfaceBuilderBuilder;
        class SnipSurfaceBuilderImpl;
        /**
            Represents a @link NXOpen::Features::SnipSurface NXOpen::Features::SnipSurface@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::FeatureCollection::CreateSnipSurfaceBuilder  NXOpen::Features::FeatureCollection::CreateSnipSurfaceBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.Degree </td> <td> 
         
        3 </td> </tr> 

        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.SegmentsOrPatches </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.UDegree </td> <td> 
         
        5 </td> </tr> 

        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.UPatches </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.VDegree </td> <td> 
         
        5 </td> </tr> 

        <tr><td> 
         
        RefitControl.DegreesAndSegmentsOrPatches.VPatches </td> <td> 
         
        1 </td> </tr> 

        </table>  

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  SnipSurfaceBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** Snip method added in v 7.5.0*/
            public: enum Types
            {
                TypesSnipCurve/** snip curve */ ,
                TypesSnipSurface/** snip surface */ ,
                TypesSnipAtPlane/** snip at plane */ ,
                TypesIsoparamSnip/** isoparam snip */ 
            };

            private: SnipSurfaceBuilderImpl * m_snipsurfacebuilder_impl;
            private: friend class  _SnipSurfaceBuilderBuilder;
            protected: SnipSurfaceBuilder();
            public: ~SnipSurfaceBuilder();
            /**Returns  the target face 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::SelectFace * TargetFace
            (
            );
            /**Returns  the snipping curve 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Section * SnippingCurve
            (
            );
            /**Returns  the snipping object 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::SelectTaggedObject * SnippingObject
            (
            );
            /**Returns  the snipping plane 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Plane * SnippingPlane
            (
            );
            /**Sets  the snipping plane 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetSnippingPlane
            (
                NXOpen::Plane * plane /** plane */ 
            );
            /**Returns  the project direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::ProjectionOptions * ProjectDirection
            (
            );
            /**Returns  the UV flag 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: int SelectUV
            (
            );
            /**Sets  the UV flag 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: void SetSelectUV
            (
                int selectUV /** selectuv */ 
            );
            /**Returns  the isoparametric position 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * IsoparametricPosition
            (
            );
            /**Returns  the refit control 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::RefitControlBuilder * RefitControl
            (
            );
            /**Returns  a value indicating whether to keep the opposite surface.  This is applicable only when DivideSurface is false  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool KeepOppositeSurface
            (
            );
            /**Sets  a value indicating whether to keep the opposite surface.  This is applicable only when DivideSurface is false  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetKeepOppositeSurface
            (
                bool switchRegion /** switchregion */ 
            );
            /**Returns  a value indicating whether to divide the surface 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool DivideSurface
            (
            );
            /**Sets  a value indicating whether to divide the surface 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetDivideSurface
            (
                bool divide /** divide */ 
            );
            /**Returns  a value indicating whether to keep the original surface intact 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: bool EditCopy
            (
            );
            /**Sets  a value indicating whether to keep the original surface intact 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: void SetEditCopy
            (
                bool editCopy /** editcopy */ 
            );
            /**Returns   the 3D point picked on surface in Select Face 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Point3d RegionPickPoint
            (
            );
            /**Sets   the 3D point picked on surface in Select Face 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetRegionPickPoint
            (
                const NXOpen::Point3d & pnt /** pnt */ 
            );
            /**Returns  the UV values of the picked point on surface
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Point3d SurfacePointUV
            (
            );
            /**Sets  the UV values of the picked point on surface
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetSurfacePointUV
            (
                const NXOpen::Point3d & surfacePointUV /** surfacepointuv */ 
            );
            /**Returns  the cutting type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: int CutType
            (
            );
            /**Sets  the cutting type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetCutType
            (
                int cutType /** cuttype */ 
            );
            /** Returns the indicator for creating a new copy  @return  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool GetCreateNewCopy
            (
            );
            /** Sets the indicator for creating a new copy 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetCreateNewCopy
            (
                bool createNewCopy /** createnewcopy */ 
            );
            /**Returns  the snipping method accessor
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::SnipSurfaceBuilder::Types Type
            (
            );
            /**Sets  the snipping method accessor
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: void SetType
            (
                NXOpen::Features::SnipSurfaceBuilder::Types type /** type */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
