#ifndef NXOpen_GEOMETRICUTILITIES_CONICCROSSSECTION_HXX_INCLUDED
#define NXOpen_GEOMETRICUTILITIES_CONICCROSSSECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     GeometricUtilities_ConicCrossSection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/GeometricUtilities_LawBuilder.hxx>
#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_geometricutilities_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace GeometricUtilities
    {
        class ConicCrossSection;
    }
    class Expression;
    namespace GeometricUtilities
    {
        class IComponentBuilder;
    }
    namespace GeometricUtilities
    {
        class LawBuilder;
    }
    class ScCollector;
    namespace GeometricUtilities
    {
        class _ConicCrossSectionBuilder;
        class ConicCrossSectionImpl;
        /** Represents a conic section data for face blend. 
            
         <br>  Created in NX4.0.0.  <br>  
        */
        class NXOPENCPP_GEOMETRICUTILITIESEXPORT  ConicCrossSection : public NXOpen::TaggedObject, public virtual NXOpen::GeometricUtilities::IComponentBuilder
        {
            /** This enum represents the offset options */
            public: enum OffsetMethod
            {
                OffsetMethodConstant/** Constant */,
                OffsetMethodLaw/** Control by law */
            };

            /** This enum represents the rho options */
            public: enum RhoMethod
            {
                RhoMethodConstant/** Constant */,
                RhoMethodLaw/** Control by law */,
                RhoMethodAutoEllipse/** Automatic Ellipse */
            };

            /** This enum represents the depth option */
            public: enum DepthMethod
            {
                DepthMethodConstant/** Constant */,
                DepthMethodLaw/** Control by law */
            };

            /** This enum represents the shape skew option */
            public: enum ShapeSkewMethod
            {
                ShapeSkewMethodConstant/** Constant */,
                ShapeSkewMethodLaw/** Control by law */
            };

            /** This enum represents the conic method for advanced symmetric conic */
            public: enum DefineMethod
            {
                DefineMethodBoundaryPlusCenter/** conic shape controlled by boundary and center values */,
                DefineMethodBoundaryPlusRho/** conic shape controlled by boundary and rho values */,
                DefineMethodCenterPlusRho/** conic shape controlled by center and rho values */
            };

            private: ConicCrossSectionImpl * m_coniccrosssection_impl;
            private: friend class  _ConicCrossSectionBuilder;
            protected: ConicCrossSection();
            public: ~ConicCrossSection();
            /**Returns  the first offset for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * FirstOffset
            (
            );
            /** Sets the first offset for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::FirstOffset NXOpen::GeometricUtilities::ConicCrossSection::FirstOffset@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using NXOpen::GeometricUtilities::ConicCrossSection::FirstOffset and NXOpen::Expression::SetRightHandSide.") void SetFirstOffset
            (
                const NXString & offset /** offset */ 
            );
            /** Sets the first offset for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::FirstOffset NXOpen::GeometricUtilities::ConicCrossSection::FirstOffset@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetFirstOffset
            (
                const char * offset /** offset */ 
            );
            /**Returns  the second offset for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * SecondOffset
            (
            );
            /** Sets the second offset for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::SecondOffset NXOpen::GeometricUtilities::ConicCrossSection::SecondOffset@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using NXOpen::GeometricUtilities::ConicCrossSection::SecondOffset and NXOpen::Expression::SetRightHandSide.") void SetSecondOffset
            (
                const NXString & offset /** offset */ 
            );
            /** Sets the second offset for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::SecondOffset NXOpen::GeometricUtilities::ConicCrossSection::SecondOffset@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetSecondOffset
            (
                const char * offset /** offset */ 
            );
            /**Returns  the first offset option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::OffsetMethod FirstOffsetOption
            (
            );
            /**Sets  the first offset option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetFirstOffsetOption
            (
                NXOpen::GeometricUtilities::ConicCrossSection::OffsetMethod method /** method */ 
            );
            /**Returns  the second offset option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::OffsetMethod SecondOffsetOption
            (
            );
            /**Sets  the second offset option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSecondOffsetOption
            (
                NXOpen::GeometricUtilities::ConicCrossSection::OffsetMethod method /** method */ 
            );
            /**Returns  the rho expression for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Rho
            (
            );
            /** Sets a rho expression for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::Rho NXOpen::GeometricUtilities::ConicCrossSection::Rho@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using NXOpen::GeometricUtilities::ConicCrossSection::Rho and NXOpen::Expression::SetRightHandSide.") void SetRho
            (
                const NXString & rho /** rho */ 
            );
            /** Sets a rho expression for the conic section with face blend.
                    
             <br>  @deprecated Deprecated in NX9.0.0.  To set the value of the expression modify the expression directly using @link NXOpen::GeometricUtilities::ConicCrossSection::Rho NXOpen::GeometricUtilities::ConicCrossSection::Rho@endlink  and @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink . <br>  

             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetRho
            (
                const char * rho /** rho */ 
            );
            /**Returns  the depth expression for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Depth
            (
            );
            /**Returns  the shape skew expression for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * ShapeSkew
            (
            );
            /**Returns  the offset skew ratio expression for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * OffsetSkewRatio
            (
            );
            /**Returns  the rho option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::RhoMethod RhoOption
            (
            );
            /**Sets  the rho option for the conic section with face blend
                    
             <br>  Created in NX4.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRhoOption
            (
                NXOpen::GeometricUtilities::ConicCrossSection::RhoMethod method /** method */ 
            );
            /**Returns  the depth option for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::DepthMethod DepthOption
            (
            );
            /**Sets  the depth option for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDepthOption
            (
                NXOpen::GeometricUtilities::ConicCrossSection::DepthMethod method /** method */ 
            );
            /**Returns  the shape skew option for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::ShapeSkewMethod ShapeSkewOption
            (
            );
            /**Sets  the shape skew option for the conic section with face blend
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetShapeSkewOption
            (
                NXOpen::GeometricUtilities::ConicCrossSection::ShapeSkewMethod method /** method */ 
            );
            /**Returns  the First Offset Law builder 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * FirstLawControl
            (
            );
            /**Returns  the Second Offset Law builder 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * SecondLawControl
            (
            );
            /**Returns  the Rho Law builder 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * RhoLawControl
            (
            );
            /**Returns  the Depth Law builder 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * DepthLawControl
            (
            );
            /**Returns  the Shape Skew Law builder 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * ShapeSkewLawControl
            (
            );
            /** Sets a constant radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlConstantFirstOffset
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a constant radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlConstantFirstOffset
            (
                const char * radius /** The value to be set */
            );
            /** Sets a start radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlFirstOffsetStartRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a start radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlFirstOffsetStartRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a end radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlFirstOffsetEndRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a end radius for the first law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlFirstOffsetEndRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a constant radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlConstantSecondOffset
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a constant radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlConstantSecondOffset
            (
                const char * radius /** The value to be set */
            );
            /** Sets a start radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlSecondOffsetStartRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a start radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlSecondOffsetStartRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a end radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlSecondOffsetEndRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a end radius for the second law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlSecondOffsetEndRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a constant radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlConstantRho
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a constant radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlConstantRho
            (
                const char * radius /** The value to be set */
            );
            /** Sets a start radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlRhoStartRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a start radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlRhoStartRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a end radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlRhoEndRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a end radius for the rho law control of the conic section with face blend.
                    
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlRhoEndRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a constant radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlConstantDepth
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a constant radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlConstantDepth
            (
                const char * radius /** The value to be set */
            );
            /** Sets a start radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlDepthStartRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a start radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlDepthStartRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a end radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlDepthEndRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a end radius for the depth law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlDepthEndRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a constant radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlConstantShapeSkew
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a constant radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlConstantShapeSkew
            (
                const char * radius /** The value to be set */
            );
            /** Sets a start radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlShapeSkewStartRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a start radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlShapeSkewStartRadius
            (
                const char * radius /** The value to be set */
            );
            /** Sets a end radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLawControlShapeSkewEndRadius
            (
                const NXString & radius /** The value to be set */
            );
            /** Sets a end radius for the shape skew law control of the conic section with face blend.
                    
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            void SetLawControlShapeSkewEndRadius
            (
                const char * radius /** The value to be set */
            );
            /**Returns  the conic method for the advanced symmetric conic section with face blend
                    
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection::DefineMethod ConicMethod
            (
            );
            /**Sets  the conic method for the advanced symmetric conic section with face blend
                    
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetConicMethod
            (
                NXOpen::GeometricUtilities::ConicCrossSection::DefineMethod method /** method */ 
            );
            /**Returns  the flag to link multi-transition law types
                    
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : None */
            public: bool TransitionLinkFlag
            (
            );
            /**Sets  the flag to link multi-transition law types
                    
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTransitionLinkFlag
            (
                bool transitionLinkFlag /** transition link flag */ 
            );
            /**Returns  the first constraint curve collector
                     
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * FirstConstraintCurveCollector
            (
            );
            /**Sets  the first constraint curve collector
                     
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetFirstConstraintCurveCollector
            (
                NXOpen::ScCollector * collector /** collector */ 
            );
            /**Returns  the second constraint curve collector
                     
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * SecondConstraintCurveCollector
            (
            );
            /**Sets  the second constraint curve collector
                     
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSecondConstraintCurveCollector
            (
                NXOpen::ScCollector * collector /** collector */ 
            );
            /** Validate whether the inputs to the component are sufficient for 
                        commit to be called.  If the component is not in a state to commit
                        then an exception is thrown.  For example, if the component requires
                        you to set some property, this method will throw an exception if
                        you haven't set it.  This method throws a not-yet-implemented
                        NXException for some components.
                     @return  Was self validation successful 
             <br>  Created in NX3.0.1.  <br>  
             <br> License requirements : None */
            public: virtual bool Validate
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
