#ifndef NXOpen_LAYOUT2D_INSERTCOMPONENTBUILDER_HXX_INCLUDED
#define NXOpen_LAYOUT2D_INSERTCOMPONENTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Layout2d_InsertComponentBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Layout2d_ComponentSettingsBlockBuilder.hxx>
#include <NXOpen/Layout2d_InsertComponentBuilder.hxx>
#include <NXOpen/Layout2d_Types.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_layout2d_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Layout2d
    {
        class InsertComponentBuilder;
    }
    class Builder;
    namespace Layout2d
    {
        class ComponentSettingsBlockBuilder;
    }
    class Sketch;
    namespace Layout2d
    {
        class _InsertComponentBuilderBuilder;
        class InsertComponentBuilderImpl;
        /** Represents a Builder for Insert Component functionality which will insert a 2D
             *  Component instance in the active sketch   <br> To create a new instance of this class, use @link NXOpen::Layout2d::ComponentCollection::CreateInsertComponentBuilder  NXOpen::Layout2d::ComponentCollection::CreateInsertComponentBuilder @endlink  <br> 
         <br>  Created in NX10.0.0.  <br>  
        */
        class NXOPENCPP_LAYOUT2DEXPORT  InsertComponentBuilder : public NXOpen::Builder
        {
            private: InsertComponentBuilderImpl * m_insertcomponentbuilder_impl;
            private: friend class  _InsertComponentBuilderBuilder;
            protected: InsertComponentBuilder();
            public: ~InsertComponentBuilder();
            /**Returns  the point specified to put the 2D Component instance
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point3d SpecifyPoint
            (
            );
            /**Sets  the point specified to put the 2D Component instance
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_layout ("NX Layout") */
            public: void SetSpecifyPoint
            (
                const NXOpen::Point3d & specifyPoint /** specifypoint */ 
            );
            /**Returns  the Component settings block builder which holds the component settings builder 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Layout2d::ComponentSettingsBlockBuilder * Settings
            (
            );
            /** Sets the path of the reuse library for the 2D Component 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_layout ("NX Layout") */
            public: void SetPath
            (
                const NXString & path /** the path of the 2D Component */
            );
            /** Sets the path of the reuse library for the 2D Component 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_layout ("NX Layout") */
            void SetPath
            (
                const char * path /** the path of the 2D Component */
            );
            /** Sets the location type of the 2D Component indicating local, native or team center
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_layout ("NX Layout") */
            public: void SetLocation
            (
                NXOpen::Layout2d::Layout2dDefinitionLocation locationType /** locationtype */ 
            );
            /**Returns  the sketch to insert the 2D Component 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Sketch * Sketch
            (
            );
            /**Sets  the sketch to insert the 2D Component 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_layout ("NX Layout") */
            public: void SetSketch
            (
                NXOpen::Sketch * sketch /** sketch */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
