#ifndef NXOpen_CAE_ORDEREDSELECTION_HXX_INCLUDED
#define NXOpen_CAE_ORDEREDSELECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_OrderedSelection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/SelectionMethod.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class OrderedSelection;
    }
    class Arc;
    namespace CAE
    {
        class CAEEdge;
    }
    namespace CAE
    {
        class FEElement;
    }
    namespace CAE
    {
        class FENode;
    }
    namespace CAE
    {
        class MeshPoint;
    }
    class Conic;
    class Line;
    class Point;
    class SelectionMethod;
    class Spline;
    class TaggedObject;
    namespace CAE
    {
    }
    namespace CAE
    {
        class _OrderedSelectionBuilder;
        class OrderedSelectionImpl;
        /** Represents list of ordered selection entitites
         <br>  Created in NX11.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  OrderedSelection : public NXOpen::TaggedObject
        {
            private: OrderedSelectionImpl * m_orderedselection_impl;
            private: friend class  _OrderedSelectionBuilder;
            protected: OrderedSelection();
            public: ~OrderedSelection();
            /** Adds a mesh point to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::CAE::MeshPoint * entity /** mesh point to be added */
            );
            /** Adds a point to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::Point * entity /** point to be added */
            );
            /** Adds a node to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::CAE::FENode * entity /** node to be added */
            );
            /** Adds a element to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::CAE::FEElement * entity /** node to be added */
            );
            /** Adds a polygon edge  to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::CAE::CAEEdge * entity /** point to be added */,
                bool flipDirection /** flip the direction of edge*/
            );
            /** Adds a line to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::Line * entity /** point to be added */,
                bool flipDirection /** flip the direction of line*/
            );
            /** Adds a arc to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::Arc * entity /** point to be added */,
                bool flipDirection /** flip the direction of arc*/
            );
            /** Adds a conic to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::Conic * entity /** point to be added */,
                bool flipDirection /** flip the direction of conic*/
            );
            /** Adds a spline to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::Spline * entity /** point to be added */,
                bool flipDirection /** flip the direction of spline*/
            );
            /** Adds objects contained in the method to the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Add
            (
                NXOpen::SelectionMethod * selectionMethod /** selection method containing objects to add */
            );
            /** Removes a tagged object from the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Remove
            (
                NXOpen::TaggedObject * entity /** object to be removed*/
            );
            /** Removes objects contained in the method from the list 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Remove
            (
                NXOpen::SelectionMethod * selectionMethod /** selection method containing objects to remove */
            );
            /** Removes all objects from the list
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void Clear
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
