#ifndef NXOpen_FEATURES_MIRRORFACEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_MIRRORFACEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_MirrorFaceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_FaceRecognitionBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class MirrorFaceBuilder;
    }
    namespace Features
    {
        class FaceRecognitionBuilder;
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    class Plane;
    class SelectISurface;
    namespace Features
    {
        class _MirrorFaceBuilderBuilder;
        class MirrorFaceBuilderImpl;
        /**
            Represents a @link NXOpen::Features::MirrorFace NXOpen::Features::MirrorFace@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::FeatureCollection::CreateMirrorFaceBuilder  NXOpen::Features::FeatureCollection::CreateMirrorFaceBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        FaceToMirror.CloneEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.CoaxialEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.CoplanarAxesEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.CoplanarEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.EqualDiameterEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.OffsetEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.ParallelEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.PatternEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.PerpendicularEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.SameEntryEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.SameEntrySurfaceEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.SameOrbitEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.SymmetricEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.TangentEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.ThicknessChainEnabled </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        FaceToMirror.UseFaceBrowse </term> <description> 
         
        1 </description> </item> 

        </list> 

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  MirrorFaceBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** Represents the mirror plane options */
            public: enum MirrorPlaneOptions
            {
                MirrorPlaneOptionsExisting/** Existing Plane */,
                MirrorPlaneOptionsNew/** New Plane */
            };

            private: MirrorFaceBuilderImpl * m_mirrorfacebuilder_impl;
            private: friend class  _MirrorFaceBuilderBuilder;
            protected: MirrorFaceBuilder();
            public: ~MirrorFaceBuilder();
            /**Returns  the face to mirror. Please refer @link NXOpen::Features::FaceRecognitionBuilder NXOpen::Features::FaceRecognitionBuilder@endlink  for details. 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::FaceRecognitionBuilder * FaceToMirror
            (
            );
            /**Returns  the mirror plane option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::MirrorFaceBuilder::MirrorPlaneOptions MirrorPlaneOption
            (
            );
            /**Sets  the mirror plane option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR cam_base ("CAM BASE") OR insp_programming ("INSPECTION PROGRAMMING") */
            public: void SetMirrorPlaneOption
            (
                NXOpen::Features::MirrorFaceBuilder::MirrorPlaneOptions mirrorPlaneOptions /** mirror plane options */ 
            );
            /**Returns  the existing mirror plane 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectISurface * ExistingMirrorPlane
            (
            );
            /**Returns  the new mirror plane 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Plane * NewMirrorPlane
            (
            );
            /**Sets  the new mirror plane 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR cam_base ("CAM BASE") OR insp_programming ("INSPECTION PROGRAMMING") */
            public: void SetNewMirrorPlane
            (
                NXOpen::Plane * newMirrorPlane /** new mirror plane */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
