#ifndef NXOpen_FEATURES_SHEETMETAL_GUSSETBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_GUSSETBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_GussetBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class GussetBuilder;
        }
    }
    class Edge;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    class Plane;
    class Section;
    class SelectEdge;
    class SelectFace;
    namespace Features
    {
        namespace SheetMetal
        {
            class _GussetBuilderBuilder;
            class GussetBuilderImpl;
            /**
                Represents a NX Sheet Metal @link NXOpen::Features::Gusset NXOpen::Features::Gusset@endlink  builder
                 <br> To create a new instance of this class, use @link NXOpen::Features::SheetMetal::SheetmetalManager::CreateGussetBuilder  NXOpen::Features::SheetMetal::SheetmetalManager::CreateGussetBuilder @endlink  <br> 
            Default values.
            <list type="table"> 
             
            <listheader><term> 
            Property</term>  <description> 
            Value</description> </listheader>
            <item><term> 
             
            CornerRadius.Value </term> <description> 
             
            1 (millimeters part), 0.05 (inches part) </description> </item> 

            <item><term> 
             
            Depth.Value </term> <description> 
             
            10 (millimeters part), 1 (inches part) </description> </item> 

            <item><term> 
             
            DieRadius.Value </term> <description> 
             
            2 (millimeters part), 0.1 (inches part) </description> </item> 

            <item><term> 
             
            PlacementCount </term> <description> 
             
            2 </description> </item> 

            <item><term> 
             
            PlacementDistance.Value </term> <description> 
             
            10 (millimeters part), 1 (inches part) </description> </item> 

            <item><term> 
             
            PlacementSpacing.Value </term> <description> 
             
            20 (millimeters part), 2 (inches part) </description> </item> 

            <item><term> 
             
            PlacementType </term> <description> 
             
            Single </description> </item> 

            <item><term> 
             
            PunchRadius.Value </term> <description> 
             
            2 (millimeters part), 0.1 (inches part) </description> </item> 

            <item><term> 
             
            Shape </term> <description> 
             
            Square </description> </item> 

            <item><term> 
             
            SideAngle.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            Width.Value </term> <description> 
             
            10 (millimeters part), 1 (inches part) </description> </item> 

            <item><term> 
             
            WidthSide </term> <description> 
             
            Side1 </description> </item> 

            </list> 

             <br>  Created in NX7.5.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  GussetBuilder : public NXOpen::Features::FeatureBuilder
            {
                /** This enum represents the two Gusset Feature types. */
                public: enum Types
                {
                    TypesAutomaticProfile/** Gusset(s) will be created between the planar faces adjacent to the selected bend face. */,
                    TypesUserDefinedProfile/** Gusset will be created using a profile defined by the user. */
                };

                /** This enum represents the different options for thickening the user defined profile Gusset. */
                public: enum WidthSides
                {
                    WidthSidesSide1/** The Gusset will be created on the side of plane normal of the user defined profile. */,
                    WidthSidesSide2/** The Gusset will be created on the opposite side of the plane normal of the user defined profile. */,
                    WidthSidesSymmetric/** The Gusset will be created on both sides of the plane of the user defined profile. */
                };

                /** This enum represents the different options for placing an automatic profile Gusset. */
                public: enum PlacementTypes
                {
                    PlacementTypesSingle/** One Gusset will be created at an offset from an edge on the selected bend face. */,
                    PlacementTypesFit/** Users will specify the number of occurances of Gusset on the selected bend face and software will calculate the spacing. */,
                    PlacementTypesFill/** Users will specify the spacing of Gussets on the selected bend face and software will calculate the number of occurances. */,
                    PlacementTypesFixed/** Users will specify the number of occurances and the spacing for Gussets on the selected bend face. */
                };

                /** This enum represents the two different shapes for Gusset. */
                public: enum Shapes
                {
                    ShapesSquare/** Specifies a square shape for the Gusset */,
                    ShapesRound/** Specifies a round shape for the Gusset */
                };

                private: GussetBuilderImpl * m_gussetbuilder_impl;
                private: friend class  _GussetBuilderBuilder;
                protected: GussetBuilder();
                public: ~GussetBuilder();
                /**Returns  the section 
                             <br> 
                                This section object contains a planar set of connected curves that will be used to
                                create a Gusset of type @link NXOpen::Features::SheetMetal::GussetBuilder::TypesUserDefinedProfile NXOpen::Features::SheetMetal::GussetBuilder::TypesUserDefinedProfile@endlink . This
                                profile can be closed or open. If it is open, then the end points can touch face(s). The profile must not intersect the
                                solid body. If an open profile does not intersect or touch any face, each end will be extended until it touches a face.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Section * Section
                (
                );
                /**Returns  the width side 
                             <br> 
                                Defines the side of the profile to which material should be added or from which material should be removed to construct 
                                the feature. 

                                The side option is not required when the profile is closed.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::GussetBuilder::WidthSides WidthSide
                (
                );
                /**Sets  the width side 
                             <br> 
                                Defines the side of the profile to which material should be added or from which material should be removed to construct 
                                the feature. 

                                The side option is not required when the profile is closed.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetWidthSide
                (
                    NXOpen::Features::SheetMetal::GussetBuilder::WidthSides widthSide /** widthside */ 
                );
                /**Returns  the bend face 
                             <br> 
                                Selects the bend face along which the gusset is placed.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectFace * BendFace
                (
                );
                /**Returns  the start edge  
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use @link NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane@endlink  to locate automatic profile gussets from NX10 onwards.  
                                Selects the edge on the bend face to determine the gusset offset direction.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectEdge * StartEdge
                (
                );
                /** Get the edges on the bend face that can be selected as Start Edge.
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use @link NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane@endlink  to locate automatic profile gussets from NX10 onwards. 
                                Get the edges on the bend face that can be selected as Start Edge.
                                If there is no Bend Face, then no edges will be returned.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: void GetStartEdgeCandidates
                (
                    std::vector<NXOpen::Edge *> & candidateEdges /** An array of edges that are valid for selection as start edge */
                );
                /**Returns  the placement type 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use patterns to create multiple gussets from NX10 onwards. 
                                Specify the Gusset placement option. See the description of @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  elements for details.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes PlacementType
                (
                );
                /**Sets  the placement type 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use patterns to create multiple gussets from NX10 onwards. 
                                Specify the Gusset placement option. See the description of @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  elements for details.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetPlacementType
                (
                    NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes placementType /** placementtype */ 
                );
                /**Returns  the placement distance 
                             <br> 
                               Only use this option to edit gussets created prior to NX10. 
                               Use @link NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane@endlink  to locate automatic profile gussets from NX10 onwards. 
                               If the @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  is set to @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesSingle NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesSingle@endlink , then this option
                               represents the location of the automatic profile Gusset from one of the ends of the selected bend face. The distance is measured in a direction going from 
                               the start end to the other end. Users can specify which end of the selected bend face to use as the start.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * PlacementDistance
                (
                );
                /** Get the placement origin and direction. 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use @link NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane NXOpen::Features::SheetMetal::GussetBuilder::DatumPlane@endlink  to locate automatic profile gussets from NX10 onwards.  
                                Get the point from which the placement distance will be measured and the 
                                direction along which the positive distance is defined.
                             <br> 
                         @return  Direction along which the placement distance is measured. 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Vector3d GetPlacementOriginAndDirection
                (
                    NXOpen::Point3d* origin /** Start point from which placement distance is measured. */
                );
                /**Returns  the placement count 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use patterns to create multiple gussets from NX10 onwards. 
                                This value is used if the @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  is set 
                                to @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit@endlink  or
                                @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed@endlink . It represents 
                                the number of occurances of the automatic profile Gusset to create on the selected bend face. The count
                                must be greater than zero for @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit@endlink  and greater than one for
                                @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed@endlink .
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: int PlacementCount
                (
                );
                /**Sets  the placement count 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                Use patterns to create multiple gussets from NX10 onwards. 
                                This value is used if the @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  is set 
                                to @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit@endlink  or
                                @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed@endlink . It represents 
                                the number of occurances of the automatic profile Gusset to create on the selected bend face. The count
                                must be greater than zero for @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFit@endlink  and greater than one for
                                @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed@endlink .
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetPlacementCount
                (
                    int placementCount /** placementcount */ 
                );
                /**Returns  the placement spacing  
                             <br> 
                               Only use this option to edit gussets created prior to NX10.
                               Use patterns to create multiple gussets from NX10 onwards. 
                               This value is used if the @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypes@endlink  is set 
                                to @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFill NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFill@endlink  or
                                @link NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed NXOpen::Features::SheetMetal::GussetBuilder::PlacementTypesFixed@endlink . It represents 
                                the spacing between the automatic profile Gussets to create on the selected bend face.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * PlacementSpacing
                (
                );
                /**Returns  the plane of the gusset profile.   
                             <br> 
                                Returns the datum plane on the bend face that contains the profile of the automatic profile gusset.
                             <br> 
                        
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Plane * DatumPlane
                (
                );
                /**Sets  the plane of the gusset profile.   
                             <br> 
                                Returns the datum plane on the bend face that contains the profile of the automatic profile gusset.
                             <br> 
                        
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetDatumPlane
                (
                    NXOpen::Plane * dPlane /** dplane */ 
                );
                /**Returns  the depth 
                             <br> 
                                This value is used for the automatic profile Gussets. It represents the distance from the outer
                                bend face of the selected bends along the bisector of the planar faces adjacent to the outer bend face.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Depth
                (
                );
                /**Returns  the shape 
                             <br>  See @link NXOpen::Features::SheetMetal::GussetBuilder::Shapes NXOpen::Features::SheetMetal::GussetBuilder::Shapes@endlink  for details.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::GussetBuilder::Shapes Shape
                (
                );
                /**Sets  the shape 
                             <br>  See @link NXOpen::Features::SheetMetal::GussetBuilder::Shapes NXOpen::Features::SheetMetal::GussetBuilder::Shapes@endlink  for details.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetShape
                (
                    NXOpen::Features::SheetMetal::GussetBuilder::Shapes shape /** shape */ 
                );
                /**Returns  the width value for the Gusset 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Width
                (
                );
                /**Returns  the side angle. The value must be greater than or equal to zero. 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * SideAngle
                (
                );
                /**Returns  the corner radius 
                             <br> 
                                Only use this option to edit gussets created prior to NX10.
                                From NX10 onwards, this is going to be automatically determined by adding the material thickness to the @link NXOpen::Features::SheetMetal::GussetBuilder::PunchRadius NXOpen::Features::SheetMetal::GussetBuilder::PunchRadius@endlink 
                                This value is used only for the @link NXOpen::Features::SheetMetal::GussetBuilder::ShapesSquare NXOpen::Features::SheetMetal::GussetBuilder::ShapesSquare@endlink  shape. The value must be greater than or equal to zero.
                             <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * CornerRadius
                (
                );
                /**Returns  the punch radius value 
                         <br>  
                               The application of the punch radius has changed from NX10 onwards, to ensure material thickness is constant in the gusset. 
                               See the legend in the gusset dialog for more information. 
                         <br> 
                        
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * PunchRadius
                (
                );
                /**Returns  the die radius value of the sharp edges of the bottom face. The value must be greater than or equal to zero. 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * DieRadius
                (
                );
                /**Returns  the type of Gusset feature 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::GussetBuilder::Types Type
                (
                );
                /**Sets  the type of Gusset feature 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetType
                (
                    NXOpen::Features::SheetMetal::GussetBuilder::Types type /** type */ 
                );
                /** Cycles the available solutions when a user defined profile intersects the solid body. If there is
                            only one working solution then it will be automatically selected and this method will not do anything. 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void AlternateSolution
                (
                );
                /**  Whether this is a pre-NX10 gusset. 
                             <br> 
                                Use this to determine whether the gusset is created prior to NX10.
                             <br> 
                        
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: bool GetIsPreNx10
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
