#ifndef NXOpen_FEATURES_DRAWSHAPES_EDITCURVEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_DRAWSHAPES_EDITCURVEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_DrawShapes_EditCurveBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_GeometricConstraintDataManager.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace DrawShapes
        {
            class EditCurveBuilder;
        }
    }
    class Builder;
    class Expression;
    namespace Features
    {
        class GeometricConstraintDataManager;
    }
    namespace Features
    {
        namespace DrawShapes
        {
            class _EditCurveBuilderBuilder;
            class EditCurveBuilderImpl;
            /** Represents @link  NXOpen::Features::DrawShapes::EditCurveBuilder   NXOpen::Features::DrawShapes::EditCurveBuilder @endlink 
                    allowing user to a edit curve.
                 <br> To create a new instance of this class, use @link NXOpen::Features::DrawShapes::DrawShapeCollection::CreateEditCurveBuilder  NXOpen::Features::DrawShapes::DrawShapeCollection::CreateEditCurveBuilder @endlink  <br> 
             <br>  Created in NX1926.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  EditCurveBuilder : public NXOpen::Builder
            {
                /** Circle definition options */
                public: enum CircleDefinitionOption
                {
                    CircleDefinitionOptionThreePoints/** three points */ ,
                    CircleDefinitionOptionCenterandRadius/** centerand radius */ 
                };

                private: EditCurveBuilderImpl * m_editcurvebuilder_impl;
                private: friend class  _EditCurveBuilderBuilder;
                protected: EditCurveBuilder();
                public: ~EditCurveBuilder();
                /**Returns  the circle definition options 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::DrawShapes::EditCurveBuilder::CircleDefinitionOption CircleDefinitionOptions
                (
                );
                /**Sets  the circle definition options 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : nx_draw_shape (" NX Draw Shape Functionality") */
                public: void SetCircleDefinitionOptions
                (
                    NXOpen::Features::DrawShapes::EditCurveBuilder::CircleDefinitionOption circleDefinitionOptions /** circledefinitionoptions */ 
                );
                /**Returns  the constraint manager 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::GeometricConstraintDataManager * ConstraintManager
                (
                );
                /**Returns  the flag indicating if spline can be closed 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : None */
                public: bool IsClosed
                (
                );
                /**Sets  the flag indicating if spline can be closed 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : nx_draw_shape (" NX Draw Shape Functionality") */
                public: void SetClosed
                (
                    bool isClosed /** isclosed */ 
                );
                /**Returns  the radius 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Radius
                (
                );
                /** Evaluates the curve after editing defining data. 
                 <br>  Created in NX1926.0.0.  <br>  
                 <br> License requirements : nx_draw_shape (" NX Draw Shape Functionality") */
                public: void EvaluateCurve
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
