<?xml version="1.0"?>
<doc>
    <assembly>
        <name>NXOpen.Guide</name>
    </assembly>
    <members>
        <member name="T:NXOpen.Guide">
            <summary>
            Simple functions used in the "Getting Started with NX Open" guide
            </summary>
        </member>
        <member name="M:NXOpen.Guide.InfoWrite(System.String)">
            <summary>Writes a string to the Info window (with no newline added)</summary>
            <param name="info">The string to write</param>      
        </member>
        <member name="M:NXOpen.Guide.InfoWriteLine(System.String)">
            <summary>Writes a string to the Info window (with a newline added)</summary>
            <param name="info">The string to write</param>            
        </member>
        <member name="M:NXOpen.Guide.CreatePoint(System.Double,System.Double,System.Double)">
            <summary>Creates an NXOpen.Point object</summary>
            <param name="x">x coordinate</param>
            <param name="y">y coordinate</param>
            <param name="z">z coordinate</param>
            <returns>The point that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.CreateLine(System.Double,System.Double,System.Double,System.Double,System.Double,System.Double)">
            <summary>Creates an NXOpen.Line object</summary>
            <param name="x0">X-coordinate of start point</param>
            <param name="y0">Y-coordinate of start point</param>
            <param name="z0">Z-coordinate of start point</param>
            <param name="x1">X-coordinate of end   point</param>
            <param name="y1">Y-coordinate of end   point</param>
            <param name="z1">Z-coordinate of end   point</param>
            <returns>The line that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.CreateCircle(System.Double,System.Double,System.Double,System.Double)">
            <summary>Creates a circle parallel to the XY-plane</summary>
            <param name="cx">X-coordinate of center point (in absolute coordinates)</param>
            <param name="cy">Y-coordinate of center point (in absolute coordinates)</param>
            <param name="cz">Z-coordinate of center point (in absolute coordinates)</param>
            <param name="radius">Radius</param>
            <returns>The arc that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.CreateCircle(NXOpen.Point3d,NXOpen.Vector3d,System.Double)">
            <summary>Creates a circle from center, normal, radius</summary>
            <param name="center">Center point (in absolute coordinates)</param>
            <param name="axisZ">Unit vector normal to plane of circle</param>
            <param name="radius">Radius</param>
            <returns>The arc that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.CurvePoint(NXOpen.Curve,System.Double)">
            <summary>Calculate a point on a curve at a given parameter value</summary>
            <param name="curve">The curve</param>
            <param name="t">The parameter value</param>
            <returns>Position on curve</returns>
        </member>
        <member name="M:NXOpen.Guide.CurveTangent(NXOpen.Curve,System.Double)">
            <summary>Calculate a unit tangent vector on a curve at a given parameter value</summary>
            <param name="curve">The curve</param>
            <param name="t">The parameter value</param>
            <returns>Unit tangent vector at location on curve</returns>
        </member>
        <member name="M:NXOpen.Guide.CreateSphere(System.Double,System.Double,System.Double,System.Double)">
            <summary>Creates a sphere feature, given center coordinates and diameter</summary>
            <param name="cx">X-coordinate of center point (in absolute coordinates)</param>
            <param name="cy">Y-coordinate of center point (in absolute coordinates)</param>
            <param name="cz">Z-coordinate of center point (in absolute coordinates)</param>
            <param name="diameter">Diameter</param>
            <returns>An NXOpen.Sphere object</returns>
        </member>
        <member name="M:NXOpen.Guide.CreateCylinder(NXOpen.Point3d,NXOpen.Vector3d,System.Double,System.Double)">
            <summary>Creates a Cylinder feature</summary>
            <param name="origin">The point at the cnter of the base of the cylinder</param>
            <param name="axis">A vector along the centerline of the cylinder</param>
            <param name="diameter">The diameter of the cylinder</param>
            <param name="height">The height of the cylinder</param>
            <returns>The NXOpen.Features.Cylinder object that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.Unite(NXOpen.Body,NXOpen.Body)">
            <summary>Unites two bodies to create a boolean feature</summary>
            <param name="target">The target body</param>
            <param name="tool">The tool body</param>
            <returns>The NXOpen.Features.BooleanFeature object that was created</returns>
        </member>
        <member name="M:NXOpen.Guide.GetWorkPart">
            <summary>Gets the work part</summary>
            <returns>The work part</returns>
        </member>
        <member name="M:NXOpen.Guide.GetAxes(NXOpen.Vector3d)">
            <summary>Construct three axes, given a Z-axis vector</summary>
            <param name="axisZ">Vector to be used as the Z-axis (length doesn't matter)</param>
            <returns>Arbitrary X and Y axes orthogonal to give Z-axis</returns>
            <remarks>
            The X and Y axes are constructed arbitrarily, so use this function only
            when you don't care about the directions of these other axes.
            </remarks>      
        </member>
        <member name="M:NXOpen.Guide.VectorCross(NXOpen.Vector3d,NXOpen.Vector3d)">
            <summary>Calculates the cross product (vector product) of two vectors</summary>
            <param name="u">First vector</param>
            <param name="v">Second vector</param>
            <returns>Cross product</returns>
        </member>
        <member name="M:NXOpen.Guide.VectorUnit(NXOpen.Vector3d)">
            <summary>Unitizes a given vector</summary>
            <param name="u">Vector to be unitized</param>
            <returns>Unit vector in same direction</returns>
            <remarks>
            If the input is the zero vector, then each component
            of the returned vector will be NaN (not a number).
            </remarks>
        </member>
    </members>
</doc>
