#ifndef NXOpen_ANNOTATIONS_OFFSETCENTERPOINTBUILDER_HXX_INCLUDED
#define NXOpen_ANNOTATIONS_OFFSETCENTERPOINTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_OffsetCenterPointBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_BaseSymbolBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Annotations
    {
        class OffsetCenterPointBuilder;
    }
    namespace Annotations
    {
        class BaseSymbolBuilder;
    }
    class NXColor;
    class SelectNXObject;
    namespace Annotations
    {
        class _OffsetCenterPointBuilderBuilder;
        class OffsetCenterPointBuilderImpl;
        /** Represents a @link NXOpen::Annotations::OffsetCenterPoint NXOpen::Annotations::OffsetCenterPoint@endlink  builder  <br> To create a new instance of this class, use @link NXOpen::Annotations::OffsetCenterPointCollection::CreateOffsetCenterPointBuilder  NXOpen::Annotations::OffsetCenterPointCollection::CreateOffsetCenterPointBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        CenterCross </td> <td> 
         
        3.175 (millimeters part), 0.125 (inches part) </td> </tr> 

        <tr><td> 
         
        DisplayStyle </td> <td> 
         
        CenterPoint </td> </tr> 

        <tr><td> 
         
        Distance </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        Extension </td> <td> 
         
        6.35 (millimeters part), 0.25 (inches part) </td> </tr> 

        <tr><td> 
         
        Gap </td> <td> 
         
        1.5875 (millimeters part), 0.0625 (inches part) </td> </tr> 

        <tr><td> 
         
        OffsetMethod </td> <td> 
         
        HorizontalDistanceFromArc </td> </tr> 

        <tr><td> 
         
        Width </td> <td> 
         
        Thin </td> </tr> 

        </table>  

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_ANNOTATIONSEXPORT  OffsetCenterPointBuilder : public NXOpen::Annotations::BaseSymbolBuilder
        {
            /** the valid offset method types */
            public: enum Offset
            {
                OffsetHorizontalDistanceFromArc/** horizontal distance from arc */,
                OffsetHorizontalDistanceFromCenter/** horizontal distance from center */,
                OffsetHorizontalDistanceByPosition/** horizontal distance by position, applicable only for creation*/,
                OffsetVerticalDistanceFromArc/** vertical distance from arc */,
                OffsetVerticalDistanceFromCenter/** vertical distance from center */,
                OffsetVerticalDistanceByPosition/** vertical distance by position, applicable only for creation */
            };

            /** the valid types of display styles */
            public: enum Display
            {
                DisplayCenterPoint/** center point */,
                DisplayCenterLine/** center line */,
                DisplayCenterLineWithExtension/** center line with extension */
            };

            /** the valid types of offset center point thickness */
            public: enum Thickness
            {
                ThicknessThin/** thin */,
                ThicknessNormal/** normal */,
                ThicknessThick/** thick */,
                ThicknessOne/** Width One */ = 6,
                ThicknessTwo/** Width Two */,
                ThicknessThree/** Width Three */,
                ThicknessFour/** Width Four */,
                ThicknessFive/** Width Five */,
                ThicknessSix/** Width Six */,
                ThicknessSeven/** Width Seven */,
                ThicknessEight/** Width Eight */,
                ThicknessNine/** Width Nine */
            };

            private: OffsetCenterPointBuilderImpl * m_offsetcenterpointbuilder_impl;
            private: friend class  _OffsetCenterPointBuilderBuilder;
            protected: OffsetCenterPointBuilder();
            public: ~OffsetCenterPointBuilder();
            /**Returns  the location 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectNXObject * Location
            (
            );
            /**Returns  the offset method 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Offset OffsetMethod
            (
            );
            /**Sets  the offset method 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetOffsetMethod
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Offset offsetMethod /** offsetmethod */ 
            );
            /**Returns  the offset distance, valid for all offset method types except those by position 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: double Distance
            (
            );
            /**Sets  the offset distance, valid for all offset method types except those by position 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetDistance
            (
                double distance /** distance */ 
            );
            /**Returns  the inherit 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectNXObject * Inherit
            (
            );
            /**Returns  the gap 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: double Gap
            (
            );
            /**Sets  the gap 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetGap
            (
                double gap /** gap */ 
            );
            /**Returns  the center cross size 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: double CenterCross
            (
            );
            /**Sets  the center cross size 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetCenterCross
            (
                double centerCross /** centercross */ 
            );
            /**Returns  the extension 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: double Extension
            (
            );
            /**Sets  the extension 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetExtension
            (
                double extension /** extension */ 
            );
            /**Returns  the display style 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Display DisplayStyle
            (
            );
            /**Sets  the display style 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetDisplayStyle
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Display display /** display */ 
            );
            /**Returns  the color 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::NXColor * Color
            (
            );
            /**Sets  the color 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetColor
            (
                NXOpen::NXColor * color /** color */ 
            );
            /**Returns  the width 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Thickness Width
            (
            );
            /**Sets  the width 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetWidth
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Thickness width /** width */ 
            );
            /**Returns  the offset position, valid for position offset methods 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point3d OffsetPosition
            (
            );
            /**Sets  the offset position, valid for position offset methods 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : drafting ("DRAFTING") */
            public: void SetOffsetPosition
            (
                const NXOpen::Point3d & point /** point */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
