#ifndef NXOpen_FEATURES_SHEETMETAL_BENDOPTIONS_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_BENDOPTIONS_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_BendOptions.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class BendOptions;
        }
    }
    class Expression;
    namespace Features
    {
        namespace SheetMetal
        {
            class _BendOptionsBuilder;
            class BendOptionsImpl;
            /** Represents a Sheetmetal Bend Options class. 
             <br>  Created in NX4.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  BendOptions : public NXOpen::TaggedObject
            {
                /** This enum represents the bend relief type. */
                public: enum BendReliefTypeOptions
                {
                    BendReliefTypeOptionsNone/**  igRipBendRelief         */,
                    BendReliefTypeOptionsSquare/**  igRectangularBendRelief */,
                    BendReliefTypeOptionsRound/**  igFilletBendRelief      */
                };

                /** This enum represents the corner relief type. */
                public: enum CornerReliefTypeOptions
                {
                    CornerReliefTypeOptionsNone/** none */ ,
                    CornerReliefTypeOptionsBendOnly/**  igBendOnlyCornerRelief */,
                    CornerReliefTypeOptionsBendAndFace/**  igBendAndFaceCornerRelief */,
                    CornerReliefTypeOptionsBendAndFaceChain/**  igChainedCornerRelief */
                };

                private: BendOptionsImpl * m_bendoptions_impl;
                private: friend class  _BendOptionsBuilder;
                protected: BendOptions();
                public: ~BendOptions();
                /**Returns  the bend radius. 
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * BendRadius
                (
                );
                /** Sets the bend radius. 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendRadius Features::SheetMetal::BendOptions::BendRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from Features::SheetMetal::BendOptions::BendRadius instead.") void SetBendRadius
                (
                    const NXString & radius /** radius */ 
                );
                /** Sets the bend radius. 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendRadius Features::SheetMetal::BendOptions::BendRadius@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                void SetBendRadius
                (
                    const char * radius /** radius */ 
                );
                /**Returns  the bend relief type.
                                 <br> 
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink  if you do not want a bend relief.
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsSquare Features::SheetMetal::BendOptions::BendReliefTypeOptionsSquare@endlink  for a square/rectangular bend relief.
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsRound Features::SheetMetal::BendOptions::BendReliefTypeOptionsRound@endlink  for a rounded bend relief.
                                 <br> 
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions BendReliefType
                (
                );
                /**Sets  the bend relief type.
                                 <br> 
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink  if you do not want a bend relief.
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsSquare Features::SheetMetal::BendOptions::BendReliefTypeOptionsSquare@endlink  for a square/rectangular bend relief.
                                    Specify @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsRound Features::SheetMetal::BendOptions::BendReliefTypeOptionsRound@endlink  for a rounded bend relief.
                                 <br> 
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetBendReliefType
                (
                    NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions type /** type */ 
                );
                /**Returns  the option to extend the bend relief if required. This only applies if the bend relief type
                                is set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .    
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ExtendBendRelief
                (
                );
                /**Sets  the option to extend the bend relief if required. This only applies if the bend relief type
                                is set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .    
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetExtendBendRelief
                (
                    bool extend /** extend */ 
                );
                /**Returns  the bend relief depth. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * BendReliefDepth
                (
                );
                /** Sets the bend relief depth. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendReliefDepth Features::SheetMetal::BendOptions::BendReliefDepth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from Features::SheetMetal::BendOptions::BendReliefDepth instead.") void SetBendReliefDepth
                (
                    const NXString & depth /** depth */ 
                );
                /** Sets the bend relief depth. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendReliefDepth Features::SheetMetal::BendOptions::BendReliefDepth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                void SetBendReliefDepth
                (
                    const char * depth /** depth */ 
                );
                /**Returns  the bend relief width. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * BendReliefWidth
                (
                );
                /** Sets the bend relief width. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendReliefWidth Features::SheetMetal::BendOptions::BendReliefWidth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from Features::SheetMetal::BendOptions::BendReliefWidth instead.") void SetBendReliefWidth
                (
                    const NXString & width /** width */ 
                );
                /** Sets the bend relief width. Applicable only if @link NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::BendReliefTypeOptions@endlink  is 
                                set to a value other than @link Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone Features::SheetMetal::BendOptions::BendReliefTypeOptionsNone@endlink .
                              
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::BendReliefWidth Features::SheetMetal::BendOptions::BendReliefWidth@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                void SetBendReliefWidth
                (
                    const char * width /** width */ 
                );
                /**Returns  the corner relief type. Use one of the values from @link NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions@endlink .
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions CornerReliefType
                (
                );
                /**Sets  the corner relief type. Use one of the values from @link NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions@endlink .
                            
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetCornerReliefType
                (
                    NXOpen::Features::SheetMetal::BendOptions::CornerReliefTypeOptions type /** type */ 
                );
                /** Sets the neutral factor. 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::NeutralFactor Features::SheetMetal::BendOptions::NeutralFactor@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NX_DEPRECATED("Deprecated in NX10.0.0.  Use NXOpen::Expression::SetRightHandSide on the NXOpen::Expression object returned from Features::SheetMetal::BendOptions::NeutralFactor instead.") void SetNeutralFactor
                (
                    const NXString & neutralFactor /** neutral factor */ 
                );
                /** Sets the neutral factor. 
                 <br>  @deprecated Deprecated in NX10.0.0.  Use @link NXOpen::Expression::SetRightHandSide NXOpen::Expression::SetRightHandSide@endlink  on the @link NXOpen::Expression NXOpen::Expression@endlink  object returned from @link Features::SheetMetal::BendOptions::NeutralFactor Features::SheetMetal::BendOptions::NeutralFactor@endlink  instead. <br>  

                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                void SetNeutralFactor
                (
                    const char * neutralFactor /** neutral factor */ 
                );
                /**Returns  the neutral factor. 
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * NeutralFactor
                (
                );
                /**Sets  the Use Global Bend Radius toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetUseGlobalBendRadius
                (
                    bool useGlobalBendRadius /** useglobalbendradius */ 
                );
                /**Returns  the Use Global Bend Radius toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool UseGlobalBendRadius
                (
                );
                /**Sets  the Use Global Neutral Factor toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetUseGlobalNeutralFactor
                (
                    bool useGlobalNeutralFactor /** useglobalneutralfactor */ 
                );
                /**Returns  the Use Global Neutral Factor toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool UseGlobalNeutralFactor
                (
                );
                /**Sets  the Use Global Relief Depth toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetUseGlobalReliefDepth
                (
                    bool useGlobalReliefDepth /** useglobalreliefdepth */ 
                );
                /**Returns  the Use Global Relief Depth toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool UseGlobalReliefDepth
                (
                );
                /**Sets  the Use Global Relief Width toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: void SetUseGlobalReliefWidth
                (
                    bool useGlobalReliefWidth /** useglobalreliefwidth */ 
                );
                /**Returns  the Use Global Relief Width toggle. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool UseGlobalReliefWidth
                (
                );
                /**Returns  the override tool set toggle value. 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: bool OverrideToolSet
                (
                );
                /**Sets  the override tool set toggle value. 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                public: void SetOverrideToolSet
                (
                    bool overrideToolSet /** overridetoolset */ 
                );
                /**Returns  the punch tool id selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: int PunchToolId
                (
                );
                /**Sets  the punch tool id selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                public: void SetPunchToolId
                (
                    int punchToolId /** punchtoolid */ 
                );
                /**Returns  the die tool id selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: int DieToolId
                (
                );
                /**Sets  the die tool id selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                public: void SetDieToolId
                (
                    int dieToolId /** dietoolid */ 
                );
                /**Returns  the punch tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString PunchToolIdName
                (
                );
                /**Sets  the punch tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                public: void SetPunchToolIdName
                (
                    const NXString & punchToolId /** punchtoolid */ 
                );
                /**Sets  the punch tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                void SetPunchToolIdName
                (
                    const char * punchToolId /** punchtoolid */ 
                );
                /**Returns  the die tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString DieToolIdName
                (
                );
                /**Sets  the die tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                public: void SetDieToolIdName
                (
                    const NXString & dieToolId /** dietoolid */ 
                );
                /**Sets  the die tool id string selected 
                 <br>  Created in NX12.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR adv_sheet_metal_dsgn ("ADVANCED SHEET METAL DESIGN") */
                void SetDieToolIdName
                (
                    const char * dieToolId /** dietoolid */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
