#ifndef NXOpen_FEATURES_CURVEFINDERBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_CURVEFINDERBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_CurveFinderBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class CurveFinderBuilder;
    }
    namespace GeometricUtilities
    {
        class IComponentBuilder;
    }
    class NXObject;
    class ScCollector;
    class SelectDisplayableObjectList;
    class SelectNXObject;
    class TaggedObject;
    namespace Features
    {
        class _CurveFinderBuilderBuilder;
        class CurveFinderBuilderImpl;
        /** Represents a collection of curves and their relationships to other curves in the model 
         <br>  Created in NX11.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  CurveFinderBuilder : public NXOpen::TaggedObject, public virtual NXOpen::GeometricUtilities::IComponentBuilder
        {
            private: CurveFinderBuilderImpl * m_curvefinderbuilder_impl;
            private: friend class  _CurveFinderBuilderBuilder;
            protected: CurveFinderBuilder();
            public: ~CurveFinderBuilder();
            /**Returns  the curve collector 
             <br>  @deprecated Deprecated in NX10.0.0.  This is for pre NX10 usage, do not use this method. <br>  

             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX10.0.0.  This is for pre NX10 usage, do not use this method.") NXOpen::ScCollector * CurveSection
            (
            );
            /**Returns  the curve and point collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectDisplayableObjectList * CurvePointList
            (
            );
            /** Adds curves to collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SelectCurves
            (
                const std::vector<NXOpen::NXObject *> & curves /** curves */ 
            );
            /** Removes curves from collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void DeselectCurves
            (
                const std::vector<NXOpen::NXObject *> & curves /** curves */ 
            );
            /** Selects entity for symmetry reference 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SelectSymmetryReference
            (
                NXOpen::NXObject * symmetryReference /** symmetryreference */ 
            );
            /** Deselect entity for symmetry reference 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void DeselectSymmetryReference
            (
                NXOpen::NXObject * symmetryReference /** symmetryreference */ 
            );
            /** Adds tangent relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddTangent
            (
            );
            /** Removes tangent relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveTangent
            (
            );
            /** Adds tangent sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddTangentSketchGroup
            (
            );
            /** Removes tangent sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveTangentSketchGroup
            (
            );
            /** Adds tangent 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddTangent2dComponent
            (
            );
            /** Removes tangent 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveTangent2dComponent
            (
            );
            /** Adds parallel relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddParallel
            (
            );
            /** Removes parallel relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveParallel
            (
            );
            /** Adds parallel sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddParallelSketchGroup
            (
            );
            /** Removes parallel sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveParallelSketchGroup
            (
            );
            /** Adds parallel 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddParallel2dComponent
            (
            );
            /** Removes parallel 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveParallel2dComponent
            (
            );
            /** Adds offset relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddOffset
            (
            );
            /** Removes offset relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveOffset
            (
            );
            /** Adds offset sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddOffsetSketchGroup
            (
            );
            /** Removes offset sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveOffsetSketchGroup
            (
            );
            /** Adds offset 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddOffset2dComponent
            (
            );
            /** Removes offset 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveOffset2dComponent
            (
            );
            /** Adds coincident vertex relations of the last vertexes added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddCoincident
            (
            );
            /** Removes coincident vertex relations of the last vertexes added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveCoincident
            (
            );
            /** Adds coincident sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddCoincidentSketchGroup
            (
            );
            /** Removes coincident sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveCoincidentSketchGroup
            (
            );
            /** Adds coincident 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddCoincident2dComponent
            (
            );
            /** Removes coincident 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveCoincident2dComponent
            (
            );
            /** Adds vertex on curve relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddVertexOnCurve
            (
            );
            /** Removes vertex on curve relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveVertexOnCurve
            (
            );
            /** Adds vertex on curve sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddVertexOnCurveSketchGroup
            (
            );
            /** Removes vertex on curve sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveVertexOnCurveSketchGroup
            (
            );
            /** Adds vertex on curve 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddVertexOnCurve2dComponent
            (
            );
            /** Removes vertex on curve 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveVertexOnCurve2dComponent
            (
            );
            /** Adds chamfer relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddChamfer
            (
            );
            /** Removes chamfer relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveChamfer
            (
            );
            /** Adds conlinear relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConlinear
            (
            );
            /** Removes conlinear relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConlinear
            (
            );
            /** Adds conlinear sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConlinearSketchGroup
            (
            );
            /** Removes conlinear sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConlinearSketchGroup
            (
            );
            /** Adds conlinear 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConlinear2dComponent
            (
            );
            /** Removes conlinear 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConlinear2dComponent
            (
            );
            /** Adds concentric relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConcentric
            (
            );
            /** Removes concentric relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConcentric
            (
            );
            /** Adds concentric sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConcentricSketchGroup
            (
            );
            /** Removes concentric sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConcentricSketchGroup
            (
            );
            /** Adds concentric 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddConcentric2dComponent
            (
            );
            /** Removes concentric 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveConcentric2dComponent
            (
            );
            /** Adds equal radius relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddEqualRadius
            (
            );
            /** Removes equal radius relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveEqualRadius
            (
            );
            /** Adds equal radius sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddEqualRadiusSketchGroup
            (
            );
            /** Removes equal radius sketch group relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveEqualRadiusSketchGroup
            (
            );
            /** Adds equal radius 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddEqualRadius2dComponent
            (
            );
            /** Removes equal radius 2d component relations of the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveEqualRadius2dComponent
            (
            );
            /** Add symmetric relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void AddSymmetric
            (
                int planeType /** planetype */ 
            );
            /** Removes symmetric relations of the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveSymmetric
            (
                int planeType /** planetype */ 
            );
            /**Returns  a value that indicates which symmetric option is 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: int SymmetryOption
            (
            );
            /**Sets  a value that indicates which symmetric option is 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetSymmetryOption
            (
                int symmetryOption /** symmetryoption */ 
            );
            /**Returns  the symmetry line reference 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectNXObject * SymmetryReference
            (
            );
            /**Returns  a value that indicates whether relation recognition is enabled 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool UseCurveFinder
            (
            );
            /**Sets  a value that indicates whether relation recognition is enabled 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetUseCurveFinder
            (
                bool curveBrowseEnabled /** curvebrowseenabled */ 
            );
            /** Finds relation curves 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void FindRelationCurve
            (
                const std::vector<NXOpen::NXObject *> & selectedCurves /** selectedcurves */ 
            );
            /**Returns  a value that indicates whether add tangent relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool TangentEnabled
            (
            );
            /**Returns  a value that indicates whether add tangent relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool TangentSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add tangent 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool Tangent2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add tangent relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetTangentEnabled
            (
                bool tangentEnabled /** tangentenabled */ 
            );
            /**Sets  a value that indicates whether add tangent relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetTangentSketchGroupEnabled
            (
                bool tangentSketchGroupEnabled /** tangentsketchgroupenabled */ 
            );
            /**Sets  a value that indicates whether add tangent 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetTangent2dComponentEnabled
            (
                bool tangent2dComponentEnabled /** tangent2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add concentric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ConcentricEnabled
            (
            );
            /**Returns  a value that indicates whether add concentric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ConcentricSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add concentric 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool Concentric2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add concentric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetConcentricEnabled
            (
                bool concentricEnabled /** concentricenabled */ 
            );
            /**Sets  a value that indicates whether add concentric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetConcentricSketchGroupEnabled
            (
                bool concentricEnabled /** concentricenabled */ 
            );
            /**Sets  a value that indicates whether add concentric 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetConcentric2dComponentEnabled
            (
                bool concentricComponentGeometryEnabled /** concentriccomponentgeometryenabled */ 
            );
            /**Returns  a value that indicates whether add collinear relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool CollinearEnabled
            (
            );
            /**Returns  a value that indicates whether add collinear relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool CollinearSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add collinear 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool Collinear2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add collinear relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCollinearEnabled
            (
                bool collinearEnabled /** collinearenabled */ 
            );
            /**Sets  a value that indicates whether add collinear relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCollinearSketchGroupEnabled
            (
                bool collinearEnabled /** collinearenabled */ 
            );
            /**Sets  a value that indicates whether add collinear 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCollinear2dComponentEnabled
            (
                bool collinear2dComponentEnabled /** collinear2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add equal radius recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool EqualRadiusEnabled
            (
            );
            /**Returns  a value that indicates whether add equal radius recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool EqualRadiusSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add equal radius 2d component recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool EqualRadius2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add equal radius recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetEqualRadiusEnabled
            (
                bool equalRadiusEnabled /** equalradiusenabled */ 
            );
            /**Sets  a value that indicates whether add equal radius recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetEqualRadiusSketchGroupEnabled
            (
                bool equalRadiusEnabled /** equalradiusenabled */ 
            );
            /**Sets  a value that indicates whether add equal radius 2d component recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetEqualRadius2dComponentEnabled
            (
                bool equalRadius2dComponentEnabled /** equalradius2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add symmetric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool SymmetricEnabled
            (
            );
            /**Sets  a value that indicates whether add symmetric relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetSymmetricEnabled
            (
                bool symmetricEnabled /** symmetricenabled */ 
            );
            /**Returns  a value that indicates whether add parallel relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ParallelEnabled
            (
            );
            /**Returns  a value that indicates whether add parallel relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ParallelSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add parallel 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool Parallel2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add parallel relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetParallelEnabled
            (
                bool parallelEnabled /** parallelenabled */ 
            );
            /**Sets  a value that indicates whether add parallel relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetParallelSketchGroupEnabled
            (
                bool parallelEnabled /** parallelenabled */ 
            );
            /**Sets  a value that indicates whether add parallel 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetParallel2dComponentEnabled
            (
                bool parallel2dComponentEnabled /** parallel2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add offset relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool OffsetEnabled
            (
            );
            /**Returns  a value that indicates whether add offset relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool OffsetSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add offset 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool Offset2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add offset relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetOffsetEnabled
            (
                bool offsetEnabled /** offsetenabled */ 
            );
            /**Sets  a value that indicates whether add offset relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetOffsetSketchGroupEnabled
            (
                bool offsetEnabled /** offsetenabled */ 
            );
            /**Sets  a value that indicates whether add offset 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetOffset2dComponentEnabled
            (
                bool offset2dComponentEnabled /** offset2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add coincident vertex relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool CoincidentVertexEnabled
            (
            );
            /**Returns  a value that indicates whether add coincident vertex relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool CoincidentVertexSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add coincident vertex 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool CoincidentVertex2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add coincident vertex relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCoincidentVertexEnabled
            (
                bool coincidentVertexEnabled /** coincidentvertexenabled */ 
            );
            /**Sets  a value that indicates whether add coincident vertex relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCoincidentVertexSketchGroupEnabled
            (
                bool coincidentVertexEnabled /** coincidentvertexenabled */ 
            );
            /**Sets  a value that indicates whether add coincident vertex 2d component relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCoincidentVertex2dComponentEnabled
            (
                bool coincidentVertex2dComponentEnabled /** coincidentvertex2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add vertex on curve relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool VertexOnCurveEnabled
            (
            );
            /**Returns  a value that indicates whether add vertex on curve relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool VertexOnCurveSketchGroupEnabled
            (
            );
            /**Returns  a value that indicates whether add vertex on curve 2d component relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: bool VertexOnCurve2dComponentEnabled
            (
            );
            /**Sets  a value that indicates whether add vertex on curve relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetVertexOnCurveEnabled
            (
                bool vertexOnCurveEnabled /** vertexoncurveenabled */ 
            );
            /**Sets  a value that indicates whether add vertex on curve relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetVertexOnCurveSketchGroupEnabled
            (
                bool vertexOnCurveEnabled /** vertexoncurveenabled */ 
            );
            /**Sets  a value that indicates whether add vertex on curve 2d component relation recognition for the last vertexes added to the collector 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetVertexOnCurve2dComponentEnabled
            (
                bool vertexOnCurve2dComponentEnabled /** vertexoncurve2dcomponentenabled */ 
            );
            /**Returns  a value that indicates whether add chamfer relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ChamferEnabled
            (
            );
            /**Sets  a value that indicates whether add chamfer relation recognition for the last curves added to curve collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetChamferEnabled
            (
                bool chamferEnabled /** chamferenabled */ 
            );
            /**Returns  a value that indicates which find scope option is 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: int FindScopeOption
            (
            );
            /**Sets  a value that indicates which find scope option is 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetFindScopeOption
            (
                int scopeOption /** scopeoption */ 
            );
            /** Finds relation curves in the scope 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void FindScopeCurve
            (
                const std::vector<NXOpen::NXObject *> & selectedCurves /** selectedcurves */ 
            );
            /** Close the VTK interaction and Remove all nodes from the Engine 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveEngineNodes
            (
            );
            /** ReStore all nodes from the Engine On Undo 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RestoreEngineNodes
            (
            );
            /**Returns  a value that indicates what kind of relations are needed to recognize 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: int RelationScope
            (
            );
            /**Sets  a value that indicates what kind of relations are needed to recognize 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetRelationScope
            (
                int relationScope /** relationscope */ 
            );
            /**Returns  a value that indicates what kind of sketch group relations are needed to recognize 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: int SketchGroupRelationScope
            (
            );
            /**Sets  a value that indicates what kind of sketch group relations are needed to recognize 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetSketchGroupRelationScope
            (
                int relationScope /** relationscope */ 
            );
            /**Returns  a value that indicates what kind of 2d component relations are needed to recognize 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : None */
            public: int CompoundGeometryRelationScope
            (
            );
            /**Sets  a value that indicates what kind of 2d component relations are needed to recognize 
             <br>  Created in NX11.0.1.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetCompoundGeometryRelationScope
            (
                int relationScope /** relationscope */ 
            );
            /** Set the distance Tolerance for loop Recognization 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SetDistanceTolerance
            (
                double distanceTolerance /** distancetolerance */ 
            );
            /** Remove all the included constraint 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RemoveIncludedConstraints
            (
            );
            /** Recognize rigid from the recognized relation 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void RecognizeRigid
            (
                NXOpen::NXObject * constraintTag /** constrainttag */ 
            );
            /** Unrecognize rigid from the unrecognized relation 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void UnrecognizeRigid
            (
                NXOpen::NXObject * constraintTag /** constrainttag */ 
            );
            /** Adds snap point to collector 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void SelectSnapPoint
            (
                NXOpen::TaggedObject * selectedCurve /** selected curve*/,
                const NXOpen::Point3d & point /** selected point*/
            );
            /** Removes snap point from collector 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR geometric_tol ("GDT") */
            public: void DeselectSnapPoint
            (
                NXOpen::TaggedObject * selectedCurve /** selected curve*/,
                const NXOpen::Point3d & point /** selected point*/
            );
            /** Validate whether the inputs to the component are sufficient for 
                        commit to be called.  If the component is not in a state to commit
                        then an exception is thrown.  For example, if the component requires
                        you to set some property, this method will throw an exception if
                        you haven't set it.  This method throws a not-yet-implemented
                        NXException for some components.
                     @return  Was self validation successful 
             <br>  Created in NX3.0.1.  <br>  
             <br> License requirements : None */
            public: virtual bool Validate
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
