#ifndef NXOpen_MOTION_ANALYTICALCONTACTBUILDER_HXX_INCLUDED
#define NXOpen_MOTION_ANALYTICALCONTACTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Motion_AnalyticalContactBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Motion_MotionBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_motion_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Motion
    {
        class AnalyticalContactBuilder;
    }
    class Direction;
    class Expression;
    namespace Motion
    {
        class MotionBuilder;
    }
    namespace Motion
    {
        class MotionFunction;
    }
    namespace Motion
    {
        class SelectAnalyticalContactProperty;
    }
    namespace Motion
    {
        class SelectLink;
    }
    class Point;
    class Section;
    class SelectNXObjectList;
    namespace Motion
    {
        class _AnalyticalContactBuilderBuilder;
        class AnalyticalContactBuilderImpl;
        /** Represents a @link Motion::AnalyticalContact Motion::AnalyticalContact@endlink  builder  <br> To create a new instance of this class, use @link NXOpen::Motion::AnalyticalContactCollection::CreateAnalyticalContactBuilder  NXOpen::Motion::AnalyticalContactCollection::CreateAnalyticalContactBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        ContactType </td> <td> 
         
        SphereToSphere </td> </tr> 

        <tr><td> 
         
        EffectiveContactDepth.Value </td> <td> 
         
        1000 (millimeters part), 39.3701 (inches part) </td> </tr> 

        <tr><td> 
         
        ExtrusionGeometryData </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        ExtrusionMaterialSide </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        FindAllRoots </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        FirstSuperElementIncrement </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        InfiniteExtrusion </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        InfiniteSweep </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MaxTesselationLength.Value </td> <td> 
         
        5 (millimeters part), 0.19685 (inches part) </td> </tr> 

        <tr><td> 
         
        Profile </td> <td> 
         
        None </td> </tr> 

        <tr><td> 
         
        RadiusOfExclusion.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        RailGeometryData </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        RailMaterialSide </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        RevolutionGeometryData </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        RevolutionMaterialSide </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SecondRevolutionGeometryData </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        SecondRevolutionMaterialSide </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SecondSphereRadius.Value </td> <td> 
         
        1000 (millimeters part), 39.3701 (inches part) </td> </tr> 

        <tr><td> 
         
        SecondSuperElementIncrement </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SphereRadius.Value </td> <td> 
         
        1000 (millimeters part), 39.3701 (inches part) </td> </tr> 

        <tr><td> 
         
        SuperElementReportInstance </td> <td> 
         
        1 </td> </tr> 

        </table>  

         <br>  Created in NX12.0.0.  <br>  
        */
        class NXOPENCPP_MOTIONEXPORT  AnalyticalContactBuilder : public NXOpen::Motion::MotionBuilder
        {
            /** Contact type */
            public: enum ContactTypeOption
            {
                ContactTypeOptionSphereToSphere/** sphere to sphere */ ,
                ContactTypeOptionSphereToExtrusion/** sphere to extrusion */ ,
                ContactTypeOptionSphereToRevolution/** sphere to revolution */ ,
                ContactTypeOptionExtrusionToRevolution/** extrusion to revolution */ ,
                ContactTypeOptionRevolutionToRevolution/** revolution to revolution */ ,
                ContactTypeOptionSphereToRail/** sphere to rail */ 
            };

            /** Profile Type */
            public: enum ProfileType
            {
                ProfileTypeNone/** none */ ,
                ProfileTypeCircular/** circular */ ,
                ProfileTypeRoad/** road */ 
            };

            private: AnalyticalContactBuilderImpl * m_analyticalcontactbuilder_impl;
            private: friend class  _AnalyticalContactBuilderBuilder;
            protected: AnalyticalContactBuilder();
            public: ~AnalyticalContactBuilder();
            /**Returns  the type 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::AnalyticalContactBuilder::ContactTypeOption ContactType
            (
            );
            /**Sets  the type 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetContactType
            (
                NXOpen::Motion::AnalyticalContactBuilder::ContactTypeOption type /** type */ 
            );
            /**Returns  the sphere link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * SphereLink
            (
            );
            /**Returns  the sphere point 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Point * SpherePoint
            (
            );
            /**Sets  the sphere point 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSpherePoint
            (
                NXOpen::Point * spherePoint /** spherepoint */ 
            );
            /**Returns  the second sphere link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * SecondSphereLink
            (
            );
            /**Returns  the second sphere point 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Point * SecondSpherePoint
            (
            );
            /**Sets  the second sphere point 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondSpherePoint
            (
                NXOpen::Point * secondSpherePoint /** secondspherepoint */ 
            );
            /**Returns  the extrusion link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * ExtrusionLink
            (
            );
            /**Returns  the extrusion bodies 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::SelectNXObjectList * ExtrusionBodies
            (
            );
            /**Returns  the extrusion line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool ExtrusionGeometryData
            (
            );
            /**Sets  the extrusion line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetExtrusionGeometryData
            (
                bool geometryDataOption /** geometrydataoption */ 
            );
            /**Returns  the extrusion line-arc file.
                        This is a file containing information describing the extrusion profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXString ExtrusionGeometryDataFile
            (
            );
            /**Sets  the extrusion line-arc file.
                        This is a file containing information describing the extrusion profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetExtrusionGeometryDataFile
            (
                const NXString & fileName /** filename */ 
            );
            /**Sets  the extrusion line-arc file.
                        This is a file containing information describing the extrusion profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetExtrusionGeometryDataFile
            (
                const char * fileName /** filename */ 
            );
            /**Returns  the revolution link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * RevolutionLink
            (
            );
            /**Returns  the revolution bodies 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::SelectNXObjectList * RevolutionBodies
            (
            );
            /**Returns  the revolution line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool RevolutionGeometryData
            (
            );
            /**Sets  the revolution line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRevolutionGeometryData
            (
                bool geometryDataOption /** geometrydataoption */ 
            );
            /**Returns  the revolution line-arc file.
                        This is a file containing information describing the revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXString RevolutionGeometryDataFile
            (
            );
            /**Sets  the revolution line-arc file.
                        This is a file containing information describing the revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRevolutionGeometryDataFile
            (
                const NXString & fileName /** filename */ 
            );
            /**Sets  the revolution line-arc file.
                        This is a file containing information describing the revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetRevolutionGeometryDataFile
            (
                const char * fileName /** filename */ 
            );
            /**Returns  the second revolution link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * SecondRevolutionLink
            (
            );
            /**Returns  the second revolution bodies 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::SelectNXObjectList * SecondRevolutionBodies
            (
            );
            /**Returns  the second revolution line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool SecondRevolutionGeometryData
            (
            );
            /**Sets  the second revolution line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondRevolutionGeometryData
            (
                bool geometryDataOption /** geometrydataoption */ 
            );
            /**Returns  the second revolution line-arc file.
                        This is a file containing information describing the second revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXString SecondRevolutionGeometryDataFile
            (
            );
            /**Sets  the second revolution line-arc file.
                        This is a file containing information describing the second revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondRevolutionGeometryDataFile
            (
                const NXString & fileName /** filename */ 
            );
            /**Sets  the second revolution line-arc file.
                        This is a file containing information describing the second revolution profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetSecondRevolutionGeometryDataFile
            (
                const char * fileName /** filename */ 
            );
            /**Returns  the rail link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * RailLink
            (
            );
            /**Returns  the rail bodies 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::SelectNXObjectList * RailBodies
            (
            );
            /**Returns  the rail curve 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Section * RailCurve
            (
            );
            /**Returns  the rail line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool RailGeometryData
            (
            );
            /**Sets  the rail line-arc file option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailGeometryData
            (
                bool geometryDataOption /** geometrydataoption */ 
            );
            /**Returns  the rail line-arc file.
                        This is a file containing information describing the rail profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXString RailGeometryDataFile
            (
            );
            /**Sets  the rail line-arc file.
                        This is a file containing information describing the rail profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailGeometryDataFile
            (
                const NXString & fileName /** filename */ 
            );
            /**Sets  the rail line-arc file.
                        This is a file containing information describing the rail profile.
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetRailGeometryDataFile
            (
                const char * fileName /** filename */ 
            );
            /**Returns  the sphere radius 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * SphereRadius
            (
            );
            /**Returns  the partial sphere option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool PartialSphereOption
            (
            );
            /**Sets  the partial sphere option
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetPartialSphereOption
            (
                bool partialSphereOption /** partialsphereoption */ 
            );
            /**Returns  the partial sphere vector
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Direction * PartialSphereVector
            (
            );
            /**Sets  the partial sphere vector
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetPartialSphereVector
            (
                NXOpen::Direction * partialSphereVector /** partialspherevector */ 
            );
            /**Returns  the partial sphere angle
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * PartialSphereAngle
            (
            );
            /**Returns  the second sphere radius 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * SecondSphereRadius
            (
            );
            /**Returns  the max penetration depth 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * EffectiveContactDepth
            (
            );
            /**Returns  the radius of exclusion 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * RadiusOfExclusion
            (
            );
            /**Returns  the infinite extrusion 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool InfiniteExtrusion
            (
            );
            /**Sets  the infinite extrusion 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetInfiniteExtrusion
            (
                bool infiniteExtrusion /** infiniteextrusion */ 
            );
            /**Returns  the infinite sweep for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool InfiniteSweep
            (
            );
            /**Sets  the infinite sweep for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetInfiniteSweep
            (
                bool infiniteSweep /** infinitesweep */ 
            );
            /**Returns  the spline function toggle for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool RailSplineFunctions
            (
            );
            /**Sets  the spline function toggle for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailSplineFunctions
            (
                bool functionsToggle /** functionstoggle */ 
            );
            /**Returns  the RailX function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::MotionFunction * RailXCurve
            (
            );
            /**Sets  the RailX function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailXCurve
            (
                NXOpen::Motion::MotionFunction * railCurve /** railcurve */ 
            );
            /**Returns  the RailY function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::MotionFunction * RailYCurve
            (
            );
            /**Sets  the RailY function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailYCurve
            (
                NXOpen::Motion::MotionFunction * railCurve /** railcurve */ 
            );
            /**Returns  the RailZ function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::MotionFunction * RailZCurve
            (
            );
            /**Sets  the RailZ function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailZCurve
            (
                NXOpen::Motion::MotionFunction * railCurve /** railcurve */ 
            );
            /**Returns  the RailRollAngle function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::MotionFunction * RailRollAngleCurve
            (
            );
            /**Sets  the RailRollAngle function 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailRollAngleCurve
            (
                NXOpen::Motion::MotionFunction * railCurve /** railcurve */ 
            );
            /**Returns  the max tesselation length 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Expression * MaxTesselationLength
            (
            );
            /**Returns  the profile 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::AnalyticalContactBuilder::ProfileType Profile
            (
            );
            /**Sets  the profile 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetProfile
            (
                NXOpen::Motion::AnalyticalContactBuilder::ProfileType profileType /** profiletype */ 
            );
            /**Returns  the find all roots 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool FindAllRoots
            (
            );
            /**Sets  the find all roots 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetFindAllRoots
            (
                bool findAllRoots /** findallroots */ 
            );
            /**Returns  the contact property 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectAnalyticalContactProperty * ContactProperty
            (
            );
            /**Returns  the first super element link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * FirstSuperElementLink
            (
            );
            /**Returns  the first super element increment 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: int FirstSuperElementIncrement
            (
            );
            /**Sets  the first super element increment 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetFirstSuperElementIncrement
            (
                int firstSuperElementIncrement /** firstsuperelementincrement */ 
            );
            /**Returns  the second super element link 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXOpen::Motion::SelectLink * SecondSuperElementLink
            (
            );
            /**Returns  the second super element increment 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: int SecondSuperElementIncrement
            (
            );
            /**Sets  the second super element increment 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondSuperElementIncrement
            (
                int sSecondSuperElementIncrement /** ssecondsuperelementincrement */ 
            );
            /**Returns  the super element report instance 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: int SuperElementReportInstance
            (
            );
            /**Sets  the super element report instance 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSuperElementReportInstance
            (
                int superElementReportInstance /** superelementreportinstance */ 
            );
            /**Returns  the string name 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: NXString Name
            (
            );
            /**Sets  the string name 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetName
            (
                const NXString & name /** name */ 
            );
            /**Sets  the string name 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            void SetName
            (
                const char * name /** name */ 
            );
            /**Returns  the material side toggle for extrusion 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool ExtrusionMaterialSide
            (
            );
            /**Sets  the material side toggle for extrusion 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetExtrusionMaterialSide
            (
                bool matSide /** matside */ 
            );
            /**Returns  the material side toggle for revolution 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool RevolutionMaterialSide
            (
            );
            /**Sets  the material side toggle for revolution 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRevolutionMaterialSide
            (
                bool matSide /** matside */ 
            );
            /**Returns  the material side toggle for second revolution 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool SecondRevolutionMaterialSide
            (
            );
            /**Sets  the material side toggle for second revolution 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetSecondRevolutionMaterialSide
            (
                bool matSide /** matside */ 
            );
            /**Returns  the material side toggle for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: bool RailMaterialSide
            (
            );
            /**Sets  the material side toggle for rail 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : mechanisms ("MECHANISMS") */
            public: void SetRailMaterialSide
            (
                bool matSide /** matside */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
