#ifndef NXOpen_ARC_HXX_INCLUDED
#define NXOpen_ARC_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Arc.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Conic.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    class Arc;
    class Conic;
    class NXMatrix;
    class _ArcBuilder;
    class ArcImpl;
    /** Represents an arc curve.  The start and end angles of the arc are
        measured relative to the X and Y axes of the orientation matrix.  <br> To create a new instance of this class, use @link CurveCollection::CreateArc CurveCollection::CreateArc@endlink  <br> */
    class NXOPENCPPEXPORT  Arc : public Conic
    {
        private: ArcImpl * m_arc_impl;
        private: friend class  _ArcBuilder;
        protected: Arc();
        public: ~Arc();
        /**Returns  the radius of the arc.  <br> License requirements : None */
        public: double Radius
        (
        );
        /**Returns  the start angle of the arc.  <br> License requirements : None */
        public: double StartAngle
        (
        );
        /**Returns  the angle of the arc.  <br> License requirements : None */
        public: double EndAngle
        (
        );
        /** Sets the radius of the arc.  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetRadius
        (
            double radius /** radius */ 
        );
        /** Sets the center, radius, start and end angles, and orientation
                matrix of the arc.  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetParameters
        (
            double radius /** The radius must be greater than zero. */,
            const NXOpen::Point3d & center /** center */ ,
            double startAngle /** In radians */,
            double endAngle /** In radians.  The end angle must not equal the start angle. */,
            NXOpen::NXMatrix * matrix /** Orientation matrix */
        );
        /** Sets the center, radius, and start and end angles of the arc.  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetParameters
        (
            double radius /** Must be greater than zero */,
            const NXOpen::Point3d & center /** center */ ,
            double startAngle /** In radians */,
            double endAngle /** In radians.  The end angle must not equal the start angle */
        );
    };
}
#undef EXPORTLIBRARY
#endif
