#ifndef NXOpen_FEATURES_SKETCHONPATHBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SKETCHONPATHBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SketchOnPathBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/type.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class SketchOnPathBuilder;
    }
    class DatumAxis;
    class DatumPlane;
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    class IReferenceAxis;
    class Point;
    class Section;
    namespace Features
    {
        class _SketchOnPathBuilderBuilder;
        class SketchOnPathBuilderImpl;
        /** Represents a sketch on path feature builder. 
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateSketchOnPathBuilder Features::FeatureCollection::CreateSketchOnPathBuilder@endlink  <br> 
         @deprecated Deprecated in NX5.0.0 <br> 
        */
        class NXOPENCPPEXPORT  NX_DEPRECATED("Deprecated in NX5.0.0")  SketchOnPathBuilder : public Features::FeatureBuilder
        {
            /** Specifies the type of orientation for the sketch plane */
            public: enum OrientationType
            {
                OrientationTypeNormalToPath/** Sketch plane will be normal to the path */,
                OrientationTypeNormalToAxis/** Sketch plane will be normal to specified axis */,
                OrientationTypeParallelToAxis/** Sketch plane will be parallel to specified axis */,
                OrientationTypeThroughAxis/** Sketch plane will pass through specified axis */
            };

            private: SketchOnPathBuilderImpl * m_sketchonpathbuilder_impl;
            private: friend class  _SketchOnPathBuilderBuilder;
            protected: SketchOnPathBuilder();
            public: ~SketchOnPathBuilder();
            /**Sets  the path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetPath
            (
                NXOpen::Section * section /** section */ 
            );
            /**Returns  the path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Section * Path
            (
            );
            /**Sets  the axis for orientation types other than @link NXOpen::Features::SketchOnPathBuilder::OrientationTypeNormalToPath NXOpen::Features::SketchOnPathBuilder::OrientationTypeNormalToPath@endlink 
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetAxis
            (
                NXOpen::Direction * axis /** axis */ 
            );
            /**Returns  the axis for orientation types other than @link NXOpen::Features::SketchOnPathBuilder::OrientationTypeNormalToPath NXOpen::Features::SketchOnPathBuilder::OrientationTypeNormalToPath@endlink 
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Direction * Axis
            (
            );
            /**Sets  the orientation type of the sketch plane that describes how to interpret the axis
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetPlaneOrientation
            (
                NXOpen::Features::SketchOnPathBuilder::OrientationType type /** Indicates orientation type */
            );
            /**Returns  the orientation type of the sketch plane that describes how to interpret the axis
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Features::SketchOnPathBuilder::OrientationType PlaneOrientation
            (
            );
            /**Sets  the thru point, an optional parameter that can be used with any orientation type, NULL if not defined
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetThruPoint
            (
                NXOpen::Point * thruPoint /** thru point */ 
            );
            /**Returns  the thru point, an optional parameter that can be used with any orientation type, NULL if not defined
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Point * ThruPoint
            (
            );
            /** Sets the location on the path in either arc length or percent arc length
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetValue
            (
                const NXString & valueExpression /** The arc length or percent arc length along the path   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /**Returns  the location on the path in either arc length or percent arc length
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Expression * Value
            (
            );
            /**Sets  the type of value, either arc length or percent arc length
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetValueType
            (
                NXOpen::CurveParameterType valueType /** Indicates whether the value is arc length or percent arc length */
            );
            /**Returns  the type of value, either arc length or percent arc length
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::CurveParameterType ValueType
            (
            );
            /** Sets the name of the sketch on path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetSketchOnPathName
            (
                const NXString & name /** The name of the sketch on path   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Flip the sketch plane normal
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void FlipPlaneNormal
            (
            );
            /** Flip the sketch reference direction (X-axis)
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void FlipHorizontalReference
            (
            );
            /**Returns  the sketch on path plane tag
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::DatumPlane * Plane
            (
            );
            /** The horizontal reference direction vector. Needed if horizontal reference is explicitly set to NULL
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetReferenceDirection
            (
                const NXOpen::Vector3d & vector /** The direction of horizontal reference */
            );
            /**Returns  the primary tangent axis of sketch on path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::DatumAxis * PrimaryTangentAxis
            (
            );
            /**Returns  the primary normal axis of sketch on path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::DatumAxis * PrimaryNormalAxis
            (
            );
            /**Returns  the secondary tangent axis of sketch on path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::DatumAxis * SecondaryTangentAxis
            (
            );
            /**Returns  the secondary normal axis of sketch on path
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::DatumAxis * SecondaryNormalAxis
            (
            );
            /** The sketch horizontal reference (X-axis)
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetHorizontalReference
            (
                NXOpen::IReferenceAxis * horizontalReference /** The sketch horizontal reference (X-axis) */
            );
            /**Returns  the sketch horizontal reference (X-axis)
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::IReferenceAxis * HorizontalReference
            (
            );
            /**Returns  the point on path - the principle intersection point between the sketch plane and the path. Corresponds to the origin
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Point * PointOnPath
            (
            );
            /**Returns  the number of possible valid plane configurations if the thru point is set
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") int ValueCount
            (
            );
            /**Sets  the index to the desired solution value in the range [1,value_count], applicable only when the thru point is set
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void SetValueIndex
            (
                int indexOfSolution /** index to the possible solution, valid only when @link Features::SketchOnPathBuilder::ValueCount Features::SketchOnPathBuilder::ValueCount@endlink  \> 0 and must be between [1,@link Features::SketchOnPathBuilder::ValueCount Features::SketchOnPathBuilder::ValueCount@endlink ] */
            );
            /**Returns  the index to the desired solution value in the range [1,value_count], applicable only when the thru point is set
                
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") int ValueIndex
            (
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
