#ifndef NXOpen_FEATURES_EDGEBLENDBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_EDGEBLENDBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_EdgeBlendBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/GeometricUtilities_BlendLimitsData.hxx>
#include <NXOpen/GeometricUtilities_BlendStopshortBuilder.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class EdgeBlendBuilder;
    }
    class Edge;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class BlendLimitsData;
    }
    namespace GeometricUtilities
    {
        class BlendStopshortBuilder;
    }
    class Point;
    class ScCollector;
    namespace Features
    {
        class _EdgeBlendBuilderBuilder;
        class EdgeBlendBuilderImpl;
        /** Represents a Edge Blend builder.
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateEdgeBlendBuilder Features::FeatureCollection::CreateEdgeBlendBuilder@endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        TrimmingOption </td> <td> 
         
        False </td> </tr> 

        </table>  
        */
        class NXOPENCPPEXPORT  EdgeBlendBuilder : public Features::FeatureBuilder
        {
            /** This enum represents the Overlap resolution options for Edge Blend */
            public: enum Overlap
            {
                OverlapMaintainAndIntersect/** Maintain Blend and Intersect */,
                OverlapDifferentConvexityRollOver/** If different convexity,roll over */,
                OverlapAnyConvexityRollOver/** Any convexity,roll over */
            };

            /** This enum represents the order of Blending */
            public: enum OrderOfBlending
            {
                OrderOfBlendingConvexFirst/** Convex first */,
                OrderOfBlendingConcaveFirst/** Concave first */
            };

            /** This enum represents the Setback option  */
            public: enum Setback
            {
                SetbackIncludeWithCorner/** Include with corner*/,
                SetbackSeparateFromCorner/** Separate from corner */
            };

            private: EdgeBlendBuilderImpl * m_edgeblendbuilder_impl;
            private: friend class  _EdgeBlendBuilderBuilder;
            protected: EdgeBlendBuilder();
            public: ~EdgeBlendBuilder();
            /**Returns  the tolerance of a variable blend
                 <br> License requirements : None */
            public: double Tolerance
            (
            );
            /**Sets  the tolerance of a variable blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTolerance
            (
                double tolerance /** tolerance */ 
            );
            /**Returns  the blend all instances option
                 <br> License requirements : None */
            public: bool AllInstancesOption
            (
            );
            /**Sets  the blend all instances option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAllInstancesOption
            (
                bool optionValue /** option value */ 
            );
            /**Returns  the Remove self-intersection option
                 <br> License requirements : None */
            public: bool RemoveSelfIntersection
            (
            );
            /**Sets  the Remove self-intersection option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRemoveSelfIntersection
            (
                bool optionValue /** option value */ 
            );
            /**Returns  the Roll over smooth edges option
                 <br> License requirements : None */
            public: bool RollOverSmoothEdge
            (
            );
            /**Sets  the Roll over smooth edges option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRollOverSmoothEdge
            (
                bool optionValue /** option value */ 
            );
            /**Returns  the Roll onto edges option
                 <br> License requirements : None */
            public: bool RollOntoEdge
            (
            );
            /**Sets  the Roll onto edges option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRollOntoEdge
            (
                bool optionValue /** option value */ 
            );
            /**Returns  the Maintain blend and move sharp edges option
                 <br> License requirements : None */
            public: bool MoveSharpEdge
            (
            );
            /**Sets  the Maintain blend and move sharp edges option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetMoveSharpEdge
            (
                bool optionValue /** option value */ 
            );
            /**Returns  the Special blend at convex / concave Y option
                 <br> License requirements : None */
            public: bool ConvexConcaveY
            (
            );
            /**Sets  the Special blend at convex / concave Y option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetConvexConcaveY
            (
                bool optionValue /** option value */ 
            );
            /** Add an edge blend chainset to the edge blend  @return  Index of chainset, indicating which chainset we are dealing with  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: int AddChainset
            (
                NXOpen::ScCollector * collector /**The collector for this edge blend chainset */,
                const NXString & radius /** The radius of this chain set collector  <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Get the index of edge blend chainset given the collector @return  Index of chainset, indicating which chainset we are dealing with  <br> License requirements : None */
            public: int GetChainsetIndex
            (
                NXOpen::ScCollector * collector /**The collector for this edge blend chainset */
            );
            /** Get the number of valid chainsets @return  Number of valid chainsets  <br> License requirements : None */
            public: int GetNumberOfValidChainsets
            (
            );
            /** Get collector and radius for an edge blend chainset given the index of the chainset  <br> License requirements : None */
            public: void GetChainset
            (
                int csIndex /** Index of chainset, indicating which chainset we are dealing with */,
                NXOpen::ScCollector ** collector /**The collector for this edge blend chainset */,
                NXOpen::Expression ** radius /**  The radius of this chain set collector */
            );
            /** Get collector, radius and validity status for an edge blend chainset given the index of the chainset  <br> License requirements : None */
            public: void GetChainsetAndStatus
            (
                int csIndex /** Index of chainset */,
                NXOpen::ScCollector ** collector /** The collector for this edge blend chainset */,
                NXOpen::Expression ** radius /** The radius of this chain set collector */,
                bool* isValid /** Is the chainset alive/valid ? */
            );
            /** Delete an edge blend chainset from the edge blend.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveChainset
            (
                int csIndex /** Index of chainset, indicating which chainset we are dealing with */
            );
            /** Delete an edge blend chainset from the edge blend.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveChainsetByCollector
            (
                NXOpen::ScCollector * collector /**The collector for this edge blend chainset */
            );
            /** Get an edge blend setback data for the index provided   @return  Array of Edge collector tags that are used by the setback  <br> License requirements : None */
            public: std::vector<NXOpen::Edge *> GetSetbackData
            (
                int sbIndex /** Index of where setback data item was created. */,
                std::vector<bool> & fromStart /** if true, then the setback is defined at the start
                                           vertex.  Otherwise, it is defined at the end vertex.
                                           There is one for each output edge. */,
                std::vector<NXOpen::Expression *> & distanceExp /**  The distance for the setback on each edge. */
            );
            /** Add an edge blend setback data for an edge in the edge blend  @return  Index of where setback data item is created.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: int AddSetbackData
            (
                const std::vector<NXOpen::Edge *> & edgeArray /** Array of Edge collector tags that are used by the setback */,
                const std::vector<bool> & fromStart /** if true, then the setback is defined at the start
                                           vertex.  Otherwise, it is defined at the end vertex.
                                           There is one for each input edge. */,
                std::vector<NXString> & distance /**  Array of distances   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Remove an edge blend setback data for an edge in the edge blend  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveSetbackData
            (
                int sbIndex /** Index of where setback data item was created*/
            );
            /** Get an edge blend stop short data for the index provided   @return  the Stopshort Data  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::BlendStopshortBuilder * GetNewStopshortData
            (
                int ssIndex /** Index of where stop short data item is created */
            );
            /** Get an edge blend stop short data for the index provided   @return   The distance for the stopshort on the edge. 
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") NXOpen::Expression * GetStopshortData
            (
                int ssIndex /** Index of where stop short data item is created. */,
                NXOpen::Edge ** edge /** Edge the stop short data is on. */,
                bool* fromStart /** if true, then the stopshort is defined at the start
                                                     vertex.  Otherwise, it is defined at the end vertex. */
            );
            /** Add an edge blend stop short data for an edge in the edge blend   @return  Index of where stop short data item is created.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: int AddNewStopshortData
            (
                NXOpen::GeometricUtilities::BlendStopshortBuilder * builder /** the Stopshort Data */
            );
            /** Add an edge blend stop short data for an edge in the edge blend   @return  Index of where stop short data item is created. 
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") int AddStopshortData
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                bool fromStart /** if true, then the stopshort is defined at the start
                                                     vertex.  Otherwise, it is defined at the end vertex. */,
                const NXString & distance /**  The distance for the stopshort on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Remove an edge blend stop short data for an edge   
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void RemoveStopshortData
            (
                NXOpen::Edge * edge /** Edge to remove the stopshort on*/,
                bool fromStart /** if true, then the stopshort is defined at the start
                                                    vertex.  Otherwise, it is defined at the end vertex. */
            );
            /** Remove the stop short from an edge, given its type and location  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveStopshortDataByType
            (
                NXOpen::Edge * edge /** Edge to remove the stopshort on*/,
                bool fromStart /** if true, then the stopshort is defined at the start
                                                              vertex.  Otherwise, it is defined at the end vertex. */,
                NXOpen::GeometricUtilities::BlendStopshortBuilder::Choices type /** the type of the stopshort */
            );
            /** Remove an edge blend stop short corresponding to a BlendStopshortBuilder  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveNewStopshortData
            (
                NXOpen::GeometricUtilities::BlendStopshortBuilder * builder /** the Stopshort Data */
            );
            /** Remove an edge blend stop short data for the index indicated  
             @deprecated Deprecated in NX5.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX5.0.0") void RemoveStopshortData
            (
                int ssIndex /** Index of where stop short data item is created. */
            );
            /** Get all the variable radii data for an edge in the edge blend  @return  Parameter locations of points on the edge 
             @deprecated Deprecated in NX6.0.0 <br> 
             <br> License requirements : None */
            public:  NX_DEPRECATED("Deprecated in NX6.0.0") std::vector<double> GetVariableRadiusData
            (
                NXOpen::Edge * edge /** Edge to get all the varible radius data on*/,
                std::vector<NXOpen::Expression *> & radiiExp /** The radius value of each point on the edge */,
                std::vector<NXOpen::Point *> & smartPoints /** Array of smart points defining variable radius */,
                std::vector<bool> & isExternalFlagArray /** Corresponding is_external flags of the variable radius points*/
            );
            /** Get all the variable radii data for an edge in the edge blend  <br> License requirements : None */
            public: void GetVariableRadiusDataNew
            (
                NXOpen::Edge * edge /** Edge to get all the varible radius data on*/,
                std::vector<NXOpen::Expression *> & parameterExp /** Parameter value of points on the edge */,
                std::vector<NXOpen::Expression *> & radiiExp /** The radius value of each point on the edge */,
                std::vector<NXOpen::Point *> & smartPoints /** Array of smart points defining variable radius */,
                std::vector<bool> & isExternalFlagArray /** Corresponding is_external flags of the variable radius points*/
            );
            /** Add an edge blend variable radius data for an edge in the edge blend  @return  Index of where variable radius data item is created
             @deprecated Deprecated in NX6.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX6.0.0") int AddVariableRadiusData
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                double parameter /** Parameter location of point on the edge */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */
            );
            /** Add an edge blend variable radius data for an edge in the edge blend 
                  * Note: This ja will always create arclength parameter  @return  Index of where variable radius data item is created <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: int AddVariableRadiusDataNew
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                const NXString & parameter /** Parameter location of point on the edge   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */
            );
            /** Add an edge blend variable radius data for an edge in the edge blend  @return  Index of where variable radius data item is created <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: int AddVariableRadiusDataNew
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                const NXString & parameter /** Parameter location of point on the edge   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */,
                bool isArclength /** Flag indicating whether parameter is arclength or not */
            );
            /** Edit an edge blend variable radius data for an edge in the edge blend 
             @deprecated Deprecated in NX6.0.0 <br> 
             <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public:  NX_DEPRECATED("Deprecated in NX6.0.0") void EditVariableRadiusData
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                int vrIndex /** Index of what variable radius data item to edit*/,
                double parameter /** Parameter location of point on the edge */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */
            );
            /** Edit an edge blend variable radius data for an edge in the edge blend  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void EditVariableRadiusDataNew
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                int vrIndex /** Index of what variable radius data item to edit*/,
                const NXString & parameter /** Parameter location of point on the edge   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */
            );
            /** Edit an edge blend variable radius data for an edge in the edge blend  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void EditVariableRadiusDataNew
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                int vrIndex /** Index of what variable radius data item to edit*/,
                const NXString & parameter /** Parameter location of point on the edge   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & radius /**  The radius at this point on the edge.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * smartPoint /** Smart Point defining the location of this vr */,
                bool isExternal /** Flag indicating whether this point is external to blend */,
                bool isArclength /** Flag indicating whether the parameter is arclength or not */
            );
            /** Remove variable radius data on an edge by the parameter value of the point on the edge  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveVariableRadiusData
            (
                NXOpen::Edge * edge /** Edge to add stop short data on*/,
                double parameter /** Parameter location of point on the edge */
            );
            /** Remove variable radius data on an edge by the index into the point array on the edge  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveVariableRadiusDataByIndex
            (
                NXOpen::Edge * edge /** Edge to remove variable radius data on*/,
                int index /** Index into point array on the edge */
            );
            /** Remove all variable radius datas on an edge   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void RemoveVariableRadiusData
            (
                NXOpen::Edge * edge /** Edge to remove all variable radius datas from*/
            );
            /**Returns  the overlap resolution for edge blend   <br> License requirements : None */
            public: NXOpen::Features::EdgeBlendBuilder::Overlap OverlapOption
            (
            );
            /**Sets  the overlap resolution for edge blend   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetOverlapOption
            (
                NXOpen::Features::EdgeBlendBuilder::Overlap overlapOption /** overlap option */ 
            );
            /**Returns  the order of blending for edge blend   <br> License requirements : None */
            public: NXOpen::Features::EdgeBlendBuilder::OrderOfBlending BlendOrder
            (
            );
            /**Sets  the order of blending for edge blend   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetBlendOrder
            (
                NXOpen::Features::EdgeBlendBuilder::OrderOfBlending blendOrder /** blend order */ 
            );
            /**Returns  the setback option for edge blend   <br> License requirements : None */
            public: NXOpen::Features::EdgeBlendBuilder::Setback SetbackOption
            (
            );
            /**Sets  the setback option for edge blend   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSetbackOption
            (
                NXOpen::Features::EdgeBlendBuilder::Setback setbackOption /** setback option */ 
            );
            /**Returns  the forced cliff edges for edge blend   <br> License requirements : None */
            public: NXOpen::ScCollector * CliffEdges
            (
            );
            /**Sets  the forced cliff edges for edge blend   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetCliffEdges
            (
                NXOpen::ScCollector * cliffEdgeCollector /**The cliff edge collector */
            );
            /**Returns  the prohibited cliff edges for edge blend   <br> License requirements : None */
            public: NXOpen::ScCollector * NonCliffEdges
            (
            );
            /**Sets  the prohibited cliff edges for edge blend   <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetNonCliffEdges
            (
                NXOpen::ScCollector * nonCliffEdgeCollector /**The non cliff edge collector */
            );
            /**Returns  the limits list  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::BlendLimitsData * LimitsListData
            (
            );
            /**Returns  the trimming option
                 <br> License requirements : None */
            public: bool TrimmingOption
            (
            );
            /**Sets  the trimming option
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTrimmingOption
            (
                bool optionValue /** option value */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
