#ifndef NXOpen_DISPLAYABLEOBJECT_HXX_INCLUDED
#define NXOpen_DISPLAYABLEOBJECT_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     DisplayableObject.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/IFitTo.hxx>
#include <NXOpen/INXObject.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    class DisplayableObject;
    namespace Assemblies
    {
        class Component;
    }
    class BasePart;
    class IFitTo;
    class INXObject;
    class NXObject;
    class _DisplayableObjectBuilder;
    class DisplayableObjectImpl;
    /** Base class for all objects that are displayable.  <br> This is an abstract class, and cannot be instantiated. <br> */
    class NXOPENCPPEXPORT  DisplayableObject : public NXObject, public virtual IFitTo
    {
        /** specifies object width for objects such as lines and text */
        public: enum ObjectWidth
        {
            ObjectWidthNormal/** normal */ ,
            ObjectWidthThick/** thick */ ,
            ObjectWidthThin/** thin */ 
        };

        /** specifies the object font for objects such as lines */
        public: enum ObjectFont
        {
            ObjectFontSolid = 1/** solid */ ,
            ObjectFontDashed/** dashed */ ,
            ObjectFontPhantom/** phantom */ ,
            ObjectFontCenterline/** centerline */ ,
            ObjectFontDotted/** dotted */ ,
            ObjectFontLongDashed/** long dashed */ ,
            ObjectFontDottedDashed/** dotted dashed */ 
        };

        private: DisplayableObjectImpl * m_displayableobject_impl;
        private: friend class  _DisplayableObjectBuilder;
        protected: DisplayableObject();
        public: ~DisplayableObject();
        /** Blanks the object.  <br> License requirements : None */
        public: void Blank
        (
        );
        /** Unblanks the object.  <br> License requirements : None */
        public: void Unblank
        (
        );
        /**Returns  the blank status of this object.  <br> License requirements : None */
        public: bool IsBlanked
        (
        );
        /** Highlights the object.  <br> License requirements : None */
        public: void Highlight
        (
        );
        /** Unhighlights the object.  <br> License requirements : None */
        public: void Unhighlight
        (
        );
        /**Returns  the color of the object. After setting the color, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect.
                There is a more efficient way to change the color, layer, line font or
                line width of a object. First call
                @link DisplayManager::NewDisplayModification DisplayManager::NewDisplayModification@endlink  and
                then call any combination of set methods for the properties
                @link DisplayModification::NewColor DisplayModification::NewColor @endlink and @link DisplayModification::SetNewColor DisplayModification::SetNewColor @endlink ,
                @link DisplayModification::NewWidth DisplayModification::NewWidth @endlink and @link DisplayModification::SetNewWidth DisplayModification::SetNewWidth @endlink ,
                @link DisplayModification::NewFont DisplayModification::NewFont @endlink and @link DisplayModification::SetNewFont DisplayModification::SetNewFont @endlink 
                and @link DisplayModification::NewLayer DisplayModification::NewLayer @endlink and @link DisplayModification::SetNewLayer DisplayModification::SetNewLayer @endlink . Finally call
                @link DisplayModification::Apply DisplayModification::Apply@endlink  and
                @link TransientObject::Dispose TransientObject::Dispose@endlink .
                This eliminates the need to call @link RedisplayObject RedisplayObject@endlink .  <br> License requirements : None */
        public: int Color
        (
        );
        /**Returns  the layer that the object is in.  After setting the layer, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: int Layer
        (
        );
        /**Returns  the line font of the object. After setting the line font, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: NXOpen::DisplayableObject::ObjectFont LineFont
        (
        );
        /**Returns  the line width of the object.  After setting the line width, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: NXOpen::DisplayableObject::ObjectWidth LineWidth
        (
        );
        /** Sets the location of the object's name.  <br> License requirements : None */
        public: void SetNameLocation
        (
            const NXOpen::Point3d & location /** location */ 
        );
        /**Returns  the location of the object's name.  <br> License requirements : None */
        public: NXOpen::Point3d NameLocation
        (
        );
        /**Sets  the color of the object. After setting the color, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect.
                There is a more efficient way to change the color, layer, line font or
                line width of a object. First call
                @link DisplayManager::NewDisplayModification DisplayManager::NewDisplayModification@endlink  and
                then call any combination of set methods for the properties
                @link DisplayModification::NewColor DisplayModification::NewColor @endlink and @link DisplayModification::SetNewColor DisplayModification::SetNewColor @endlink ,
                @link DisplayModification::NewWidth DisplayModification::NewWidth @endlink and @link DisplayModification::SetNewWidth DisplayModification::SetNewWidth @endlink ,
                @link DisplayModification::NewFont DisplayModification::NewFont @endlink and @link DisplayModification::SetNewFont DisplayModification::SetNewFont @endlink 
                and @link DisplayModification::NewLayer DisplayModification::NewLayer @endlink and @link DisplayModification::SetNewLayer DisplayModification::SetNewLayer @endlink . Finally call
                @link DisplayModification::Apply DisplayModification::Apply@endlink  and
                @link TransientObject::Dispose TransientObject::Dispose@endlink .
                This eliminates the need to call @link RedisplayObject RedisplayObject@endlink .  <br> License requirements : None */
        public: void SetColor
        (
            int color /** color */ 
        );
        /**Sets  the layer that the object is in.  After setting the layer, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: void SetLayer
        (
            int layer /** layer */ 
        );
        /**Sets  the line font of the object. After setting the line font, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: void SetLineFont
        (
            NXOpen::DisplayableObject::ObjectFont font /** font */ 
        );
        /**Sets  the line width of the object.  After setting the line width, you must call
                @link RedisplayObject RedisplayObject@endlink  in order for the change to take effect,
                except see the comments for @link DisplayableObject::Color DisplayableObject::Color @endlink and @link DisplayableObject::SetColor DisplayableObject::SetColor @endlink .  <br> License requirements : None */
        public: void SetLineWidth
        (
            NXOpen::DisplayableObject::ObjectWidth width /** width */ 
        );
        /** Redisplays the object in all views. Typically this is used to display
            an object after its creation.  <br> License requirements : None */
        public: void RedisplayObject
        (
        );
    };
}
#undef EXPORTLIBRARY
#endif
