#ifndef NXOpen_FACET_STLIMPORTBUILDER_HXX_INCLUDED
#define NXOpen_FACET_STLIMPORTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Facet_STLImportBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_facet_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Facet
    {
        class STLImportBuilder;
    }
    class Builder;
    class Part;
    namespace Facet
    {
        class _STLImportBuilderBuilder;
        class STLImportBuilderImpl;
        /** The STL file import builder. Inputs to this class can be convergent objects. <br> To create a new instance of this class, use @link NXOpen::Facet::FacetedBodyCollection::CreateSTLImportBuilder  NXOpen::Facet::FacetedBodyCollection::CreateSTLImportBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        AngularTolerance </term> <description> 
         
        Medium </description> </item> 

        <item><term> 
         
        FacetBodyType </term> <description> 
         
        Psm </description> </item> 

        <item><term> 
         
        HideSmoothEdges </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        MinimumAngleFoldedFacets </term> <description> 
         
        15.0 </description> </item> 

        <item><term> 
         
        MinimumFacetNumber </term> <description> 
         
        100 </description> </item> 

        <item><term> 
         
        STLFileUnits </term> <description> 
         
        Millimeters </description> </item> 

        <item><term> 
         
        ShowInformationWindow </term> <description> 
         
        0 </description> </item> 

        </list> 

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_FACETEXPORT  STLImportBuilder : public NXOpen::Builder
        {
            /** The angular tolerance types*/
            public: enum AngularToleranceTypes
            {
                AngularToleranceTypesCoarse/** coarse */ ,
                AngularToleranceTypesMedium/** medium */ ,
                AngularToleranceTypesFine/** fine */ 
            };

            /** The STL file units types */
            public: enum STLFileUnitsTypes
            {
                STLFileUnitsTypesMeters/** meters */ ,
                STLFileUnitsTypesMillimeters/** millimeters */ ,
                STLFileUnitsTypesInches/** inches */ 
            };

            /** These represent the type of body that will get created on importing the STL file */
            public: enum FacetBodyTypes
            {
                FacetBodyTypesPsm/** Import to Facet Brep format*/,
                FacetBodyTypesNx/** Import To NX Facet Format */,
                FacetBodyTypesJt/** Import to JT format*/
            };

            private: STLImportBuilderImpl * m_stlimportbuilder_impl;
            private: friend class  _STLImportBuilderBuilder;
            protected: STLImportBuilder();
            public: ~STLImportBuilder();
            /**Returns  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") OR nx_masterfem ("Finite Element Modeling") */
            public: NXString File
            (
            );
            /**Sets  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetFile
            (
                const NXString & filename /** filename */ 
            );
            /**Sets  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") OR nx_masterfem ("Finite Element Modeling") */
            void SetFile
            (
                const char * filename /** filename */ 
            );
            /**Returns  the indicator for whether to hide smooth edges 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: bool HideSmoothEdges
            (
            );
            /**Sets  the indicator for whether to hide smooth edges 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetHideSmoothEdges
            (
                bool hideSmoothEdges /** hidesmoothedges */ 
            );
            /**Returns  the angular tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Facet::STLImportBuilder::AngularToleranceTypes AngularTolerance
            (
            );
            /**Sets  the angular tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetAngularTolerance
            (
                NXOpen::Facet::STLImportBuilder::AngularToleranceTypes angularTolerance /** angulartolerance */ 
            );
            /**Returns  the STL file units 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Facet::STLImportBuilder::STLFileUnitsTypes STLFileUnits
            (
            );
            /**Sets  the STL file units 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetSTLFileUnits
            (
                NXOpen::Facet::STLImportBuilder::STLFileUnitsTypes stlFileUnits /** stlfileunits */ 
            );
            /**Returns  the indicator for whether to show information window 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: bool ShowInformationWindow
            (
            );
            /**Sets  the indicator for whether to show information window 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetShowInformationWindow
            (
                bool showInformationWindow /** showinformationwindow */ 
            );
            /**Returns  the facet body type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Facet::STLImportBuilder::FacetBodyTypes FacetBodyType
            (
            );
            /**Sets  the facet body type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetFacetBodyType
            (
                NXOpen::Facet::STLImportBuilder::FacetBodyTypes facetBodyType /** facetbodytype */ 
            );
            /**Returns  the option to clean up all mesh defects on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: bool CleanUp
            (
            );
            /**Sets  the option to clean up all mesh defects on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetCleanUp
            (
                bool cleanUp /** cleanup */ 
            );
            /**Returns  the value for minimum angle between adjacent facets to define folded facets. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: double MinimumAngleFoldedFacets
            (
            );
            /**Sets  the value for minimum angle between adjacent facets to define folded facets. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetMinimumAngleFoldedFacets
            (
                double minimumAngleFoldedFacets /** minimumanglefoldedfacets */ 
            );
            /**Returns  the value for minimum number of facets for a STL file to be imported 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: int MinimumFacetNumber
            (
            );
            /**Sets  the value for minimum number of facets for a STL file to be imported 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: void SetMinimumFacetNumber
            (
                int minimumFacetNumber /** minimumfacetnumber */ 
            );
            /**  The imported bodies after STL file import 
             <br>  Created in NX1926.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") OR nx_masterfem ("Finite Element Modeling") */
            public: std::vector<NXOpen::Part *> GetTopology
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
