#ifndef NXOpen_FEATURES_SHIPDESIGN_PILLARBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHIPDESIGN_PILLARBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_PillarBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_ShipDesign_BuiltUpBlockBuilder.hxx>
#include <NXOpen/Features_ShipDesign_EndCutBuilder.hxx>
#include <NXOpen/Features_ShipDesign_PlateStockBuilder.hxx>
#include <NXOpen/Features_ShipDesign_PointPairBuilder.hxx>
#include <NXOpen/Features_ShipDesign_ShipNamesBuilder.hxx>
#include <NXOpen/Features_ShipDesign_SteelFeatureSpreadsheetBuilder.hxx>
#include <NXOpen/Features_ShipDesign_StiffenerLimitBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class PillarBuilder;
        }
    }
    class CoordinateSystem;
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class BuiltUpBlockBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class EndCutBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class PlateStockBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class PointPairBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class ShipNamesBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class SteelFeatureSpreadsheetBuilder;
        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class StiffenerLimitBuilder;
        }
    }
    class NXObjectList;
    class Plane;
    class SelectNXObjectList;
    class SelectTaggedObject;
    namespace Features
    {
        namespace ShipDesign
        {
            class _PillarBuilderBuilder;
            class PillarBuilderImpl;
            /**
                    Represents a @link NXOpen::Features::ShipDesign::Pillar NXOpen::Features::ShipDesign::Pillar@endlink  builder
                     <br> To create a new instance of this class, use @link NXOpen::Features::ShipCollection::CreatePillarBuilder  NXOpen::Features::ShipCollection::CreatePillarBuilder @endlink  <br> 
            Default values.
            <list type="table"> 
             
            <listheader><term> 
            Property</term>  <description> 
            Value</description> </listheader>
            <item><term> 
             
            AngleTolerance </term> <description> 
             
            0.5 (millimeters part), 0.5 (inches part) </description> </item> 

            <item><term> 
             
            AngularDim.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            DistanceTolerance </term> <description> 
             
            0.0254 (millimeters part), 0.001 (inches part) </description> </item> 

            <item><term> 
             
            EndCapPlateStock.KnuckleRatio </term> <description> 
             
            3.0 </description> </item> 

            <item><term> 
             
            EndCapPlateStock.KnuckleSmoothAngle </term> <description> 
             
            3.0 </description> </item> 

            <item><term> 
             
            EndCapPlateStock.MaterialOption </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            EndCapPlateStock.OppositeThickness.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            EndCapPlateStock.RestrictThicknessToMaterial </term> <description> 
             
            true </description> </item> 

            <item><term> 
             
            EndCapPlateStock.ThickenOption </term> <description> 
             
            SingleSided </description> </item> 

            <item><term> 
             
            EndCapPlateStock.Thickness.Value </term> <description> 
             
            10 (millimeters part), 0.5 (inches part) </description> </item> 

            <item><term> 
             
            EndCapPlateStock.ThicknessSourceOption </term> <description> 
             
            List </description> </item> 

            <item><term> 
             
            EndCapThickness.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            EndCutType </term> <description> 
             
            None </description> </item> 

            <item><term> 
             
            EndEndCut.ConnectionType </term> <description> 
             
            Connected </description> </item> 

            <item><term> 
             
            EndEndCut.DraftAngle.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            EndEndCut.DraftOffset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            EndEndCut.DraftType </term> <description> 
             
            Trim </description> </item> 

            <item><term> 
             
            EndEndCut.EndFaceType </term> <description> 
             
            NeatTrim </description> </item> 

            <item><term> 
             
            EndEndCut.LimitType </term> <description> 
             
            Value </description> </item> 

            <item><term> 
             
            EndEndCut.Offset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            EndEndCut.SelectionType </term> <description> 
             
            FacesWithAttributes </description> </item> 

            <item><term> 
             
            EndEndCut.ShearAngle.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            EndEndCut.TiltAngle.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            EndLimit.LimitMethod </term> <description> 
             
            Value </description> </item> 

            <item><term> 
             
            EndLimit.LimitValue.Value </term> <description> 
             
            0 </description> </item> 

            <item><term> 
             
            EndOffset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            Line1Offset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            Line2Offset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            PlacementMethod </term> <description> 
             
            TwoPlanesandLines </description> </item> 

            <item><term> 
             
            SectionType </term> <description> 
             
            Profile </description> </item> 

            <item><term> 
             
            StartCapThickness.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            StartOffset.Value </term> <description> 
             
            0 (millimeters part), 0 (inches part) </description> </item> 

            <item><term> 
             
            SupportCapOptions </term> <description> 
             
            None </description> </item> 

            </list> 

             <br>  Created in NX8.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  PillarBuilder : public NXOpen::Features::FeatureBuilder
            {
                /** SpreadSheet Type  Profile or BuiltUp */
                public: enum StockSectionType
                {
                    StockSectionTypeProfile/** Profile Stock */,
                    StockSectionTypeBuiltUp/** Built Up Stock */
                };

                /** Method used to create the support feature. */
                public: enum CreationMethod
                {
                    CreationMethodTwoPlanesandLines/** two planesand lines */ ,
                    CreationMethodSpecifyLine/** specify line */ ,
                    CreationMethodSpecifyCsys/** specify csys */ ,
                    CreationMethodAdoption/** adoption */ ,
                    CreationMethodStructure/** structure */ ,
                    CreationMethodPoints/** points */ 
                };

                /** Settings to indicate how the cap is designed. */
                public: enum CapOptions
                {
                    CapOptionsNone/** none */ ,
                    CapOptionsTwoSided/** two sided */ ,
                    CapOptionsSymmetric/** symmetric */ 
                };

                /** this specifies end type option */
                public: enum EndTypeOptions
                {
                    EndTypeOptionsNone/** No end cuts are applied */,
                    EndTypeOptionsEndcut/** The same end cut is applied to both ends */,
                    EndTypeOptionsCap/** Each end has different end cuts */
                };

                /** this specifies how the end cuts are applied */
                public: enum EndCutTypes
                {
                    EndCutTypesNone/** No end cuts are applied */,
                    EndCutTypesSymmetric/** The same end cut is applied to both ends */,
                    EndCutTypesTwoSided/** Each end has different end cuts */
                };

                /** this specifies how the end is treated */
                public: enum EndTreatmentTypes
                {
                    EndTreatmentTypesEndcut/** end cuts are applied */,
                    EndTreatmentTypesCap/** caps are applied */
                };

                private: PillarBuilderImpl * m_pillarbuilder_impl;
                private: friend class  _PillarBuilderBuilder;
                protected: PillarBuilder();
                public: ~PillarBuilder();
                /**Returns  the section type (profile or plate) 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::StockSectionType SectionType
                (
                );
                /**Sets  the section type (profile or plate) 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_basic ("Ship Basic Design") OR nx_ship_detail ("Ship Detail Design") */
                public: void SetSectionType
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::StockSectionType sectionType /** sectiontype */ 
                );
                /**Returns  the placement method used to locate the pillar. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::CreationMethod PlacementMethod
                (
                );
                /**Sets  the placement method used to locate the pillar. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetPlacementMethod
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::CreationMethod placementMethod /** placementmethod */ 
                );
                /**Returns  the start plane (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Plane * StartPlane
                (
                );
                /**Sets  the start plane (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetStartPlane
                (
                    NXOpen::Plane * startPlane /** startplane */ 
                );
                /**Returns  the select guide curve (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * GuideCurve
                (
                );
                /**Returns  the first line (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * Line1
                (
                );
                /**Returns  the second line (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * Line2
                (
                );
                /**Returns  the end plane (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Plane * EndPlane
                (
                );
                /**Sets  the end plane (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetEndPlane
                (
                    NXOpen::Plane * endPlane /** endplane */ 
                );
                /**Returns  the coordinate system (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CoordinateSystem * CoordSystem
                (
                );
                /**Sets  the coordinate system (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetCoordSystem
                (
                    NXOpen::CoordinateSystem * coordSystem /** coordsystem */ 
                );
                /**Returns  the orientation line (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * OrientationLine
                (
                );
                /**Returns  the adoption body. (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodAdoption NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodAdoption@endlink  creation method). 
                 <br>  Created in NX8.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * AdoptionBody
                (
                );
                /**Returns  the angle that the pillar stock will be rotated about its path from its initial location. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * AngularDim
                (
                );
                /**Returns  the first line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Line1Offset
                (
                );
                /**Returns  the reverse first line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseLine1Offset
                (
                );
                /**Sets  the reverse first line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseLine1Offset
                (
                    bool reverseLine1Offset /** reverseline1offset */ 
                );
                /**Returns  the second line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Line2Offset
                (
                );
                /**Returns  the reverse second line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseLine2Offset
                (
                );
                /**Sets  the reverse second line offset (only used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodTwoPlanesandLines@endlink  creation method). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseLine2Offset
                (
                    bool reverseLine2Offset /** reverseline2offset */ 
                );
                /**Returns  the offset used to determine where the support starts (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * StartOffset
                (
                );
                /**Returns  the reverse start offset (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseStartOffset
                (
                );
                /**Sets  the reverse start offset (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseStartOffset
                (
                    bool reverseStartOffset /** reversestartoffset */ 
                );
                /**Returns  the offset used to determine where the support ends (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * EndOffset
                (
                );
                /**Returns  the reverse end offset (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseEndOffset
                (
                );
                /**Sets  the reverse end offset (used with @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyLine@endlink  
                            and @link NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys NXOpen::Features::ShipDesign::PillarBuilder::CreationMethodSpecifyCsys@endlink  creation methods). 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseEndOffset
                (
                    bool reverseEndOffset /** reverseendoffset */ 
                );
                /**Returns  the support cap options. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::CapOptions SupportCapOptions
                (
                );
                /**Sets  the support cap options. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetSupportCapOptions
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::CapOptions supportCapOptions /** supportcapoptions */ 
                );
                /**Returns  the stock used to build the pillar from. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::SteelFeatureSpreadsheetBuilder * MainStock
                (
                );
                /**Returns  the list of Seams 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::BuiltUpBlockBuilder * BuiltUpBlock
                (
                );
                /**Returns  the list of available material attributes. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::SteelFeatureSpreadsheetBuilder * StartCapStock
                (
                );
                /**Returns  the start cap thickness. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * StartCapThickness
                (
                );
                /**Returns  the list of available material attributes. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::SteelFeatureSpreadsheetBuilder * EndCapStock
                (
                );
                /**Returns  the end cap thickness. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * EndCapThickness
                (
                );
                /**Returns  the end type Option 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::EndTypeOptions EndTypeOption
                (
                );
                /**Sets  the end type Option 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetEndTypeOption
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::EndTypeOptions endTypeOption /** endtypeoption */ 
                );
                /**Returns  the end cut type Symmetric or TwoSided 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::EndCutTypes EndCutType
                (
                );
                /**Sets  the end cut type Symmetric or TwoSided 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetEndCutType
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::EndCutTypes endcutType /** endcuttype */ 
                );
                /**Returns  the start end cut 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::EndCutBuilder * StartEndCut
                (
                );
                /**Returns  the end end cut 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::EndCutBuilder * EndEndCut
                (
                );
                /**Returns  the distance tolerance. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: double DistanceTolerance
                (
                );
                /**Sets  the distance tolerance. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetDistanceTolerance
                (
                    double distanceTolerance /** distancetolerance */ 
                );
                /**Returns  the angle tolerance. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: double AngleTolerance
                (
                );
                /**Sets  the angle tolerance. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetAngleTolerance
                (
                    double angleTolerance /** angletolerance */ 
                );
                /** Gets the show migrated body flag. Reserved for administrator use only.
                 <br>  Created in NX8.5.3.  <br>  
                 <br> License requirements : None */
                public: bool GetShowMigratedBody
                (
                );
                /** Sets the show migrated body flag. Reserved for administrator use only.
                 <br>  Created in NX8.5.3.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetShowMigratedBody
                (
                    bool showMigratedBody /** showmigratedbody */ 
                );
                /**Returns  the ship structure to intersect with each other that defines the start of a pillar. Only used when Type is Features.ShipDesign.PillarSystemBuilder.Types.ShipStructure. 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectNXObjectList * IntersectingObjects
                (
                );
                /**Returns  the list of pairs of points that define the ends of the pillars. Only used when Type is Features.ShipDesign.PillarSystemBuilder.Types.Points. 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXObjectList * PointPairList
                (
                );
                /** Creates a @link NXOpen::Features::ShipDesign::PointPairBuilder NXOpen::Features::ShipDesign::PointPairBuilder@endlink . 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: NXOpen::Features::ShipDesign::PointPairBuilder * CreatePointPairBuilder
                (
                );
                /**Returns  the direction of the pillar. Only used when Type is Features.ShipDesign.PillarBuilder.Types.ShipStructure. 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Direction * Direction
                (
                );
                /**Sets  the direction of the pillar. Only used when Type is Features.ShipDesign.PillarBuilder.Types.ShipStructure. 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetDirection
                (
                    NXOpen::Direction * direction /** direction */ 
                );
                /**Returns  the start treatment type: Endcut or Cap 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::EndTreatmentTypes StartTreatmentType
                (
                );
                /**Sets  the start treatment type: Endcut or Cap 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetStartTreatmentType
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::EndTreatmentTypes startTreatmentType /** starttreatmenttype */ 
                );
                /**Returns  the end treatment type: Endcut or Cap 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PillarBuilder::EndTreatmentTypes EndTreatmentType
                (
                );
                /**Sets  the end treatment type: Endcut or Cap 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetEndTreatmentType
                (
                    NXOpen::Features::ShipDesign::PillarBuilder::EndTreatmentTypes endTreatmentType /** endtreatmenttype */ 
                );
                /**Returns  the plate stock builder, which defines the seam material, grade, and thickness
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PlateStockBuilder * StartCapPlateStock
                (
                );
                /**Returns  the plate stock builder, which defines the seam material, grade, and thickness
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::PlateStockBuilder * EndCapPlateStock
                (
                );
                /**Returns  the start path limit 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::StiffenerLimitBuilder * StartLimit
                (
                );
                /**Returns  the end path limit 
                 <br>  Created in NX9.0.1.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::StiffenerLimitBuilder * EndLimit
                (
                );
                /**Returns  the reverse orientation direction  
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseOrientationDirection
                (
                );
                /**Sets  the reverse orientation direction  
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseOrientationDirection
                (
                    bool reverseOrientationDirection /** reverseorientationdirection */ 
                );
                /**Returns  the reverse reference direction  
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ReverseReferenceDirection
                (
                );
                /**Sets  the reverse reference direction  
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void SetReverseReferenceDirection
                (
                    bool reverseReferenceDirection /** reversereferencedirection */ 
                );
                /**Returns  the anchor point. 
                 <br>  Created in NX9.0.3.  <br>  
                 <br> License requirements : None */
                public: int AnchorPoint
                (
                );
                /**Sets  the anchor point. 
                 <br>  Created in NX9.0.3.  <br>  
                 <br> License requirements : nx_ship_basic ("Ship Basic Design") OR nx_ship_detail ("Ship Detail Design") */
                public: void SetAnchorPoint
                (
                    int anchorPoint /** anchorpoint */ 
                );
                /** Update anchor points 
                 <br>  Created in NX9.0.3.  <br>  
                 <br> License requirements : None */
                public: void PopulateAnchorPointList
                (
                );
                /** The list of available anchor points  @return  Array of available anchor point names.
                                                                        These names are read from the current reuse sketch  
                 <br>  Created in NX9.0.3.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXString> GetAvailableAnchorPointNames
                (
                );
                /**Returns   @brief  The ship name builder.  

                 
                            
                                The ship name builder is used to construct the part name of the structure.
                             
                 <br>  Created in NX11.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::ShipNamesBuilder * ShipNames
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
