#ifndef NXOpen_FEATURES_GRIDTARGETBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_GRIDTARGETBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_GridTargetBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class GridTargetBuilder;
    }
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    class Point;
    namespace Features
    {
        class _GridTargetBuilderBuilder;
        class GridTargetBuilderImpl;

        /// \cond NX_NO_DOC 
        /**
            Represents a @link Features::GridTarget Features::GridTarget@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::AVDACollection::CreateGridTargetBuilder  NXOpen::Features::AVDACollection::CreateGridTargetBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        AngleIncrement.Value </term> <description> 
         
        15 </description> </item> 

        <item><term> 
         
        BoundaryOffset.Value </term> <description> 
         
        1000 (millimeters part), 39.370 (inches part) </description> </item> 

        <item><term> 
         
        DisplayAngleValues </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        EndAngle.Value </term> <description> 
         
        75 </description> </item> 

        <item><term> 
         
        EndRadius.Value </term> <description> 
         
        12000 (millimeters part), 472.440 (inches part) </description> </item> 

        <item><term> 
         
        GridLocation </term> <description> 
         
        Floor </description> </item> 

        <item><term> 
         
        GridType </term> <description> 
         
        CircularRadius </description> </item> 

        <item><term> 
         
        RadLinesAngleIncrement.Value </term> <description> 
         
        45 </description> </item> 

        <item><term> 
         
        RadiusIncrement.Value </term> <description> 
         
        3000 (millimeters part), 118.110 (inches part) </description> </item> 

        <item><term> 
         
        ShowRadiatingLines </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        ShowRectangularBoundary </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        Standard </term> <description> 
         
        Iso5006 </description> </item> 

        <item><term> 
         
        StartAngle.Value </term> <description> 
         
        15 </description> </item> 

        <item><term> 
         
        StartRadius.Value </term> <description> 
         
        3000 (millimeters part), 118.110 (inches part) </description> </item> 

        <item><term> 
         
        UseLoadingSpecifiedStandard </term> <description> 
         
        1 </description> </item> 

        </list> 

         <br>  Created in NX1953.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  GridTargetBuilder : public NXOpen::Features::FeatureBuilder
        {
            /**
                    Used to indicate the grid location
                    */
            public: enum GridLocations
            {
                GridLocationsFloor/** floor */ ,
                GridLocationsWall/** wall */ ,
                GridLocationsNotDefined/** not defined */ 
            };

            /**
                    Used to indicate the grid standard
                    */
            public: enum GridStandards
            {
                GridStandardsIso5006/** iso5006 */ ,
                GridStandardsIso5721/** iso5721 */ ,
                GridStandardsUserDefined/** user defined */ ,
                GridStandardsNotDefined/** not defined */ 
            };

            /**
                    Used to indicate the type of grid
                    */
            public: enum GridTypes
            {
                GridTypesCircularRadius/** circular radius */ ,
                GridTypesCircularConical/** circular conical */ ,
                GridTypesCircularDefaultConical/** circular default conical */ ,
                GridTypesStandard/** standard */ 
            };

            private: GridTargetBuilderImpl * m_gridtargetbuilder_impl;
            private: friend class  _GridTargetBuilderBuilder;
            protected: GridTargetBuilder();
            public: ~GridTargetBuilder();

            /// \cond NX_NO_DOC 
            /**Returns  the grid location 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::GridTargetBuilder::GridLocations GridLocation
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the grid location 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetGridLocation
            (
                NXOpen::Features::GridTargetBuilder::GridLocations gridLocation /** gridlocation */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the standard 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::GridTargetBuilder::GridStandards Standard
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the standard 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetStandard
            (
                NXOpen::Features::GridTargetBuilder::GridStandards standard /** standard */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the use loading specified standard 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: bool UseLoadingSpecifiedStandard
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the use loading specified standard 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetUseLoadingSpecifiedStandard
            (
                bool useLoadingSpecifiedStandard /** useloadingspecifiedstandard */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the loading 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXString Loading
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the loading 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetLoading
            (
                const NXString & loading /** loading */ 
            );
            /**Sets  the loading 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            void SetLoading
            (
                const char * loading /** loading */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the grid type 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::GridTargetBuilder::GridTypes GridType
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the grid type 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetGridType
            (
                NXOpen::Features::GridTargetBuilder::GridTypes gridType /** gridtype */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the grid reference point 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * GridReferencePoint
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the grid reference point 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetGridReferencePoint
            (
                NXOpen::Point * gridReferencePoint /** gridreferencepoint */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the start radius 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * StartRadius
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the end radius 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * EndRadius
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the radius increment 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * RadiusIncrement
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the start angle 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * StartAngle
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the end angle 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * EndAngle
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the angle increment 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * AngleIncrement
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the show radiating lines 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: bool ShowRadiatingLines
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the show radiating lines 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetShowRadiatingLines
            (
                bool showRadiatingLines /** showradiatinglines */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the start direction 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * StartDirection
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the start direction 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetStartDirection
            (
                NXOpen::Direction * startDirection /** startdirection */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the rad lines angle increment 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * RadLinesAngleIncrement
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the display angle values 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: bool DisplayAngleValues
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the display angle values 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetDisplayAngleValues
            (
                bool displayAngleValues /** displayanglevalues */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the show rectangular boundary 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: bool ShowRectangularBoundary
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the show rectangular boundary 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : nx_general_packaging ("NX General Packaging") */
            public: void SetShowRectangularBoundary
            (
                bool showRectangularBoundary /** showrectangularboundary */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the boundary offset 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * BoundaryOffset
            (
            );

            /// \endcond 
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
