<html>
	<head>
        <title>PMIExample</title>
        <meta http-equiv="Content-Language" content="en-us">
        <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    </head>
    <body>
        <DIV class="Section1">
            <H3>PMIExample
            </H3>
            <P>This example demonstrates the creation of a PMI dimension.&nbsp;</P>

            <h4>Files required</h4>
            <ol>
            <li> PMIExample.java </li>
			<li> PMIExample.jar </li>
			<li> PMIExample.class </li>
			<li> PMIExample_Makefile_win </li>
            <li> PMIExample_cylinder.prt : This file is located at $UGII_BASE_DIR/ugopen/SampleNXOpenApplications/C++/PMIExample.</li>
			</ol>
            <h4>How to run the example</h4>
            <P>Unless noted otherwise, the commands in these instructions must be run from an 
                NX command prompt.&nbsp; See the general notes of the examples for <A href="../../README.htm#How_to_start_an_NX_command_prompt">
                    instructions on how to start an NX command prompt</A>.</P>
            <P>Instructions for Windows: All commands are the same as in Unix except substitute "make" with 
			"nmake -f Makefile_win".</P>

            <h5>Interactive mode</h5>
			
            <OL style="MARGIN-TOP: 0in" type="1">
                <LI class="MsoNormal" style="mso-list: l3 level1 lfo3; tab-stops: list .5in">
                    Compile the example with following command:
                </LI>
            </OL>
            <PRE style="MARGIN-LEFT: 0.5in">make</PRE>
            
			<OL style="MARGIN-TOP: 0in" type="1" start="2">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
                    Start NX. 
                </LI>
            </OL>
			
            <OL style="MARGIN-TOP: 0in" type="1" start="3">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
                    Open PMIExample_cylinder.prt part file.
                </LI>
            </OL>
			
			<OL style="MARGIN-TOP: 0in" type="1" start="4">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
                    Enter into Modeling application through Start->All Applications->Modeling.
                </LI>
            </OL>

            <OL style="MARGIN-TOP: 0in" type="1" start="5">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
					In NX, go to File - Execute - NX Open, select PMIExample.jar, and press 
                Ok. 
                </LI>
            </OL>
					
			<OL style="MARGIN-TOP: 0in" type="1" start="6">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
					This will create a dimension on the cylinder in the 3D Model.
                </LI>
            </OL>
			
			<OL style="MARGIN-TOP: 0in" type="1" start="7">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
					Now enter into Drafting application through Start->All Applications-Drafting.
				 </LI>
            </OL>
			
			<OL style="MARGIN-TOP: 0in" type="1" start="8">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
					In NX, go to File - Execute - NX Open, select PMIExample.jar, and press Ok.
				 </LI>
            </OL>
			
			<OL style="MARGIN-TOP: 0in" type="1" start="9">
                <LI class="MsoNormal" style="mso-list: l2 level1 lfo6; tab-stops: list .5in">
					Then a dimension will be created in the drafting view.&nbsp;
				</LI>
            </OL>
        </DIV>
    </body>
</html>
