#ifndef NXOpen_FEATURES_TANGENTBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_TANGENTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_TangentBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_FaceRecognitionBuilder.hxx>
#include <NXOpen/Features_TangentBuilder.hxx>
#include <NXOpen/GeometricUtilities_FaceChangeOverflowBehavior.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class TangentBuilder;
    }
    namespace Features
    {
        class FaceRecognitionBuilder;
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class FaceChangeOverflowBehavior;
    }
    class Point;
    class SelectFace;
    class SelectISurface;
    namespace Features
    {
        class _TangentBuilderBuilder;
        /**
            Represents a @link Features::Tangent Features::Tangent@endlink  builder
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateTangentBuilder Features::FeatureCollection::CreateTangentBuilder@endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        MoveAlongFace.CoaxialEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.CoplanarAxesEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.CoplanarEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.EqualDiameterEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.OffsetEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.ParallelEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.PerpendicularEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.SymmetricEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.TangentEnabled </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        MoveAlongFace.UseFaceBrowse </td> <td> 
         
        1 </td> </tr> 

        </table>  
        */
        class NXOPENCPPEXPORT TangentBuilder : public Features::FeatureBuilder
        {
            private: friend class  _TangentBuilderBuilder;
            protected: TangentBuilder();
            /**Returns  the motion face  <br> License requirements : None */
            public: NXOpen::SelectFace * MotionFace
            (
            );
            /**Returns  the through point  <br> License requirements : None */
            public: NXOpen::Point * ThroughPoint
            (
            );
            /**Sets  the through point  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetThroughPoint
            (
                NXOpen::Point * throughPoint /** throughpoint */ 
            );
            /**Returns  the stationary face  <br> License requirements : None */
            public: NXOpen::SelectISurface * StationaryFace
            (
            );
            /**Returns  the move along faces  <br> License requirements : None */
            public: NXOpen::Features::FaceRecognitionBuilder * MoveAlongFace
            (
            );
            /**Returns  the face change overflow behavior. Please refer @link GeometricUtilities::FaceChangeOverflowBehavior GeometricUtilities::FaceChangeOverflowBehavior@endlink  for details.  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::FaceChangeOverflowBehavior * FaceChangeOverflowBehavior
            (
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
