#ifndef NXOpen_FEATURES_CYLINDERBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_CYLINDERBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_CylinderBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_CylinderBuilder.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class CylinderBuilder;
    }
    class Axis;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class BooleanOperation;
    }
    class SelectICurve;
    namespace Features
    {
        class _CylinderBuilderBuilder;
        /**
            Represents a @link Features::Cylinder Features::Cylinder@endlink  builder
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateCylinderBuilder Features::FeatureCollection::CreateCylinderBuilder@endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        BooleanOption.Type </td> <td> 
         
        Create </td> </tr> 

        <tr><td> 
         
        Diameter.Value </td> <td> 
         
        50.0 (millimeters part), 2.0 (inches part) </td> </tr> 

        <tr><td> 
         
        Height.Value </td> <td> 
         
        100.0 (millimeters part), 4.0 (inches part) </td> </tr> 

        <tr><td> 
         
        ReverseDirection </td> <td> 
         
        false </td> </tr> 

        <tr><td> 
         
        Type </td> <td> 
         
        AxisDiameterAndHeight </td> </tr> 

        </table>  
        */
        class NXOPENCPPEXPORT CylinderBuilder : public Features::FeatureBuilder
        {
            /** the cylinder types */
            public: enum Types
            {
                TypesAxisDiameterAndHeight/** Axis, Diameter and Height */,
                TypesArcAndHeight/** Arc and Height */
            };

            private: friend class  _CylinderBuilderBuilder;
            protected: CylinderBuilder();
            /**Returns  the type  <br> License requirements : None */
            public: NXOpen::Features::CylinderBuilder::Types Type
            (
            );
            /**Sets  the type  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetType
            (
                NXOpen::Features::CylinderBuilder::Types type /** type */ 
            );
            /**Returns  the axis  <br> License requirements : None */
            public: NXOpen::Axis * Axis
            (
            );
            /**Sets  the axis  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAxis
            (
                NXOpen::Axis * axis /** axis */ 
            );
            /**Returns  the diameter. This will be used only when the law type is Axis, Diameter, and Height  <br> License requirements : None */
            public: NXOpen::Expression * Diameter
            (
            );
            /**Returns  the height  <br> License requirements : None */
            public: NXOpen::Expression * Height
            (
            );
            /**Returns  the boolean option  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::BooleanOperation * BooleanOption
            (
            );
            /**Returns  the arc  <br> License requirements : None */
            public: NXOpen::SelectICurve * Arc
            (
            );
            /**Returns  the reverse direction
                     <br> License requirements : None */
            public: bool ReverseDirection
            (
            );
            /**Sets  the reverse direction
                     <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetReverseDirection
            (
                bool reverse /** reverse */ 
            );
            /**Returns  the cylinder origin
                     <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Point3d Origin
            (
            );
            /**Sets  the cylinder origin
                     <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetOrigin
            (
                const NXOpen::Point3d & origin /** origin */ 
            );
            /**Returns  the cylinder direction
                     <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Vector3d Direction
            (
            );
            /**Sets  the cylinder direction
                     <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDirection
            (
                const NXOpen::Vector3d & vector /** vector */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
