#ifndef NXOpen_FEATURES_SHEETMETAL_EDGERIPBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_EDGERIPBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_EdgeRipBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_SheetMetal_SheetmetalBaseBuilder.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class EdgeRipBuilder;
        }
    }
    class Edge;
    class Expression;
    namespace Features
    {
        namespace SheetMetal
        {
            class SheetmetalBaseBuilder;
        }
    }
    namespace Features
    {
        class SketchFeature;
    }
    class Section;
    namespace Features
    {
        namespace SheetMetal
        {
            class _EdgeRipBuilderBuilder;
            class EdgeRipBuilderImpl;
            /** Represents a Edge Rip feature builder.  <br> To create a new instance of this class, use @link NXOpen::Features::SheetMetal::SheetmetalManager::CreateEdgeRipFeatureBuilder  NXOpen::Features::SheetMetal::SheetmetalManager::CreateEdgeRipFeatureBuilder @endlink  <br> 
             <br>  Created in NX4.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  EdgeRipBuilder : public NXOpen::Features::SheetMetal::SheetmetalBaseBuilder
            {
                /** This enum defines the end cap shapes. */
                public: enum EndCapShapeOptions
                {
                    EndCapShapeOptionsSquare/**square end caps*/,
                    EndCapShapeOptionsRound/**round end caps*/
                };

                private: EdgeRipBuilderImpl * m_edgeripbuilder_impl;
                private: friend class  _EdgeRipBuilderBuilder;
                protected: EdgeRipBuilder();
                public: ~EdgeRipBuilder();
                /**Returns  the section used by Edge Rip 
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: NXOpen::Section * Section
                (
                );
                /**Sets  the section used by Edge Rip 
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetSection
                (
                    NXOpen::Section * section /** section */ 
                );
                /**Returns  the Slave Sketch used by the Edge Rip, If one exists.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: NXOpen::Features::SketchFeature * Sketch
                (
                );
                /**Sets  the Slave Sketch used by the Edge Rip, If one exists.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetSketch
                (
                    NXOpen::Features::SketchFeature * sketch /** sketch */ 
                );
                /** Edges to rip 
                 <br>  Created in NX5.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetRipEdges
                (
                    const std::vector<NXOpen::Edge *> & ripEdges /** Rip Edges */
                );
                /** Edges to rip  @return  Rip Edges 
                 <br>  Created in NX5.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: std::vector<NXOpen::Edge *> GetRipEdges
                (
                );
                /** Verify whether the builder data is valid for creating a Edge Rip or not.
                             <br> 
                                 If the Builder data is valid, returned value shall be 0

                             <br> 
                         @return  Data Validity Flag.
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: int ValidateBuilderData
                (
                );
                /**Returns  whether the system width should be used.  If true, edge rip will be created with the system default rip width. 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : None */
                public: bool UseSystemWidth
                (
                );
                /**Sets  whether the system width should be used.  If true, edge rip will be created with the system default rip width. 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetUseSystemWidth
                (
                    bool useSystemWidth /** usesystemwidth */ 
                );
                /**Returns  the rip width. This only applies if @link NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth @endlink  is set to false. 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * Width
                (
                );
                /**Returns  whether sharp corners should be blended. If true, blends will be applied at sharp corners with radius specified by @link NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendRadius NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendRadius @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendRadius NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendRadius @endlink . 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : None */
                public: bool BlendSharpCorners
                (
                );
                /**Sets  whether sharp corners should be blended. If true, blends will be applied at sharp corners with radius specified by @link NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendRadius NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendRadius @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendRadius NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendRadius @endlink . 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetBlendSharpCorners
                (
                    bool blendSharpCorners /** blendsharpcorners */ 
                );
                /**Returns  the blend radius. This only applies if @link NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendSharpCorners NXOpen::Features::SheetMetal::EdgeRipBuilder::BlendSharpCorners @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendSharpCorners NXOpen::Features::SheetMetal::EdgeRipBuilder::SetBlendSharpCorners @endlink  is set to true. 
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * BlendRadius
                (
                );
                /**Returns  the end cap shape type. This only applies if @link NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth @endlink  is set to false.
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsSquare NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsSquare@endlink  for square end caps.
                                Specify @link NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsRound NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsRound@endlink  for rounded end caps.
                             <br> 
                        
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptions EndCapShape
                (
                );
                /**Sets  the end cap shape type. This only applies if @link NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::UseSystemWidth @endlink and @link NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth NXOpen::Features::SheetMetal::EdgeRipBuilder::SetUseSystemWidth @endlink  is set to false.
                             <br> 
                                Specify @link NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsSquare NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsSquare@endlink  for square end caps.
                                Specify @link NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsRound NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptionsRound@endlink  for rounded end caps.
                             <br> 
                        
                 <br>  Created in NX12.0.2.  <br>  
                 <br> License requirements : nx_sheet_metal ("NX Sheet Metal") OR nx_flexible_pcb ("NX Flexible PCB") */
                public: void SetEndCapShape
                (
                    NXOpen::Features::SheetMetal::EdgeRipBuilder::EndCapShapeOptions endCapShape /** endcapshape */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
