#ifndef NXOpen_FEATURES_AERORIBBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_AERORIBBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_AeroRibBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/GeometricUtilities_CurveLengthBuilder.hxx>
#include <NXOpen/GeometricUtilities_OnPathDimensionBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class AeroRibBuilder;
    }
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class BooleanOperation;
    }
    namespace GeometricUtilities
    {
        class CurveLengthBuilder;
    }
    namespace GeometricUtilities
    {
        class OnPathDimensionBuilder;
    }
    namespace GeometricUtilities
    {
        class ProjectionOptions;
    }
    class Plane;
    class ScCollector;
    class Section;
    namespace Features
    {
        class _AeroRibBuilderBuilder;
        class AeroRibBuilderImpl;
        /**
            Represents a @link NXOpen::Features::AeroRib NXOpen::Features::AeroRib@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::AeroCollection::CreateAeroRibBuilder  NXOpen::Features::AeroCollection::CreateAeroRibBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        AlignRefType0 </td> <td> 
         
        None </td> </tr> 

        <tr><td> 
         
        AlignRefType1 </td> <td> 
         
        None </td> </tr> 

        <tr><td> 
         
        BooleanOperation.Type </td> <td> 
         
        Create </td> </tr> 

        <tr><td> 
         
        CurveLength.EndOffset0.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        CurveLength.EndOffset1.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        CurveLength.EndType0 </td> <td> 
         
        Value </td> </tr> 

        <tr><td> 
         
        CurveLength.EndType1 </td> <td> 
         
        Value </td> </tr> 

        <tr><td> 
         
        GuideObjectType </td> <td> 
         
        Face </td> </tr> 

        <tr><td> 
         
        Height.Value </td> <td> 
         
        25 (millimeters part), 1 (inches part) </td> </tr> 

        <tr><td> 
         
        HeightDimensionType </td> <td> 
         
        Simple </td> </tr> 

        <tr><td> 
         
        HeightOffset.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        Limit1Offset.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        Limit1Type </td> <td> 
         
        FromGuideCurve </td> </tr> 

        <tr><td> 
         
        Limit2Offset.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        Limit2Type </td> <td> 
         
        FromGuideCurve </td> </tr> 

        <tr><td> 
         
        ReverseHeightOffsetDirection </td> <td> 
         
        False </td> </tr> 

        <tr><td> 
         
        Thickness.Value </td> <td> 
         
        2 (millimeters part), 0.1 (inches part) </td> </tr> 

        <tr><td> 
         
        ThicknessDimensionType </td> <td> 
         
        Symmetric </td> </tr> 

        </table>  

         <br>  Created in NX10.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  AeroRibBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** This attribute represents the Guide Object types */
            public: enum GuideObjectTypes
            {
                GuideObjectTypesFace/** Guide object is face */,
                GuideObjectTypesDatumPlane/** Guide object is datum plane */,
                GuideObjectTypesCurve/** Guide object is curve */
            };

            /** This attribute represents the Rib Form */
            public: enum RibForms
            {
                RibFormsNormalToSkin/** Rib form normal to skin */,
                RibFormsAlignWithGuideFace/** Rib form align with guide face */
            };

            /** This attribute represents the options for height dimension */
            public: enum HeightDimensionOptions
            {
                HeightDimensionOptionsSimple/** simple */ ,
                HeightDimensionOptionsSymmetric/** symmetric */ 
            };

            /** This attribute represents the limit object types */
            public: enum LimitObjectTypes
            {
                LimitObjectTypesFromGuideCurve/** from guide curve */ ,
                LimitObjectTypesFromSelected/** from selected */ 
            };

            /** This attribute represents the options for thickness dimension */
            public: enum ThicknessDimensionOptions
            {
                ThicknessDimensionOptionsSimple/** simple */ ,
                ThicknessDimensionOptionsSymmetric/** symmetric */ 
            };

            /** This attribute represents the options for on path dimension */
            public: enum PointOption
            {
                PointOptionArcLength/** arc length */ ,
                PointOptionPercentArcLength/** percent arc length */ ,
                PointOptionParameterArcLength/** parameter arc length */ ,
                PointOptionThroughPoint/** through point */ 
            };

            /** This attribute represents align end type */
            public: enum AlignReferenceType
            {
                AlignReferenceTypeNone/** none */ ,
                AlignReferenceTypeLengthFace/** length face */ ,
                AlignReferenceTypeSkin/** skin */ ,
                AlignReferenceTypeGuideFace/** guide face */ 
            };

            private: AeroRibBuilderImpl * m_aeroribbuilder_impl;
            private: friend class  _AeroRibBuilderBuilder;
            protected: AeroRibBuilder();
            public: ~AeroRibBuilder();
            /**Returns  the skin face collector 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * SkinFaceCollector
            (
            );
            /**Returns  the guide object type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::GuideObjectTypes GuideObjectType
            (
            );
            /**Sets  the guide object type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetGuideObjectType
            (
                NXOpen::Features::AeroRibBuilder::GuideObjectTypes guideObjectType /** guideobjecttype */ 
            );
            /**Returns  the guide faces 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * GuideFaces
            (
            );
            /**Returns  the plane 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Plane * Plane
            (
            );
            /**Sets  the plane 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetPlane
            (
                NXOpen::Plane * plane /** plane */ 
            );
            /**Returns  the section 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Section * Section
            (
            );
            /**Returns  the project direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ProjectionOptions * ProjectDirection
            (
            );
            /**Returns  the rib form 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::RibForms RibForm
            (
            );
            /**Sets  the rib form 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void SetRibForm
            (
                NXOpen::Features::AeroRibBuilder::RibForms ribForm /** ribform */ 
            );
            /**Returns  the height dimension type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::HeightDimensionOptions HeightDimensionType
            (
            );
            /**Sets  the height dimension type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetHeightDimensionType
            (
                NXOpen::Features::AeroRibBuilder::HeightDimensionOptions heightDimensionType /** heightdimensiontype */ 
            );
            /**Returns  the height 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Height
            (
            );
            /**Returns  the reverse height direction flag. Indicates whether the height direction has been flipped from its initial inferred direction 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseHeightDirection
            (
            );
            /**Sets  the reverse height direction flag. Indicates whether the height direction has been flipped from its initial inferred direction 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseHeightDirection
            (
                bool reverseHeightDirection /** reverseheightdirection */ 
            );
            /**Returns  the height offset 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * HeightOffset
            (
            );
            /**Returns  the reverse height offset direction flag. Indicates whether the heightOffset direction has been flipped from its initial inferred direction 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseHeightOffsetDirection
            (
            );
            /**Sets  the reverse height offset direction flag. Indicates whether the heightOffset direction has been flipped from its initial inferred direction 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseHeightOffsetDirection
            (
                bool reverseHeightOffsetDirection /** reverseheightoffsetdirection */ 
            );
            /**Returns  the limit1 type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::LimitObjectTypes Limit1Type
            (
            );
            /**Sets  the limit1 type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetLimit1Type
            (
                NXOpen::Features::AeroRibBuilder::LimitObjectTypes limit1Type /** limit1type */ 
            );
            /**Returns  the limit1 point 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::OnPathDimensionBuilder * Limit1Point
            (
            );
            /**Returns  the flag of whether limit1 measure expression used 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool IsLimit1MeasureExpressionUsed
            (
            );
            /**Sets  the flag of whether limit1 measure expression used 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void SetLimit1MeasureExpressionUsed
            (
                bool isLimit1MeasureExpressionUsed /** islimit1measureexpressionused */ 
            );
            /**Returns  the limit1 selection 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * Limit1Selection
            (
            );
            /**Returns  the limit1 offset 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Limit1Offset
            (
            );
            /**Returns  the reverse limit1 offset direction flag. Indicates whether the limit1 offset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseLimit1OffsetDirection
            (
            );
            /**Sets  the reverse limit1 offset direction flag. Indicates whether the limit1 offset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseLimit1OffsetDirection
            (
                bool reverseLimit1OffsetDirection /** reverselimit1offsetdirection */ 
            );
            /**Returns  the limit2 type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::LimitObjectTypes Limit2Type
            (
            );
            /**Sets  the limit2 type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetLimit2Type
            (
                NXOpen::Features::AeroRibBuilder::LimitObjectTypes limit2Type /** limit2type */ 
            );
            /**Returns  the limit2 point 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::OnPathDimensionBuilder * Limit2Point
            (
            );
            /**Returns  the flag of whether limit2 measure expression used 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool IsLimit2MeasureExpressionUsed
            (
            );
            /**Sets  the flag of whether limit2 measure expression used 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: void SetLimit2MeasureExpressionUsed
            (
                bool isLimit2MeasureExpressionUsed /** islimit2measureexpressionused */ 
            );
            /**Returns  the limit2 selection 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * Limit2Selection
            (
            );
            /**Returns  the limit2 offset 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Limit2Offset
            (
            );
            /**Returns  the reverse limit2 offset direction flag. Indicates whether the limit2 offset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseLimit2OffsetDirection
            (
            );
            /**Sets  the reverse limit2 offset direction flag. Indicates whether the limit2 offset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseLimit2OffsetDirection
            (
                bool reverseLimit2OffsetDirection /** reverselimit2offsetdirection */ 
            );
            /**Returns  the thickness dimension type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::ThicknessDimensionOptions ThicknessDimensionType
            (
            );
            /**Sets  the thickness dimension type 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetThicknessDimensionType
            (
                NXOpen::Features::AeroRibBuilder::ThicknessDimensionOptions thicknessDimensionType /** thicknessdimensiontype */ 
            );
            /**Returns  the thickness 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Thickness
            (
            );
            /**Returns  the reverse thickness direction flag. Indicates whether the thickness direction has been flipped from its initial inferred direction 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseThicknessDirection
            (
            );
            /**Sets  the reverse thickness direction flag. Indicates whether the thickness direction has been flipped from its initial inferred direction 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseThicknessDirection
            (
                bool reverseThicknessDirection /** reversethicknessdirection */ 
            );
            /**Returns  the thicknessOffset 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * ThicknessOffset
            (
            );
            /**Returns  the reverse thicknessOffset direction flag. Indicates whether the thicknessOffset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseThicknessOffsetDirection
            (
            );
            /**Sets  the reverse thicknessOffset direction flag. Indicates whether the thicknessOffset direction has been flipped from its initial inferred direction 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_aero_design (" NX Aero Design") */
            public: void SetReverseThicknessOffsetDirection
            (
                bool reverseThicknessOffsetDirection /** reversethicknessoffsetdirection */ 
            );
            /**Returns  the boolean operation 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::BooleanOperation * BooleanOperation
            (
            );
            /**Returns  the curve length builder
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::CurveLengthBuilder * CurveLength
            (
            );
            /**Returns  the align ref type0 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::AlignReferenceType AlignRefType0
            (
            );
            /**Sets  the align ref type0 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: void SetAlignRefType0
            (
                NXOpen::Features::AeroRibBuilder::AlignReferenceType alignRefType0 /** alignreftype0 */ 
            );
            /**Returns  the align ref type1 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::AeroRibBuilder::AlignReferenceType AlignRefType1
            (
            );
            /**Sets  the align ref type1 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: void SetAlignRefType1
            (
                NXOpen::Features::AeroRibBuilder::AlignReferenceType alignRefType1 /** alignreftype1 */ 
            );
            /** Construct guide curves 
             <br>  Created in NX12.0.0.  <br>  
             <br> License requirements : None */
            public: void ConstructGuidecurves
            (
                bool deleteGuideCurves /** deleteguidecurves */ ,
                bool showGuideCurves /** showguidecurves */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
