#ifndef NXOpen_CADCAEPREP_IDEALIZEDBEAMMANAGER_HXX_INCLUDED
#define NXOpen_CADCAEPREP_IDEALIZEDBEAMMANAGER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CADCAEPrep_IdealizedBeamManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionBar.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionBox.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionChan.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionHexa.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionI.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionL.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionRod.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionSketch.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionT.hxx>
#include <NXOpen/CADCAEPrep_BeamSectionTube.hxx>
#include <NXOpen/CADCAEPrep_IBeamSection.hxx>
#include <NXOpen/CADCAEPrep_IdealizedBeam.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_cadcaeprep_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CADCAEPrep
    {
        class IdealizedBeamManager;
    }
    class Part;
    namespace CADCAEPrep
    {
        class BeamSectionBar;
    }
    namespace CADCAEPrep
    {
        class BeamSectionBox;
    }
    namespace CADCAEPrep
    {
        class BeamSectionChan;
    }
    namespace CADCAEPrep
    {
        class BeamSectionHexa;
    }
    namespace CADCAEPrep
    {
        class BeamSectionI;
    }
    namespace CADCAEPrep
    {
        class BeamSectionL;
    }
    namespace CADCAEPrep
    {
        class BeamSectionRod;
    }
    namespace CADCAEPrep
    {
        class BeamSectionSketch;
    }
    namespace CADCAEPrep
    {
        class BeamSectionT;
    }
    namespace CADCAEPrep
    {
        class BeamSectionTube;
    }
    namespace CADCAEPrep
    {
        class IBeamSection;
    }
    namespace CADCAEPrep
    {
        class IBeamSectionCollection;
    }
    namespace CADCAEPrep
    {
        class IdealizedBeam;
    }
    namespace CADCAEPrep
    {
        class IdealizedBeamCollection;
    }
    class Curve;
    class Sketch;
    namespace CADCAEPrep
    {
        class IdealizedBeamManagerImpl;
        /** The object containing the information about the IdealizedBeamManager to be modified. <br> Use @link Part::IdealizedBeamManager Part::IdealizedBeamManager@endlink  to get the instance of this class.  <br> 
         <br>  Created in NX1953.0.0.  <br>  
        */
        class NXOPENCPP_CADCAEPREPEXPORT  IdealizedBeamManager
        {
            private: IdealizedBeamManagerImpl * m_idealizedbeammanager_impl;
            private: NXOpen::Part* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit IdealizedBeamManager(NXOpen::Part *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~IdealizedBeamManager();
            /** Get section by name  @return  the section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::IBeamSection * GetSection
            (
                const NXString & sectionName /** sectionname */ 
            );
            /** Get section by name  @return  the section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::IBeamSection * GetSection
            (
                const char * sectionName /** sectionname */ 
            );
            /** Add a beam section Rod @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionRod * AddBeamSectionRod
            (
                const NXString & sectionName /** sectionname */ ,
                double radius /** radius */ 
            );
            /** Add a beam section Rod @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionRod * AddBeamSectionRod
            (
                const char * sectionName /** sectionname */ ,
                double radius /** radius */ 
            );
            /** Add a beam section Box @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionBox * AddBeamSectionBox
            (
                const NXString & sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double thicknessTopBottom /** thicknesstopbottom */ ,
                double thicknessSides /** thicknesssides */ 
            );
            /** Add a beam section Box @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionBox * AddBeamSectionBox
            (
                const char * sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double thicknessTopBottom /** thicknesstopbottom */ ,
                double thicknessSides /** thicknesssides */ 
            );
            /** Add a beam section Chan @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionChan * AddBeamSectionChan
            (
                const NXString & sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double flangeThickness /** flangethickness */ ,
                double webThickness /** webthickness */ 
            );
            /** Add a beam section Chan @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionChan * AddBeamSectionChan
            (
                const char * sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double flangeThickness /** flangethickness */ ,
                double webThickness /** webthickness */ 
            );
            /** Add a beam section Hexa @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionHexa * AddBeamSectionHexa
            (
                const NXString & sectionName /** sectionname */ ,
                double sideWidth /** sidewidth */ ,
                double overallWidth /** overallwidth */ ,
                double height /** height */ 
            );
            /** Add a beam section Hexa @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionHexa * AddBeamSectionHexa
            (
                const char * sectionName /** sectionname */ ,
                double sideWidth /** sidewidth */ ,
                double overallWidth /** overallwidth */ ,
                double height /** height */ 
            );
            /** Add a beam section T @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionT * AddBeamSectionT
            (
                const NXString & sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double flangeThickness /** flangethickness */ ,
                double webThickness /** webthickness */ 
            );
            /** Add a beam section T @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionT * AddBeamSectionT
            (
                const char * sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ ,
                double flangeThickness /** flangethickness */ ,
                double webThickness /** webthickness */ 
            );
            /** Add a beam section Bar  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionBar * AddBeamSectionBar
            (
                const NXString & sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ 
            );
            /** Add a beam section Bar  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionBar * AddBeamSectionBar
            (
                const char * sectionName /** sectionname */ ,
                double width /** width */ ,
                double height /** height */ 
            );
            /** Add a beam section I  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionI * AddBeamSectionI
            (
                const NXString & sectionName /** sectionname */ ,
                double height /** height */ ,
                double widthBottomFlange /** widthbottomflange */ ,
                double widthTopFlange /** widthtopflange */ ,
                double thicknessWeb /** thicknessweb */ ,
                double thicknessBottomFlange /** thicknessbottomflange */ ,
                double thicknessTopFlange /** thicknesstopflange */ 
            );
            /** Add a beam section I  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionI * AddBeamSectionI
            (
                const char * sectionName /** sectionname */ ,
                double height /** height */ ,
                double widthBottomFlange /** widthbottomflange */ ,
                double widthTopFlange /** widthtopflange */ ,
                double thicknessWeb /** thicknessweb */ ,
                double thicknessBottomFlange /** thicknessbottomflange */ ,
                double thicknessTopFlange /** thicknesstopflange */ 
            );
            /** Add a beam section L  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionL * AddBeamSectionL
            (
                const NXString & sectionName /** sectionname */ ,
                double lengthVertical /** lengthvertical */ ,
                double lengthHorizontal /** lengthhorizontal */ ,
                double thicknessVertical /** thicknessvertical */ ,
                double thicknessHorizontal /** thicknesshorizontal */ 
            );
            /** Add a beam section L  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionL * AddBeamSectionL
            (
                const char * sectionName /** sectionname */ ,
                double lengthVertical /** lengthvertical */ ,
                double lengthHorizontal /** lengthhorizontal */ ,
                double thicknessVertical /** thicknessvertical */ ,
                double thicknessHorizontal /** thicknesshorizontal */ 
            );
            /** Add a beam section Tube  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionTube * AddBeamSectionTube
            (
                const NXString & sectionName /** sectionname */ ,
                double radiusOutside /** radiusoutside */ ,
                double radiusInside /** radiusinside */ 
            );
            /** Add a beam section Tube  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionTube * AddBeamSectionTube
            (
                const char * sectionName /** sectionname */ ,
                double radiusOutside /** radiusoutside */ ,
                double radiusInside /** radiusinside */ 
            );
            /** Add a beam section Sketch  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::BeamSectionSketch * AddBeamSectionSketch
            (
                const NXString & sectionName /** sectionname */ ,
                NXOpen::Sketch * sketchTag /** sketchtag */ 
            );
            /** Add a beam section Sketch  @return  the new section 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            NXOpen::CADCAEPrep::BeamSectionSketch * AddBeamSectionSketch
            (
                const char * sectionName /** sectionname */ ,
                NXOpen::Sketch * sketchTag /** sketchtag */ 
            );
            /** Add an idealized beam  @return  the new idealized beam 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::IdealizedBeam * AddIdealizedBeam
            (
                NXOpen::Curve * curve /** the associated curve  */
            );
            /** Get idealized beam from curve  @return  the idealized beam 
             <br>  Created in NX1953.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CADCAEPrep::IdealizedBeam * GetIdealizedBeam
            (
                NXOpen::Curve * curve /** the curve*/
            );


            /** Returns the @link NXOpen::CADCAEPrep::IBeamSectionCollection NXOpen::CADCAEPrep::IBeamSectionCollection@endlink  belonging to this 
             <br>  Created in NX1953.0.0.  <br>  
            */
            public: NXOpen::CADCAEPrep::IBeamSectionCollection *IBeamSectionCollection();
            /** Returns the @link NXOpen::CADCAEPrep::IdealizedBeamCollection NXOpen::CADCAEPrep::IdealizedBeamCollection@endlink  belonging to this 
             <br>  Created in NX1953.0.0.  <br>  
            */
            public: NXOpen::CADCAEPrep::IdealizedBeamCollection *IdealizedBeamCollection();
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
