#ifndef NXOpen_FEATURES_BLOCKFEATUREBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_BLOCKFEATUREBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_BlockFeatureBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class BlockFeatureBuilder;
    }
    class Body;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        class _BlockFeatureBuilderBuilder;
        /**
        Represents a block feature builder.
         <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateBlockFeatureBuilder Features::FeatureCollection::CreateBlockFeatureBuilder@endlink  <br> */
        class NXOPENCPPEXPORT BlockFeatureBuilder : public Features::FeatureBuilder
        {
            private: friend class  _BlockFeatureBuilderBuilder;
            protected: BlockFeatureBuilder();
            /**Returns  the expression representing the block length.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Expression * Length
            (
            );
            /**Returns  the expression representing the block width.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Expression * Width
            (
            );
            /**Returns  the expression representing the block height.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Expression * Height
            (
            );
            /**Returns  the point representing the block origin.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Point3d Origin
            (
            );
            /** Gets the orientation (x and y axes) of the block.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void GetOrientation
            (
                NXOpen::Vector3d* x_axis /** */,
                NXOpen::Vector3d* y_axis /** */
            );
            /**Returns  the boolean operation for the block  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Features::Feature::BooleanType BooleanType
            (
            );
            /**Returns  the boolean operation for the block  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: NXOpen::Body * Target
            (
            );
            /** The expression representing the block length.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLength
            (
                const NXString & length /**   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** The expression representing the block width.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetWidth
            (
                const NXString & width /**   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** The expression representing the block height.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetHeight
            (
                const NXString & height /**   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /**Sets  the point representing the block origin.  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetOrigin
            (
                const NXOpen::Point3d & origin /** */
            );
            /** Sets the orientation for the block  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetOrientation
            (
                const NXOpen::Vector3d & x_axis /** */,
                const NXOpen::Vector3d & y_axis /** */
            );
            /**Sets  the boolean operation for the block  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetBooleanType
            (
                NXOpen::Features::Feature::BooleanType boolean_type /** */
            );
            /**Sets  the boolean operation for the block  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTarget
            (
                NXOpen::Body * target /** */
            );
            /** Create a block by setting the origin and the block length, width, and height. The origin of the block
                    is specified by the input origin point in absolute coordinates. The orientation of the block is along 
                    the x, y, and z axes of the WCS.  <br> License requirements : solid_modeling ("SOLIDS MODELING"), features_modeling ("FEATURES MODELING") */
            public: void SetOriginAndLengths
            (
                const NXOpen::Point3d & origin_point /** Block origin point */,
                const NXString & length_expression /** Block length in the WCS x direction   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & width_expression /** Block width in the WCS y direction   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & height_expression /** Block height in the WCS z direction   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Create a block by setting the block height and two diagonal points in the WCS x-y plane. The orientation
                    of the block is along the x, y, and z axes of the WCS.  <br> License requirements : solid_modeling ("SOLIDS MODELING"), features_modeling ("FEATURES MODELING") */
            public: void SetTwoPointsAndHeight
            (
                const NXOpen::Point3d & origin_point /** Block origin point */,
                const NXOpen::Point3d & corner_point /** Block 2d corner point, diagonal in WCS x-y plane from the block origin point. */,
                const NXString & height_expression /** Block height in the WCS z direction   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Create a block by setting two diagonal points, one at the block origin and one at the opposite corner point.
                    The orientation of the block is along the x, y, and z axes of the WCS.  <br> License requirements : solid_modeling ("SOLIDS MODELING"), features_modeling ("FEATURES MODELING") */
            public: void SetTwoDiagonalPoints
            (
                const NXOpen::Point3d & origin_point /** Block origin point */,
                const NXOpen::Point3d & corner_point /** Block corner point, diagonal from the block origin point */
            );
            /** Set the boolean operation for creating the block and the boolean operation target body  <br> License requirements : solid_modeling ("SOLIDS MODELING"), features_modeling ("FEATURES MODELING") */
            public: void SetBooleanOperationAndTarget
            (
                NXOpen::Features::Feature::BooleanType boolean_operation /** Type of boolean operation. */,
                NXOpen::Body * target_body /** Target body for boolean operation. 
                                                                    Set to a null reference (Nothing in Visual Basic) 
                                                                    for a boolean create operation. */
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
