#ifndef NXOpen_FEATURES_FACEBLENDBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_FACEBLENDBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_FaceBlendBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class FaceBlendBuilder;
    }
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class CircularCrossSection;
    }
    namespace GeometricUtilities
    {
        class ConicCrossSection;
    }
    class ISurface;
    class Plane;
    class Point;
    class ScCollector;
    class Section;
    namespace Features
    {
        class _FaceBlendBuilderBuilder;
        /** Represents a face blend builder. 
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateFaceBlendBuilder Features::FeatureCollection::CreateFaceBlendBuilder@endlink  <br> */
        class NXOPENCPPEXPORT FaceBlendBuilder : public Features::FeatureBuilder
        {
            /** This enum represents the Face Blend types */
            public: enum Type
            {
                TypeRollingBall/** */,
                TypeSwept/** */
            };

            /** This enum represents the Cross section types */
            public: enum CrossSectionOption
            {
                CrossSectionOptionCircular/** */,
                CrossSectionOptionConic/** */
            };

            /** This enum represents the Trimming options for Face Blend */
            public: enum TrimmingMethod
            {
                TrimmingMethodToAllFaces/** Trim to all faces */,
                TrimmingMethodShort/** Trim short */,
                TrimmingMethodLong/** Trim long */,
                TrimmingMethodNone/** No trim */
            };

            /** This enum represents the overflow options */
            public: enum OverflowMethod
            {
                OverflowMethodNone/** No overflow option */,
                OverflowMethodNotch/** Notch or Maintain Blend And Move Sharp Edges option */
            };

            /** This enum represents the rho types */
            public: enum RhoMethod
            {
                RhoMethodAbsolute/** Absolute (NX) rho type */,
                RhoMethodRelative/** Relative (I-deas) rho type */
            };

            private: friend class  _FaceBlendBuilderBuilder;
            protected: FaceBlendBuilder();
            /**Sets  the first face collector
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetFirstFaceCollector
            (
                NXOpen::ScCollector * collector /** */
            );
            /**Returns  the first face collector
                 <br> License requirements : None */
            public: NXOpen::ScCollector * FirstFaceCollector
            (
            );
            /**Sets  the first face set normal reversal flag
                 <br> License requirements : None */
            public: void SetReverseFirstFaceNormal
            (
                bool flip_flag /** */
            );
            /**Returns  the first face set normal reversal flag
                 <br> License requirements : None */
            public: bool ReverseFirstFaceNormal
            (
            );
            /**Sets  the second face collector
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSecondFaceCollector
            (
                NXOpen::ScCollector * collector /** */
            );
            /**Returns  the second face collector
                 <br> License requirements : None */
            public: NXOpen::ScCollector * SecondFaceCollector
            (
            );
            /**Sets  the second face set normal reversal flag
                 <br> License requirements : None */
            public: void SetReverseSecondFaceNormal
            (
                bool flip_flag /** */
            );
            /**Returns  the second face set normal reversal flag
                 <br> License requirements : None */
            public: bool ReverseSecondFaceNormal
            (
            );
            /**Returns  the face blend circular section
                 <br> License requirements : None */
            public: NXOpen::GeometricUtilities::CircularCrossSection * CircularCrossSection
            (
            );
            /**Returns  the face blend conic section
                 <br> License requirements : None */
            public: NXOpen::GeometricUtilities::ConicCrossSection * ConicCrossSection
            (
            );
            /**Returns  the spine for face blend
                 <br> License requirements : None */
            public: NXOpen::Section * Spine
            (
            );
            /**Sets  the spine for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSpine
            (
                NXOpen::Section * spine /** */
            );
            /**Returns  the cliff edge collector for face blend
                 <br> License requirements : None */
            public: NXOpen::ScCollector * CoincidentEdgeCollector
            (
            );
            /**Sets  the cliff edge collector for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetCoincidentEdgeCollector
            (
                NXOpen::ScCollector * collector /** */
            );
            /**Returns  the tangency collector of edges or/and curves for face blend
                 <br> License requirements : None */
            public: NXOpen::ScCollector * TangencyCollector
            (
            );
            /**Sets  the tangency collector of edges or/and curves for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTangencyCollector
            (
                NXOpen::ScCollector * collector /** */
            );
            /**Returns  the tangency object for face blend.
                 <br> License requirements : None */
            public: NXOpen::ISurface * TangentSurface
            (
            );
            /**Sets  the tangency object for face blend.
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTangentSurface
            (
                NXOpen::ISurface * object /** */
            );
            /**Sets  the third face set normal reversal flag
                 <br> License requirements : None */
            public: void SetReverseThirdFaceNormal
            (
                bool flip_flag /** */
            );
            /**Returns  the third face set normal reversal flag
                 <br> License requirements : None */
            public: bool ReverseThirdFaceNormal
            (
            );
            /**Returns  the face blend help point
                 <br> License requirements : None */
            public: NXOpen::Point * HelpPoint
            (
            );
            /**Sets  the face blend help point
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetHelpPoint
            (
                NXOpen::Point * help_point /** */
            );
            /** This function is to get limit planes for a face blend feature.
                 <br> License requirements : None */
            public: void GetLimitPlanes
            (
                NXOpen::Plane ** start_limit_plane /** Start limit plane */,
                NXOpen::Plane ** end_limit_plane /** End limit plane */
            );
            /** This function is to set limit planes for a face blend feature.
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetLimitPlanes
            (
                NXOpen::Plane * start_limit_plane /** Start limit plane */,
                NXOpen::Plane * end_limit_plane /** End limit plane */
            );
            /**Returns  the trimming option for face blend
                 <br> License requirements : None */
            public: NXOpen::Features::FaceBlendBuilder::TrimmingMethod TrimmingOption
            (
            );
            /**Sets  the trimming option for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTrimmingOption
            (
                NXOpen::Features::FaceBlendBuilder::TrimmingMethod trimming_option /** */
            );
            /**Returns  the option for Trim Input Faces to Blend Faces
                 <br> License requirements : None */
            public: bool TrimInputFacesToBlendFaces
            (
            );
            /**Sets  the option for Trim Input Faces to Blend Faces
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTrimInputFacesToBlendFaces
            (
                bool trim_input_faces_to_blend_faces /** */
            );
            /**Returns  the sew option for face blend
                 <br> License requirements : None */
            public: bool SewAllFaces
            (
            );
            /**Sets  the sew option for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetSewAllFaces
            (
                bool sew_option /** */
            );
            /**Returns  the type for face blend
                 <br> License requirements : None */
            public: NXOpen::Features::FaceBlendBuilder::Type BlendType
            (
            );
            /**Sets  the type for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetBlendType
            (
                NXOpen::Features::FaceBlendBuilder::Type type /** */
            );
            /**Returns  the cross section for face blend
                 <br> License requirements : None */
            public: NXOpen::Features::FaceBlendBuilder::CrossSectionOption CrossSectionType
            (
            );
            /**Sets  the cross section for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetCrossSectionType
            (
                NXOpen::Features::FaceBlendBuilder::CrossSectionOption type /** */
            );
            /**Returns  the option for Add Tangent Faces As Encountered
                 <br> License requirements : None */
            public: bool AddTangentFaces
            (
            );
            /**Sets  the option for Add Tangent Faces As Encountered
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAddTangentFaces
            (
                bool option /** */
            );
            /**Returns  the option for Orient Cross Section By Isoparameter Lines for Swept section type only
                 <br> License requirements : None */
            public: bool IsIsoparameterLineOriented
            (
            );
            /**Sets  the option for Orient Cross Section By Isoparameter Lines for Swept section type only
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetIsoparameterLineOriented
            (
                bool option /** */
            );
            /**Returns  the self-intersections option for face blend
                 <br> License requirements : None */
            public: bool RemoveSelfIntersections
            (
            );
            /**Sets  the self-intersections option for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRemoveSelfIntersections
            (
                bool option /** */
            );
            /**Returns  the projection option for face blend
                 <br> License requirements : None */
            public: bool ProjectToSecondWall
            (
            );
            /**Sets  the projection option for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetProjectToSecondWall
            (
                bool project_to_second_wall /** */
            );
            /**Returns  the overflow option for face blend
                 <br> License requirements : None */
            public: NXOpen::Features::FaceBlendBuilder::OverflowMethod OverflowOption
            (
            );
            /**Sets  the overflow option for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetOverflowOption
            (
                NXOpen::Features::FaceBlendBuilder::OverflowMethod option /** */
            );
            /**Returns  the rho type for face blend
                 <br> License requirements : None */
            public: NXOpen::Features::FaceBlendBuilder::RhoMethod RhoType
            (
            );
            /**Sets  the rho type for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRhoType
            (
                NXOpen::Features::FaceBlendBuilder::RhoMethod rho_method /** */
            );
            /**Returns  the tolerance for face blend
                 <br> License requirements : None */
            public: double Tolerance
            (
            );
            /**Sets  the tolerance for face blend
                 <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTolerance
            (
                double tolerance /** */
            );
            /**Returns  the start parameter or 'from' range for the third face with a three-face blend
                    <br> License requirements : None */
            public: double ThirdFaceStartParameter
            (
            );
            /**Sets  the start parameter or 'from' range for the third face with a three-face blend
                    <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetThirdFaceStartParameter
            (
                double range /** */
            );
            /**Returns  the end paramater or 'to' range for the third face with a three-face blend
                    <br> License requirements : None */
            public: double ThirdFaceEndParameter
            (
            );
            /**Sets  the end paramater or 'to' range for the third face with a three-face blend
                    <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetThirdFaceEndParameter
            (
                double range /** */
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
