#ifndef NXOpen_FACET_STLIMPORTBUILDER_HXX_INCLUDED
#define NXOpen_FACET_STLIMPORTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Facet_STLImportBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Facet_STLImportBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/libnxopencpp_facet_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Facet
    {
        class STLImportBuilder;
    }
    class Builder;
    namespace Facet
    {
        class _STLImportBuilderBuilder;
        class STLImportBuilderImpl;
        /** The STL file import builder  <br> To create a new instance of this class, use @link NXOpen::Facet::FacetedBodyCollection::CreateSTLImportBuilder  NXOpen::Facet::FacetedBodyCollection::CreateSTLImportBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        AngularTolerance </td> <td> 
         
        Medium </td> </tr> 

        <tr><td> 
         
        FacetBodyType </td> <td> 
         
        Nx </td> </tr> 

        <tr><td> 
         
        HideSmoothEdges </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        STLFileUnits </td> <td> 
         
        Millimeters </td> </tr> 

        <tr><td> 
         
        ShowInformationWindow </td> <td> 
         
        0 </td> </tr> 

        </table>  

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_FACETEXPORT  STLImportBuilder : public NXOpen::Builder
        {
            /** The angular tolerance types*/
            public: enum AngularToleranceTypes
            {
                AngularToleranceTypesCoarse/** coarse */ ,
                AngularToleranceTypesMedium/** medium */ ,
                AngularToleranceTypesFine/** fine */ 
            };

            /** The STL file units types */
            public: enum STLFileUnitsTypes
            {
                STLFileUnitsTypesMeters/** meters */ ,
                STLFileUnitsTypesMillimeters/** millimeters */ ,
                STLFileUnitsTypesInches/** inches */ 
            };

            /** These represent the type of body that will get created on importing the STL file */
            public: enum FacetBodyTypes
            {
                FacetBodyTypesNx/** Import To NX Facet Format */,
                FacetBodyTypesJt/** Import to JT format*/,
                FacetBodyTypesPsm/** Import to Facet Brep format*/
            };

            private: STLImportBuilderImpl * m_stlimportbuilder_impl;
            private: friend class  _STLImportBuilderBuilder;
            protected: STLImportBuilder();
            public: ~STLImportBuilder();
            /**Returns  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") */
            public: NXString File
            (
            );
            /**Sets  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") */
            public: void SetFile
            (
                const NXString & filename /** filename */ 
            );
            /**Sets  the STL file  
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR nx_freeform_1 ("basic freeform modeling") */
            void SetFile
            (
                const char * filename /** filename */ 
            );
            /**Returns  the indicator for whether to hide smooth edges 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool HideSmoothEdges
            (
            );
            /**Sets  the indicator for whether to hide smooth edges 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetHideSmoothEdges
            (
                bool hideSmoothEdges /** hidesmoothedges */ 
            );
            /**Returns  the angular tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Facet::STLImportBuilder::AngularToleranceTypes AngularTolerance
            (
            );
            /**Sets  the angular tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetAngularTolerance
            (
                NXOpen::Facet::STLImportBuilder::AngularToleranceTypes angularTolerance /** angulartolerance */ 
            );
            /**Returns  the STL file units 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Facet::STLImportBuilder::STLFileUnitsTypes STLFileUnits
            (
            );
            /**Sets  the STL file units 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetSTLFileUnits
            (
                NXOpen::Facet::STLImportBuilder::STLFileUnitsTypes stlFileUnits /** stlfileunits */ 
            );
            /**Returns  the indicator for whether to show information window 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool ShowInformationWindow
            (
            );
            /**Sets  the indicator for whether to show information window 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetShowInformationWindow
            (
                bool showInformationWindow /** showinformationwindow */ 
            );
            /**Returns  the facet body type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Facet::STLImportBuilder::FacetBodyTypes FacetBodyType
            (
            );
            /**Sets  the facet body type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetFacetBodyType
            (
                NXOpen::Facet::STLImportBuilder::FacetBodyTypes facetBodyType /** facetbodytype */ 
            );

            /// \cond NX_NO_DOC 
            /**Returns  the option to clean up all mesh defects on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool CleanUp
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the option to clean up all mesh defects on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetCleanUp
            (
                bool cleanUp /** cleanup */ 
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Returns  the option to separate disconnected bodies into separate bodies on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool SeparateBodiesForDisconnectedMeshes
            (
            );

            /// \endcond 

            /// \cond NX_NO_DOC 
            /**Sets  the option to separate disconnected bodies into separate bodies on import 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void SetSeparateBodiesForDisconnectedMeshes
            (
                bool separateBodies /** separatebodies */ 
            );

            /// \endcond 
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
