#ifndef NXOpen_FEATURES_NSIDEDSURFACEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_NSIDEDSURFACEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_NSidedSurfaceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_NSidedSurfaceBuilder.hxx>
#include <NXOpen/GeometricUtilities_Continuity.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class NSidedSurfaceBuilder;
    }
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class Continuity;
    }
    class Point;
    class ScCollector;
    class Section;
    class SectionList;
    namespace Features
    {
        class _NSidedSurfaceBuilderBuilder;
        class NSidedSurfaceBuilderImpl;
        /**
            Represents a @link NXOpen::Features::NSidedSurface NXOpen::Features::NSidedSurface@endlink  builder
             <br> To create a new instance of this class, use @link NXOpen::Features::FeatureCollection::CreateNSidedSurfaceBuilder  NXOpen::Features::FeatureCollection::CreateNSidedSurfaceBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        CenterControlFlat.Value </td> <td> 
         
        100 </td> </tr> 

        <tr><td> 
         
        CenterControlTiltX.Value </td> <td> 
         
        50 </td> </tr> 

        <tr><td> 
         
        CenterControlTiltY.Value </td> <td> 
         
        50 </td> </tr> 

        <tr><td> 
         
        CenterControlTrimFlat.Value </td> <td> 
         
        50 </td> </tr> 

        <tr><td> 
         
        CenterControlX.Value </td> <td> 
         
        50 </td> </tr> 

        <tr><td> 
         
        CenterControlY.Value </td> <td> 
         
        50 </td> </tr> 

        <tr><td> 
         
        CenterControlZ.Value </td> <td> 
         
        50 </td> </tr> 

        </table>  

         <br>  Created in NX6.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  NSidedSurfaceBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** the surface type options */
            public: enum SurfaceType
            {
                SurfaceTypeTrimmedPatch/** Trimmed Patch */,
                SurfaceTypeTriangularPatch/** Triangular Patch */
            };

            /** the UV orientation options */
            public: enum UVOrientationType
            {
                UVOrientationTypeSpine/** spine orientation */,
                UVOrientationTypeVector/** vector orientation */,
                UVOrientationTypeArea/** area orientation */
            };

            /** the center control type options */
            public: enum CenterControlType
            {
                CenterControlTypePosition/** position type */,
                CenterControlTypeTilting/** tilting type */
            };

            /** the center control types */
            public: enum CenterControlAxisType
            {
                CenterControlAxisTypeX/** x axis */,
                CenterControlAxisTypeY/** y axis */,
                CenterControlAxisTypeZ/** z axis */,
                CenterControlAxisTypeFlat/** center flat */
            };

            /** the flow direction options */
            public: enum FlowDirectionType
            {
                FlowDirectionTypeNotSpecified/** not specified */,
                FlowDirectionTypePerpendicular/** perpendicular */,
                FlowDirectionTypeIsoUVLine/** uv line */,
                FlowDirectionTypeAdjacentEdges/** adjacent edges */
            };

            private: NSidedSurfaceBuilderImpl * m_nsidedsurfacebuilder_impl;
            private: friend class  _NSidedSurfaceBuilderBuilder;
            protected: NSidedSurfaceBuilder();
            public: ~NSidedSurfaceBuilder();
            /**Returns  the surface type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Features::NSidedSurfaceBuilder::SurfaceType Type
            (
            );
            /**Sets  the surface type 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetType
            (
                NXOpen::Features::NSidedSurfaceBuilder::SurfaceType surfaceType /** surfacetype */ 
            );
            /**Returns  the list of interior curves 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::SectionList * InteriorCurveList
            (
            );
            /**Returns  the outer loop 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Section * OuterLoop
            (
            );
            /**Returns  the UV orientation 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Features::NSidedSurfaceBuilder::UVOrientationType UVOrientation
            (
            );
            /**Sets  the UV orientation 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetUVOrientation
            (
                NXOpen::Features::NSidedSurfaceBuilder::UVOrientationType button /** button */ 
            );
            /**Returns  the trim-to-boundary option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: bool TrimToBoundary
            (
            );
            /**Sets  the trim-to-boundary option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetTrimToBoundary
            (
                bool trimToBoundary /** trimtoboundary */ 
            );
            /**Returns  the merge-faces option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: bool MergeFaces
            (
            );
            /**Sets  the merge-faces option 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetMergeFaces
            (
                bool mergeFaces /** mergefaces */ 
            );
            /**Returns  the position tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: double PositionTolerance
            (
            );
            /**Sets  the position tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetPositionTolerance
            (
                double positionTolerance /** positiontolerance */ 
            );
            /**Returns  the tangent tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: double TangentTolerance
            (
            );
            /**Sets  the tangent tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetTangentTolerance
            (
                double tangentTolerance /** tangenttolerance */ 
            );
            /**Returns  the curvature tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: double CurvatureTolerance
            (
            );
            /**Sets  the curvature tolerance 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetCurvatureTolerance
            (
                double curvatureTolerance /** curvaturetolerance */ 
            );
            /**Returns  the constraint faces 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::ScCollector * ConstraintFaces
            (
            );
            /**Returns  the spine curve. This is used only if UVOrientation is UVOrientationType.Spine 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Section * SpineCurve
            (
            );
            /**Returns  the orientation vector. This is used only if UVOrientation is UVOrientationType.Vector 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Direction * OrientationVector
            (
            );
            /**Sets  the orientation vector. This is used only if UVOrientation is UVOrientationType.Vector 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetOrientationVector
            (
                NXOpen::Direction * orientationVector /** orientationvector */ 
            );
            /**Returns  the first rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Point * RectanglePointFirst
            (
            );
            /**Sets  the first rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetRectanglePointFirst
            (
                NXOpen::Point * firstPoint /** firstpoint */ 
            );
            /**Returns  the second rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Point * RectanglePointSecond
            (
            );
            /**Sets  the second rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetRectanglePointSecond
            (
                NXOpen::Point * secondPoint /** secondpoint */ 
            );
            /**Returns  the flow direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Features::NSidedSurfaceBuilder::FlowDirectionType FlowDirection
            (
            );
            /**Sets  the flow direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetFlowDirection
            (
                NXOpen::Features::NSidedSurfaceBuilder::FlowDirectionType button /** button */ 
            );
            /**Returns  the continuity 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::GeometricUtilities::Continuity * Continuity
            (
            );
            /**Returns  the center control x direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlX
            (
            );
            /**Returns  the center control y direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlY
            (
            );
            /**Returns  the center control z direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlZ
            (
            );
            /**Returns  the center control tilt x direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlTiltX
            (
            );
            /**Returns  the center control tilt y direction 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlTiltY
            (
            );
            /**Returns  the center control flat 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlFlat
            (
            );
            /**Returns  the center control flat for trimming 
             <br>  Created in NX6.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Expression * CenterControlTrimFlat
            (
            );
            /**Returns  the third rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: NXOpen::Point * RectanglePointThird
            (
            );
            /**Sets  the third rectangle point. This is used only if UVOrientation is UVOrientationType.Area 
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : features_modeling ("FEATURES MODELING"), nx_freeform_1 ("basic freeform modeling") */
            public: void SetRectanglePointThird
            (
                NXOpen::Point * thirdPoint /** thirdpoint */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
