#ifndef NXOpen_FEATURES_SHIPDESIGN_SHIPENDCUTBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHIPDESIGN_SHIPENDCUTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_ShipEndCutBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/EndCutBlockBuilder.hxx>
#include <NXOpen/Features_ShipDesign_ShipEndCutBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class ShipEndCutBuilder;
        }
    }
    class CoordinateSystem;
    class EndCutBlockBuilder;
    namespace Features
    {
        class FeatureBuilder;
    }
    class SelectTaggedObject;
    namespace Features
    {
        namespace ShipDesign
        {
            class _ShipEndCutBuilderBuilder;
            class ShipEndCutBuilderImpl;
            /**
                    Represents a @link NXOpen::Features::ShipDesign::ShipEndCut NXOpen::Features::ShipDesign::ShipEndCut@endlink  builder
                     <br> To create a new instance of this class, use @link NXOpen::Features::ShipCollection::CreateShipEndCutBuilder  NXOpen::Features::ShipCollection::CreateShipEndCutBuilder @endlink  <br> 
            Default values.
            <table border="1"> 
             
            <tr><th> 
            Property</th>  <th> 
            Value</th> </tr>
            <tr><td> 
             
            EndCutBlock.Angle.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.Offset.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp1.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp10.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp11.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp12.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp2.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp3.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp4.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp5.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp6.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp7.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp8.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Exp9.Value </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.SketchBlock.Sketches </td> <td> 
             
            EndCut1 </td> </tr> 

            <tr><td> 
             
            EndCutBlock.TaperType </td> <td> 
             
            Trim </td> </tr> 

            </table>  

             <br>  Created in NX7.5.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  ShipEndCutBuilder : public NXOpen::Features::FeatureBuilder
            {
                /** available methods used to place a cutout object
                            */
                public: enum CreationMethod
                {
                    CreationMethodFaceEdge/** 1 face and 1 edge are used to place this endcut */,
                    CreationMethodSpecifyCSYS/** a csys is used to place this endcut */
                };

                private: ShipEndCutBuilderImpl * m_shipendcutbuilder_impl;
                private: friend class  _ShipEndCutBuilderBuilder;
                protected: ShipEndCutBuilder();
                public: ~ShipEndCutBuilder();
                /**Returns  the placement type 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::ShipDesign::ShipEndCutBuilder::CreationMethod PlacementType
                (
                );
                /**Sets  the placement type 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_ship_concept ("Ship Concept") */
                public: void SetPlacementType
                (
                    NXOpen::Features::ShipDesign::ShipEndCutBuilder::CreationMethod placementType /** placementtype */ 
                );
                /**Returns  the select target face 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectTargetFace
                (
                );
                /**Returns  the select edge 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectEdge
                (
                );
                /**Returns  the coord system 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::CoordinateSystem * CoordSystem
                (
                );
                /**Sets  the coord system 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : nx_ship_concept ("Ship Concept") */
                public: void SetCoordSystem
                (
                    NXOpen::CoordinateSystem * coordSystem /** coordsystem */ 
                );
                /**Returns  the select csysface 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectTaggedObject * SelectCSYSFace
                (
                );
                /**Returns  the end cut block (containing the library sketch block and other end cut specific settings) that defines the end cut outline 
                 <br>  Created in NX7.5.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::EndCutBlockBuilder * EndCutBlock
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
