#ifndef NXOpen_SKETCHAUTOCONSTRAINBUILDER_HXX_INCLUDED
#define NXOpen_SKETCHAUTOCONSTRAINBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     SketchAutoConstrainBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/SketchAutoConstrainBuilder.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class SketchAutoConstrainBuilder;
    class Builder;
    class SelectObjectList;
    class _SketchAutoConstrainBuilderBuilder;
    class SketchAutoConstrainBuilderImpl;
    /** 
    Represents a @link NXOpen::SketchAutoConstrainBuilder NXOpen::SketchAutoConstrainBuilder@endlink 
     <br> To create a new instance of this class, use @link NXOpen::SketchCollection::CreateAutoConstrainBuilder  NXOpen::SketchCollection::CreateAutoConstrainBuilder @endlink  <br> 
    Default values.
    <table border="1"> 
     
    <tr><th> 
    Property</th>  <th> 
    Value</th> </tr>
    <tr><td> 
     
    Horizontal </td> <td> 
     
    True </td> </tr> 

    <tr><td> 
     
    Parallel </td> <td> 
     
    True </td> </tr> 

    <tr><td> 
     
    Perpendicular </td> <td> 
     
    True </td> </tr> 

    <tr><td> 
     
    Tangent </td> <td> 
     
    True </td> </tr> 

    <tr><td> 
     
    Vertical </td> <td> 
     
    True </td> </tr> 

    </table>  

     <br>  Created in NX5.0.0.  <br>  
    */
    class NXOPENCPPEXPORT  SketchAutoConstrainBuilder : public NXOpen::Builder
    {
        private: SketchAutoConstrainBuilderImpl * m_sketchautoconstrainbuilder_impl;
        private: friend class  _SketchAutoConstrainBuilderBuilder;
        protected: SketchAutoConstrainBuilder();
        public: ~SketchAutoConstrainBuilder();
        /**Returns  the selected curve list. 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: NXOpen::SelectObjectList * CurveList
        (
        );
        /**Returns  the horizontal 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Horizontal
        (
        );
        /**Sets  the horizontal 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetHorizontal
        (
            bool horizontal /** horizontal */ 
        );
        /**Returns  the vertical 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Vertical
        (
        );
        /**Sets  the vertical 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetVertical
        (
            bool vertical /** vertical */ 
        );
        /**Returns  the tangent 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Tangent
        (
        );
        /**Sets  the tangent 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetTangent
        (
            bool tangent /** tangent */ 
        );
        /**Returns  the parallel 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Parallel
        (
        );
        /**Sets  the parallel 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetParallel
        (
            bool parallel /** parallel */ 
        );
        /**Returns  the perpendicular 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Perpendicular
        (
        );
        /**Sets  the perpendicular 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetPerpendicular
        (
            bool perpendicular /** perpendicular */ 
        );
        /**Returns  the collinear 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Collinear
        (
        );
        /**Sets  the collinear 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetCollinear
        (
            bool collinear /** collinear */ 
        );
        /**Returns  the concentric 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Concentric
        (
        );
        /**Sets  the concentric 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetConcentric
        (
            bool concentric /** concentric */ 
        );
        /**Returns  the equal length 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool EqualLength
        (
        );
        /**Sets  the equal length 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetEqualLength
        (
            bool equalLength /** equallength */ 
        );
        /**Returns  the equal radius 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool EqualRadius
        (
        );
        /**Sets  the equal radius 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetEqualRadius
        (
            bool equalRadius /** equalradius */ 
        );
        /**Returns  the point on curve 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool PointOnCurve
        (
        );
        /**Sets  the point on curve 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetPointOnCurve
        (
            bool pointOnCurve /** pointoncurve */ 
        );
        /**Returns  the coincident 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool Coincident
        (
        );
        /**Sets  the coincident 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetCoincident
        (
            bool coincident /** coincident */ 
        );
        /** Set all of the individual constraints (turn toggle to on for each one) 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetAllConstraints
        (
        );
        /** Clear all of the indivivual constraints (turn toggle to off for each one) 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void ClearAllConstraints
        (
        );
        /**Returns  the distance tolerance 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: double DistanceTolerance
        (
        );
        /**Sets  the distance tolerance 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetDistanceTolerance
        (
            double distanceTolerance /** distancetolerance */ 
        );
        /**Returns  the angle tolerance 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: double AngleTolerance
        (
        );
        /**Sets  the angle tolerance 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetAngleTolerance
        (
            double angleTolerance /** angletolerance */ 
        );
        /**Returns  the apply remote constraints 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : None */
        public: bool ApplyRemoteConstraints
        (
        );
        /**Sets  the apply remote constraints 
         <br>  Created in NX5.0.0.  <br>  
         <br> License requirements : solid_modeling ("SOLIDS MODELING") */
        public: void SetApplyRemoteConstraints
        (
            bool applyRemoteConstraints /** applyremoteconstraints */ 
        );
    };
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
