#ifndef NXOpen_WELD_WELDFILLBUILDER_HXX_INCLUDED
#define NXOpen_WELD_WELDFILLBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Weld_WeldFillBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/Weld_CharacteristicsBuilder.hxx>
#include <NXOpen/Weld_WeldFillBuilder.hxx>
#include <NXOpen/Weld_WeldFillStripBuilder.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_weld_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Weld
    {
        class WeldFillBuilder;
    }
    class Builder;
    class CoordinateSystem;
    class Point;
    class ScCollector;
    class Section;
    namespace Weld
    {
        class CharacteristicsBuilder;
    }
    namespace Weld
    {
        class WeldFillStripBuilder;
    }
    namespace Weld
    {
        class WeldFillStripBuilderList;
    }
    namespace Weld
    {
        class _WeldFillBuilderBuilder;
        class WeldFillBuilderImpl;
        /** A builder used to create or edit a @link NXOpen::Weld::Fill NXOpen::Weld::Fill@endlink  feature.  <br> To create a new instance of this class, use @link NXOpen::Weld::WeldManager::CreateFillBuilder  NXOpen::Weld::WeldManager::CreateFillBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        BoundaryMethod </td> <td> 
         
        Rectangle </td> </tr> 

        <tr><td> 
         
        ChangeViewOrientation </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        ExtendDistance </td> <td> 
         
        -15.0 (millimeters part), -0.5 (inches part) </td> </tr> 

        <tr><td> 
         
        ExtrudeHeight </td> <td> 
         
        1 </td> </tr> 

        <tr><td> 
         
        SubdivideRegion </td> <td> 
         
        0 </td> </tr> 

        <tr><td> 
         
        Width </td> <td> 
         
        5 </td> </tr> 

        <tr><td> 
         
        WidthAlong </td> <td> 
         
        Xc </td> </tr> 

        </table>  

         <br>  Created in NX7.5.0.  <br>  
        */
        class NXOPENCPP_WELDEXPORT  WeldFillBuilder : public NXOpen::Builder
        {
            /** Defines whether the initial boundary of the fill pattern is defined
                        by a two point rectangle or a curve. */
            public: enum BoundaryMethodType
            {
                BoundaryMethodTypeRectangle/** Boundary defined by a two point rectangle. */,
                BoundaryMethodTypeCurve/** Boundary defined by a curve. */
            };

            /** Defines the direction the fill strip's length is aligned */
            public: enum WidthAlongType
            {
                WidthAlongTypeXc/** The length is aligned along the current WCS X direction. */,
                WidthAlongTypeYc/** The length is aligned along the current WCS Y direction. */
            };

            private: WeldFillBuilderImpl * m_weldfillbuilder_impl;
            private: friend class  _WeldFillBuilderBuilder;
            protected: WeldFillBuilder();
            public: ~WeldFillBuilder();
            /**Returns  the collector containing the faces to build the fill on. Note that during processing
                        additional faces will be obtained by getting adjacent tangent faces (within 45 degrees) so that
                        the boundary of the area is covered. At least one face inside of every boundary must be selected. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::ScCollector * PlacementFace
            (
            );
            /**Returns  the coordinate system that defines the alignment of the strips and rectangle. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CoordinateSystem * Orientation
            (
            );
            /**Sets  the coordinate system that defines the alignment of the strips and rectangle. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetOrientation
            (
                NXOpen::CoordinateSystem * csys /** csys */ 
            );
            /**Returns  the type of boundary to create the fill from. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Weld::WeldFillBuilder::BoundaryMethodType BoundaryMethod
            (
            );
            /**Sets  the type of boundary to create the fill from. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetBoundaryMethod
            (
                NXOpen::Weld::WeldFillBuilder::BoundaryMethodType boundaryMethod /** boundarymethod */ 
            );
            /**Returns  the indication if the fill is to be a collection of rectangles (true), or
                        simply the enclosed boundary area (false). 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: bool SubdivideRegion
            (
            );
            /**Sets  the indication if the fill is to be a collection of rectangles (true), or
                        simply the enclosed boundary area (false). 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetSubdivideRegion
            (
                bool subdivideRegion /** subdivideregion */ 
            );
            /**Returns  the first corner of the boundary if the 
                        @link NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle@endlink  
                        option is specified for the boundary type. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * Corner1
            (
            );
            /**Sets  the first corner of the boundary if the 
                        @link NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle@endlink  
                        option is specified for the boundary type. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetCorner1
            (
                NXOpen::Point * corner1 /** corner1 */ 
            );
            /**Returns  the second corner of the boundary if the 
                        @link NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle@endlink  
                        option is specified for the boundary type. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * Corner2
            (
            );
            /**Sets  the second corner of the boundary if the 
                        @link NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeRectangle@endlink  
                        option is specified for the boundary type. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetCorner2
            (
                NXOpen::Point * corner2 /** corner2 */ 
            );
            /**Returns  the section defining the boundary if the 
                        @link NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeCurve NXOpen::Weld::WeldFillBuilder::BoundaryMethodTypeCurve@endlink  
                        option is specified for the boundary type. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Section * Boundary
            (
            );
            /**Returns  the section containing edges of interior openings which indicate that these openings should be filled over. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Section * InnerBoundary
            (
            );
            /**Returns  the width of the rectangles will be measured along this direction.  
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Weld::WeldFillBuilder::WidthAlongType WidthAlong
            (
            );
            /**Sets  the width of the rectangles will be measured along this direction.  
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetWidthAlong
            (
                NXOpen::Weld::WeldFillBuilder::WidthAlongType widthAlong /** widthalong */ 
            );
            /**Returns  the width of the rectangles. Only used if SubdivideRegion is true. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: double Width
            (
            );
            /**Sets  the width of the rectangles. Only used if SubdivideRegion is true. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetWidth
            (
                double width /** width */ 
            );
            /**Returns  the height of the extrusions representing the fill. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: double ExtrudeHeight
            (
            );
            /**Sets  the height of the extrusions representing the fill. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetExtrudeHeight
            (
                double extrudeHeight /** extrudeheight */ 
            );
            /**Returns  the distance to extend a strip. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: double ExtendDistance
            (
            );
            /**Sets  the distance to extend a strip. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetExtendDistance
            (
                double distance /** distance */ 
            );
            /**Returns  the characteristics information. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Weld::CharacteristicsBuilder * Characteristics
            (
            );
            /**Returns  the indication if the view orientation should be changed automatically (true)
                        upon initial creation of rectangles, or not (false) 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: bool ChangeViewOrientation
            (
            );
            /**Sets  the indication if the view orientation should be changed automatically (true)
                        upon initial creation of rectangles, or not (false) 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetChangeViewOrientation
            (
                bool changeViewOrientation /** changevieworientation */ 
            );
            /**Returns  the indication if the selected faces should be used as seed faces. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: bool UseSeedFace
            (
            );
            /**Sets  the indication if the selected faces should be used as seed faces. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetUseSeedFace
            (
                bool useSeedFace /** useseedface */ 
            );
            /**Returns  the distance tolerance used in processing to determine if two points are coincident. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : None */
            public: double DistanceTolerance
            (
            );
            /**Sets  the distance tolerance used in processing to determine if two points are coincident. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void SetDistanceTolerance
            (
                double distanceTolerance /** distancetolerance */ 
            );
            /** Create a new fill strip.  @return  
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NXOpen::Weld::WeldFillStripBuilder * NewFillStrip
            (
                const NXOpen::Point3d & center /** Center of the fill strip */,
                double length /** Length of the fill strip */
            );
            /** Delete a fill strip. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: void DeleteFillStrip
            (
                NXOpen::Weld::WeldFillStripBuilder * fillStrip /** Fill strip to delete. */
            );
            /**Returns  the fill strip list. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NXOpen::Weld::WeldFillStripBuilderList * FillStripList
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
