#ifndef NXOpen_FEATURES_SHEETMETAL_SHEETMETALFROMSOLIDBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHEETMETAL_SHEETMETALFROMSOLIDBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_SheetMetal_SheetMetalFromSolidBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_SheetMetal_BendOptions.hxx>
#include <NXOpen/Features_SheetMetal_SheetMetalFromSolidBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        namespace SheetMetal
        {
            class SheetMetalFromSolidBuilder;
        }
    }
    class Edge;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace Features
    {
        namespace SheetMetal
        {
            class BendOptions;
        }
    }
    class ScCollector;
    namespace Features
    {
        namespace SheetMetal
        {
            class _SheetMetalFromSolidBuilderBuilder;
            /**
                Represents a @link Features::SheetMetalFromSolid Features::SheetMetalFromSolid@endlink  builder
                (Sheet Metal from Solid).
                 <br> To create a new instance of this class, use @link Features::SheetMetal::SheetmetalManager::CreateSheetMetalFromSolidBuilder Features::SheetMetal::SheetmetalManager::CreateSheetMetalFromSolidBuilder@endlink  <br> 
            Default values:
            Thickness.RightHandSide: 3.0 (millimeters part), 0.1 (inches part)
            UseGlobalThickness: 1
            */
            class NXOPENCPPEXPORT SheetMetalFromSolidBuilder : public Features::FeatureBuilder
            {
                private: friend class  _SheetMetalFromSolidBuilderBuilder;
                protected: SheetMetalFromSolidBuilder();
                /**Returns  the web faces  <br> License requirements : None */
                public: NXOpen::ScCollector * WebFaces
                (
                );
                /**Returns  the bend edges  <br> License requirements : None */
                public: NXOpen::ScCollector * BendEdges
                (
                );
                /**Returns  the thickness  <br> License requirements : None */
                public: NXOpen::Expression * Thickness
                (
                );
                /**Returns  the reverse direction  <br> License requirements : None */
                public: bool ReverseDirection
                (
                );
                /**Sets  the reverse direction  <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetReverseDirection
                (
                    bool reverseDirection /** reversedirection */ 
                );
                /**Returns  the use global thickness  <br> License requirements : None */
                public: bool UseGlobalThickness
                (
                );
                /**Sets  the use global thickness  <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: void SetUseGlobalThickness
                (
                    bool useGlobalThickness /** useglobalthickness */ 
                );
                /**Returns  the bend options  <br> License requirements : None */
                public: NXOpen::Features::SheetMetal::BendOptions * BendOptions
                (
                );
                /** Get the candidate bend edges  @return   <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: std::vector<NXOpen::Edge *> GetCandidateBendEdges
                (
                );
                /** Get the automatic bend edges  @return   <br> License requirements : nx_sheet_metal ("NX Sheet Metal") */
                public: std::vector<NXOpen::Edge *> GetAutomaticBendEdges
                (
                );
            };
        }
    }
}
#undef EXPORTLIBRARY
#endif
