#ifndef NXOpen_FEATURES_MATCHEDGEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_MATCHEDGEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_MatchEdgeBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_MatchEdgeBuilder.hxx>
#include <NXOpen/GeometricUtilities_Continuity.hxx>
#include <NXOpen/GeometricUtilities_ControlPoleManagerData.hxx>
#include <NXOpen/GeometricUtilities_CurveRangeBuilder.hxx>
#include <NXOpen/GeometricUtilities_DegreesAndSegmentsOrPatchesBuilder.hxx>
#include <NXOpen/GeometricUtilities_DepthSkewBuilder.hxx>
#include <NXOpen/GeometricUtilities_OnPathDimensionBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class MatchEdgeBuilder;
    }
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class Continuity;
    }
    namespace GeometricUtilities
    {
        class ControlPoleManagerData;
    }
    namespace GeometricUtilities
    {
        class CurveRangeBuilder;
    }
    namespace GeometricUtilities
    {
        class DegreesAndSegmentsOrPatchesBuilder;
    }
    namespace GeometricUtilities
    {
        class DepthSkewBuilder;
    }
    namespace GeometricUtilities
    {
        class OnPathDimensionBuilder;
    }
    class SelectDisplayableObjectList;
    class SelectNXObject;
    namespace Features
    {
        class _MatchEdgeBuilderBuilder;
        /**
            Represents a @link Features::MatchEdge Features::MatchEdge@endlink  builder
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateMatchEdgeBuilder Features::FeatureCollection::CreateMatchEdgeBuilder@endlink  <br> 
        Default values:
        DegreePatches.Degree: 3
        DegreePatches.SegmentsOrPatches: 1
        DegreePatches.UDegree: 5
        DegreePatches.UPatches: 1
        DegreePatches.VDegree: 5
        DegreePatches.VPatches: 1
        EdgeLimit.AnchorPosition: Start
        EndEdgeConstraintType: Linked
        IsEndEdgeLocked: 0
        IsG0Continuity: 1
        IsG1Continuity: 1
        IsG2Continuity: 0
        IsG3Continuity: 0
        IsMatchEndToEnd: 0
        IsMatchExact: 0
        IsStartEdgeLocked: 0
        PoleMovementConstraint: Normal
        RangeControl.RightHandSide: 0 (millimeters part), 0 (inches part)
        StartEdgeConstraintType: Free
        */
        class NXOPENCPPEXPORT MatchEdgeBuilder : public Features::FeatureBuilder
        {
            /** Match Edge match types */
            public: enum Types
            {
                TypesMatchEdgeToEdge/** Edge to Edge match type  */,
                TypesMatchEdgeToFace/** Edge to Face match type  */,
                TypesMatchEdgeToCurve/** Edge to Curve match type */,
                TypesMatchEdgeToDatum/** Edge to Datum match type */
            };

            /** Pole movement type */
            public: enum PoleMovementType
            {
                PoleMovementTypeNormal/** Normal                    */,
                PoleMovementTypeProject/** Project                   */,
                PoleMovementTypeFixStart/** Fix start                 */,
                PoleMovementTypeFixEnd/** Fix end                   */,
                PoleMovementTypeFixStartAndEnd/** Fix start and end         */,
                PoleMovementTypeAlongXC/** Along xc                  */,
                PoleMovementTypeAlongYC/** Along yc                  */,
                PoleMovementTypeAlongZC/** Along zc                  */,
                PoleMovementTypeAlongVector/** Along user defined vector */
            };

            /** boundary edge constraint types */
            public: enum BoundaryEdgeConstraintType
            {
                BoundaryEdgeConstraintTypeLinked/** Linked, available for end edge only */,
                BoundaryEdgeConstraintTypeFree/** Free             */,
                BoundaryEdgeConstraintTypePerpendicular/** Perpendicular    */,
                BoundaryEdgeConstraintTypeIsoU/** Iso u            */,
                BoundaryEdgeConstraintTypeIsoV/** Iso v            */,
                BoundaryEdgeConstraintTypeAdjacent/** Adjacent         */
            };

            private: friend class  _MatchEdgeBuilderBuilder;
            protected: MatchEdgeBuilder();
            /**Returns  the edge to edit  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::SelectNXObject * ObjectToEdit
            (
            );
            /** Loads editing edge related internal data and should be called after selection of edge or face to match to  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: void LoadEditEdge
            (
            );
            /**Returns  the target object that the edge is matching to  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::SelectDisplayableObjectList * TargetObjects
            (
            );
            /**Returns  the g0 continuity  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsG0Continuity
            (
            );
            /**Sets  the g0 continuity  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetG0Continuity
            (
                bool g0Continuity /** g0continuity */ 
            );
            /**Returns  the g1 continuity  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsG1Continuity
            (
            );
            /**Sets  the g1 continuity  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetG1Continuity
            (
                bool g1Continuity /** g1continuity */ 
            );
            /**Returns  the g2 continuity  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsG2Continuity
            (
            );
            /**Sets  the g2 continuity  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetG2Continuity
            (
                bool g2Continuity /** g2continuity */ 
            );
            /**Returns  the g3 continuity  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsG3Continuity
            (
            );
            /**Sets  the g3 continuity  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetG3Continuity
            (
                bool g3Continuity /** g3continuity */ 
            );
            /**Returns  the start continuity constraint for matched surface  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::Continuity * OppositeEdgeConstraint
            (
            );
            /**Returns  the match exact state  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsMatchExact
            (
            );
            /**Sets  the match exact state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetMatchExact
            (
                bool matchExact /** matchexact */ 
            );
            /**Returns  the degree and patches  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::DegreesAndSegmentsOrPatchesBuilder * DegreePatches
            (
            );
            /**Returns  the constraint pole movement  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Features::MatchEdgeBuilder::PoleMovementType PoleMovementConstraint
            (
            );
            /**Sets  the constraint pole movement  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetPoleMovementConstraint
            (
                NXOpen::Features::MatchEdgeBuilder::PoleMovementType poleMovementConstraint /** polemovementconstraint */ 
            );
            /**Returns  the start edge constraint. The "Linked" options is not available for start edge.  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Features::MatchEdgeBuilder::BoundaryEdgeConstraintType StartEdgeConstraintType
            (
            );
            /**Sets  the start edge constraint. The "Linked" options is not available for start edge.  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetStartEdgeConstraintType
            (
                NXOpen::Features::MatchEdgeBuilder::BoundaryEdgeConstraintType constraintStartEdge /** constraintstartedge */ 
            );
            /**Returns  the start edge locked state  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsStartEdgeLocked
            (
            );
            /**Sets  the start edge locked state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetStartEdgeLocked
            (
                bool isStartEdgeLocked /** isstartedgelocked */ 
            );
            /**Returns  the end edge constraint   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Features::MatchEdgeBuilder::BoundaryEdgeConstraintType EndEdgeConstraintType
            (
            );
            /**Sets  the end edge constraint   <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetEndEdgeConstraintType
            (
                NXOpen::Features::MatchEdgeBuilder::BoundaryEdgeConstraintType constraintEndEdge /** constraintendedge */ 
            );
            /**Returns  the end edge locked state  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsEndEdgeLocked
            (
            );
            /**Sets  the end edge locked state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetEndEdgeLocked
            (
                bool lockEndEdge /** lockendedge */ 
            );
            /**Returns  the match end to end state  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: bool IsMatchEndToEnd
            (
            );
            /**Sets  the match end to end state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetMatchEndToEnd
            (
                bool isMatchEndToEnd /** ismatchendtoend */ 
            );
            /**Returns  the edge limit  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::CurveRangeBuilder * EdgeLimit
            (
            );
            /**Returns  the edge offset position  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::OnPathDimensionBuilder * EdgeOffsetPosition
            (
            );
            /**Returns  the shape control  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::DepthSkewBuilder * ShapeControl
            (
            );
            /**Returns  the range control  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Expression * RangeControl
            (
            );
            /**Returns  the constraint match direction  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Direction * MatchDirectionConstraint
            (
            );
            /**Sets  the constraint match direction  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetMatchDirectionConstraint
            (
                NXOpen::Direction * matchDirectionConstraint /** matchdirectionconstraint */ 
            );
            /**Returns  the move pole direction  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Direction * MovePoleDirection
            (
            );
            /**Sets  the move pole direction  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetMovePoleDirection
            (
                NXOpen::Direction * movePoleDirection /** movepoledirection */ 
            );
            /**Returns  the control pole manager  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::GeometricUtilities::ControlPoleManagerData * ControlPoleManager
            (
            );
            /**Returns  the type  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR studio_free_form ("STUDIO FREE FORM") */
            public: NXOpen::Features::MatchEdgeBuilder::Types Type
            (
            );
            /**Sets  the type  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetType
            (
                NXOpen::Features::MatchEdgeBuilder::Types type /** type */ 
            );
            /** Sets up surface pole editing. This should be called before getting into 
                        pole editing function to prepare necessary settings to start surface pole edit.
                     <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetupPoleEditing
            (
            );
            /** Updates surface during edit pole. This function is used only in pole editing stage 
                        and after poles are moved to new positions. This function updates the surface according to
                        the new pole positions.
                     <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void EditPoleUpdateSurface
            (
            );
            /**Returns  the poles edit state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: bool IsEditPoleEnabled
            (
            );
            /**Sets  the poles edit state  <br> License requirements : features_modeling ("FEATURES MODELING") */
            public: void SetEditPoleEnabled
            (
                bool enable /** enable */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
