#ifndef NXOpen_POINTCOLLECTION_HXX_INCLUDED
#define NXOpen_POINTCOLLECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     PointCollection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/SmartObject.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/TaggedObjectCollection.hxx>
#include <NXOpen/type.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    class PointCollection;
    class BasePart;
    class Point;
    class CartesianCoordinateSystem;
    class Direction;
    class Expression;
    class IBaseCurve;
    class IBasePlane;
    class IParameterizedSurface;
    class Offset;
    namespace Routing
    {
        class IRoutePosition;
    }
    namespace Routing
    {
        class Port;
    }
    class Scalar;
    class TaggedObject;
    class View;
    class Xform;
    /**
     Represents a collection of smart @link Point Point@endlink .
     <br> To obtain an instance of this class, refer to @link BasePart BasePart@endlink  <br> */
    class NXOPENCPPEXPORT PointCollection : public TaggedObjectCollection
    {
        /**
            Describes whether the input Scalar to the 
            @link  PointCollection::CreatePoint   PointCollection::CreatePoint @endlink  
            method is either an absolute distance or a relative percentage.
            */
        public: enum AlongCurveOption
        {
            AlongCurveOptionDistance/** Scalar is an absolute distance. */,
            AlongCurveOptionPercent/** Scalar is a relative percentage. */
        };

        private: NXOpen::BasePart* m_owner;
        public: explicit PointCollection(NXOpen::BasePart *owner): m_owner(owner)
        {
        }
        public: 
        /**Returns the tag of this object.  */
        tag_t Tag() const; 
        /** Iterator for accessing the contents of the collection. */
        class iterator
        {
        public:
            typedef Point * value_type;
            /** Default constructor */
            iterator() : m_context(NULL), m_current(NULL_TAG)
            {
            }
            explicit iterator(NXOpen::PointCollection *context) : m_context(context), m_current(NULL_TAG)
            {
            }
            iterator(const iterator &other)
            {
                copy(other);
            }
            /** Copy constructor */
            iterator &operator =(const iterator &other)
            {
                if (&other != this)
                    copy(other);
                return *this;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are equal. */
            bool operator ==(const iterator &other) const
            {
                return m_current == other.m_current && m_context == other.m_context;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are not equal. */
            bool operator !=(const iterator &other) const
            {
                return !operator == (other);
            }
            /** Return the element currently pointed to by the iterator. */
            NXOPENCPPEXPORT  value_type operator * ();
            /** Points the iterator to next element. */
            iterator & operator ++()
            {
                next();
                return *this;
            }
            /** Points the iterator to next element. */
            iterator operator ++(int)
            {
                iterator tmp(*this);
                ++*this;
                return tmp;
            }
        private:
            void copy(const iterator &other)
            {
                m_context = other.m_context;
                m_current = other.m_current;
                for (int i = 0; i < sizeof(m_state)/sizeof(m_state[0]); i++)
                     m_state[i] = other.m_state[i];
            }
            NXOPENCPPEXPORT  void next();
            NXOpen::PointCollection *m_context;
            tag_t m_current;
            unsigned int m_state[8];
        };
        /** Returns an iterator addressing the first element. */
        iterator begin();
        /** Returns an iterator addressing one past the last element. */
        iterator end()
        {
            return iterator(this);
        }
        /** 
            Creates a @link Point Point@endlink  without parameters.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            const NXOpen::Point3d & coordinates /**  Coordinates of a Point */
        );
        /** 
            Creates a @link Point Point@endlink  using a @link Point Point@endlink  and an @link Offset Offset@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Offset * offset /** offset */ ,
            NXOpen::Point * offsetPoint /** Offsetting from this Point */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  on a Surface or @link Face Face@endlink  via U-V @link Scalar Scalar@endlink  for the surface.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IParameterizedSurface * face /** face */ ,
            NXOpen::Scalar * scalarU /**  U parameter */,
            NXOpen::Scalar * scalarV /**  V parameter */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  on the intersection of two @link Curve Curve@endlink  and/or @link Edge Edge@endlink  in a View.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::View * view /** view */ ,
            NXOpen::IBaseCurve * edgeCurve1 /** Edge or Curve */,
            NXOpen::IBaseCurve * edgeCurve2 /** Edge or Curve */,
            const NXOpen::Point3d & helpPt /**  Help Point for curve 1 */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  on a @link Curve Curve@endlink  or @link Edge Edge@endlink  and @link Scalar Scalar@endlink  representing the T parameter.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * edgeCurve /** Edge or Curve */,
            NXOpen::Scalar * scalarT /**  T parameter */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /** 
            Creates a @link Point Point@endlink  along a @link Curve Curve@endlink  or @link Edge Edge@endlink  using a @link Point Point@endlink , and a @link Scalar Scalar@endlink  representing
            the T parameter along the @link Curve Curve@endlink .  This @link Point Point@endlink  is derived by finding the
            closest @link Point Point@endlink  on the given curve to the given @link Point Point@endlink  and then offsetting this Point
            along the given @link Curve Curve@endlink  by the arc length defined by T via absolute
            distance or relative percent.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * edgeCurve /** Edge or Curve */,
            NXOpen::Point * pointOffset /** Offset from this Point */,
            NXOpen::Scalar * distancePercent /**  Distance or Percentage */,
            NXOpen::PointCollection::AlongCurveOption option /**  Specify whether the input Scalar is distance/percentage */,
            NXOpen::Sense sense /**  forward/reverse along the Edge or Curve */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  via three @link Scalar Scalar@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Scalar * scalarX /** X location */,
            NXOpen::Scalar * scalarY /** Y location */,
            NXOpen::Scalar * scalarZ /** Z location */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  via an existing @link Point Point@endlink  using an optional @link Xform Xform@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Point * pointExtract /** Point to be extracted */,
            NXOpen::Xform * xform /**  optional Xform */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /** 
            Creates a @link Point Point@endlink  at an angle along an @link IBaseCurve IBaseCurve@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * edgeCurve /** edge curve */ ,
            NXOpen::Scalar * angle /** angle in radians */,
            NXOpen::Xform * xform /** optional Xform */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  via the center of an @link Edge Edge@endlink  or 
            @link Curve Curve@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * edgeCurve /** edge curve */ ,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the intersection of two Edges or Curves.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * curve1 /**  First Edge or Curve in intersection */,
            NXOpen::IBaseCurve * curve2 /** Second Edge or Curve in intersection */,
            NXOpen::Point * helpPt1 /**  Optional help Point for curve 1 */,
            NXOpen::Point * helpPt2 /** Optional help Point for curve 2 */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the apparent intersection of two Edges or Curves in a view.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBaseCurve * curve1 /** First Edge or Curve in intersection */,
            NXOpen::IBaseCurve * curve2 /** Second Edge or Curve in intersection */,
            const NXOpen::Point3d & startPoint /** Start point of the intersection */,
            NXOpen::View * view /** View in which to project the intersection */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the intersection of a
            @link IParameterizedSurface IParameterizedSurface@endlink  and @link IBaseCurve IBaseCurve@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IParameterizedSurface * face /** face */ ,
            NXOpen::IBaseCurve * curve /**  Curve in intersection */,
            NXOpen::Point * helpPt1 /**  Optional help Point for face */,
            NXOpen::Point * helpPt2 /**  Optional help Point for curve */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the intersection of a @link IBasePlane IBasePlane@endlink 
            and @link IBaseCurve IBaseCurve@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IBasePlane * plane /**  Plane or DatumPlane in intersection */,
            NXOpen::IBaseCurve * curve /**  Curve or Edge in intersection */,
            NXOpen::Point * helpPt1 /**  Optional help Point for face */,
            NXOpen::Point * helpPt2 /**  Optional help Point for curve */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the center of a spherical face.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::IParameterizedSurface * sphericalFace /** spherical face */ ,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the given @link Routing::IRoutePosition Routing::IRoutePosition@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Routing::IRoutePosition * routePosition /** route position */ ,
            NXOpen::Xform * xform /**  optional @link Xform Xform@endlink  */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /** Finds the @link  Point   Point @endlink  with the given identifier as recorded in a journal. 
                An object may not return the same value as its JournalIdentifier in different versions of 
                the software. However newer versions of the software should find the same object when 
                FindObject is passed older versions of its journal identifier. In general, this method 
                should not be used in handwritten code and exists to support record and playback of journals.

                An exception will be thrown if no object can be found with the given journal identifier.  @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * FindObject
        (
            const NXString & journalIdentifier /** Identifier of the Point you want   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
        );
        /**
            Creates a @link Point Point@endlink  via @link CartesianCoordinateSystem CartesianCoordinateSystem@endlink  and three @link Scalar Scalar@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::CartesianCoordinateSystem * csys /** Cartesian Coordinate System */,
            NXOpen::Scalar * scalarX /** X location */,
            NXOpen::Scalar * scalarY /** Y location */,
            NXOpen::Scalar * scalarZ /** Z location */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  between two points using a @link Scalar Scalar@endlink  that represents
            a percentage of the distance between the points.  The distance is measured from the first point to the
            second point.  There is no limit on the percentage so the point can be outside the area between the two
            points.  
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Point * point1 /** point1 */ ,
            NXOpen::Point * point2 /** point2 */ ,
            NXOpen::Scalar * distancePercentage /** distance percentage */ ,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  at the virtual intersection of two Edges or Curves.
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreateVirtualIntersectionPoint
        (
            NXOpen::IBaseCurve * curve1 /**  First Edge or Curve in virtual intersection */,
            NXOpen::IBaseCurve * curve2 /** Second Edge or Curve in virtual intersection */,
            NXOpen::Point * helpPt1 /**  Optional help Point for curve 1 */,
            NXOpen::Point * helpPt2 /** Optional help Point for curve 2 */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /**
            Creates a @link Point Point@endlink  via an @link Expression Expression@endlink .
             @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Point * CreatePoint
        (
            NXOpen::Expression * exp /** EXP Point */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /** 
             Creates a Routing "Stock Offset" point.  This stock offset point offsets itself from
             the input base point along the specified direction.  The input expression determines the
             distance between the base point and the offset point.  The input expression may reference
             the variable "MAX_PATH_STOCK_DIA" which is replaced by the current maximum diameter of
             stock applied to Routing segments that refer to the offset point.
              @return   <br> License requirements : routing_mechanical ("Routing Mechanical") OR routing_electrical ("Routing Electrical") OR routing_combined ("Routing Combined") */
        public: NXOpen::Point * CreateStockOffsetPoint
        (
            NXOpen::Point * basePoint /** Base point to offset from. */,
            NXOpen::Direction * offsetDirr /** Direction to offset along. */,
            const NXString & offsetExpression /** Offset value expression.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ 
        );
        /** 
             Creates a @link Point Point@endlink  at a @link Routing::Port Routing::Port@endlink .
             The @link Routing::Port Routing::Port@endlink  will be extraced into the work part if
             necessary. If the @link Routing::Port Routing::Port@endlink  has already been extracted,
             the existing extract will be used. If extraction is not required, the input
             @link Routing::Port Routing::Port@endlink  will be used.
              @return   <br> License requirements : routing_mechanical ("Routing Mechanical") OR routing_electrical ("Routing Electrical") OR routing_combined ("Routing Combined") */
        public: NXOpen::Point * CreatePointOnPortExtractAlign
        (
            NXOpen::SmartObject::UpdateOption updateOption /** update option */ ,
            NXOpen::Routing::Port * port /** @link Routing::Port Routing::Port@endlink  */,
            NXOpen::Scalar * distance /** Scalar Distance */
        );
        /** Creates a parameterised point on the center line axis of the given face.
             @return  Point   <br> License requirements : None */
        public: NXOpen::Point * CreatePointOnSurfaceAxis
        (
            NXOpen::TaggedObject * face /** RM Face */,
            NXOpen::Scalar * parameter /** RM Scalar */,
            NXOpen::SmartObject::UpdateOption updateOption /** Update option of smart object  */
        );
        public: virtual void initialize();
    };
}
#undef EXPORTLIBRARY
#endif
