#ifndef NXOpen_TOOLING_WIREHOLEBUILDER_HXX_INCLUDED
#define NXOpen_TOOLING_WIREHOLEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Tooling_WireHoleBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Tooling_WireHoleBuilder.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Tooling
    {
        class WireHoleBuilder;
    }
    class Builder;
    class Direction;
    class Point;
    class ScCollector;
    namespace Tooling
    {
        class _WireHoleBuilderBuilder;
        /**
             Represents a @link Tooling::WireHoleBuilder Tooling::WireHoleBuilder@endlink 
             This class is for Wire Hole Design UI
             <br> To create a new instance of this class, use @link Tooling::WireHoleCollection::CreateWireHoleBuilder Tooling::WireHoleCollection::CreateWireHoleBuilder@endlink  <br> 
        Default values:
        HoleDiameter: 3
        */
        class NXOPENCPPEXPORT WireHoleBuilder : public Builder
        {
            private: friend class  _WireHoleBuilderBuilder;
            protected: WireHoleBuilder();
            /**Returns  the plane to create wire hole sketch  <br> License requirements : None */
            public: NXOpen::ScCollector * SketchPlane
            (
            );
            /**Returns  the orientation to create wire hole sketch  <br> License requirements : None */
            public: NXOpen::Direction * SketchOrientation
            (
            );
            /**Sets  the orientation to create wire hole sketch  <br> License requirements : None */
            public: void SetSketchOrientation
            (
                NXOpen::Direction * sketchOrientation /** Sets the orientation to create wire hole sketch */
            );
            /**Returns  the diameter to create wire hole  <br> License requirements : None */
            public: double HoleDiameter
            (
            );
            /**Sets  the diameter to create wire hole  <br> License requirements : None */
            public: void SetHoleDiameter
            (
                double holeDiameter /** Sets the diameter to create wire hole */
            );
            /**Returns  the centerline length to create wire hole  <br> License requirements : None */
            public: NXString CenterlineLength
            (
            );
            /**Sets  the centerline length to create wire hole  <br> License requirements : None */
            public: void SetCenterlineLength
            (
                const NXString & centerlineLength /** Sets the centerline length to create wire hole */
            );
            /**Returns  the circle center to create wire hole  <br> License requirements : None */
            public: NXOpen::Point * CircleCenter
            (
            );
            /**Sets  the circle center to create wire hole  <br> License requirements : None */
            public: void SetCircleCenter
            (
                NXOpen::Point * circleCenter /** Sets the circle center to create wire hole */
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
