#ifndef NXOpen_ANNOTATIONS_OFFSETCENTERPOINTBUILDER_HXX_INCLUDED
#define NXOpen_ANNOTATIONS_OFFSETCENTERPOINTBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_OffsetCenterPointBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_OffsetCenterPointBuilder.hxx>
#include <NXOpen/Annotations_BaseSymbolBuilder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Annotations
    {
        class OffsetCenterPointBuilder;
    }
    namespace Annotations
    {
        class BaseSymbolBuilder;
    }
    class NXColor;
    class SelectNXObject;
    namespace Annotations
    {
        class _OffsetCenterPointBuilderBuilder;
        /** Represents a @link Annotations::OffsetCenterPoint Annotations::OffsetCenterPoint@endlink  builder  <br> To create a new instance of this class, use @link Annotations::OffsetCenterPointCollection::CreateOffsetCenterPointBuilder Annotations::OffsetCenterPointCollection::CreateOffsetCenterPointBuilder@endlink  <br> 
        Default values:
        CenterCross: 3.175 (millimeters part), 0.125 (inches part)
        DisplayStyle: CenterPoint
        Distance: 0
        Extension: 6.35 (millimeters part), 0.25 (inches part)
        Gap: 1.5875 (millimeters part), 0.0625 (inches part)
        OffsetMethod: HorizontalDistanceFromArc
        Width: Thin
        */
        class NXOPENCPPEXPORT OffsetCenterPointBuilder : public Annotations::BaseSymbolBuilder
        {
            /** the valid offset method types */
            public: enum Offset
            {
                OffsetHorizontalDistanceFromArc/** horizontal distance from arc */,
                OffsetHorizontalDistanceFromCenter/** horizontal distance from center */,
                OffsetHorizontalDistanceByPosition/** horizontal distance by position */,
                OffsetVerticalDistanceFromArc/** vertical distance from arc */,
                OffsetVerticalDistanceFromCenter/** vertical distance from center */,
                OffsetVerticalDistanceByPosition/** vertical distance by position */
            };

            /** the valid types of display styles */
            public: enum Display
            {
                DisplayCenterPoint/** center point */,
                DisplayCenterLine/** center line */,
                DisplayCenterLineWithExtension/** center line with extension */
            };

            /** the valid types of offset center point thickness */
            public: enum Thickness
            {
                ThicknessThin/** thin */,
                ThicknessNormal/** normal */,
                ThicknessThick/** thick */
            };

            private: friend class  _OffsetCenterPointBuilderBuilder;
            protected: OffsetCenterPointBuilder();
            /**Returns  the location  <br> License requirements : None */
            public: NXOpen::SelectNXObject * Location
            (
            );
            /**Returns  the offset method  <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Offset OffsetMethod
            (
            );
            /**Sets  the offset method  <br> License requirements : drafting ("DRAFTING") */
            public: void SetOffsetMethod
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Offset offsetMethod /** offsetmethod */ 
            );
            /**Returns  the offset distance, valid for all offset method types except those by position  <br> License requirements : None */
            public: double Distance
            (
            );
            /**Sets  the offset distance, valid for all offset method types except those by position  <br> License requirements : drafting ("DRAFTING") */
            public: void SetDistance
            (
                double distance /** distance */ 
            );
            /**Returns  the inherit  <br> License requirements : None */
            public: NXOpen::SelectNXObject * Inherit
            (
            );
            /**Returns  the gap  <br> License requirements : None */
            public: double Gap
            (
            );
            /**Sets  the gap  <br> License requirements : drafting ("DRAFTING") */
            public: void SetGap
            (
                double gap /** gap */ 
            );
            /**Returns  the center cross size  <br> License requirements : None */
            public: double CenterCross
            (
            );
            /**Sets  the center cross size  <br> License requirements : drafting ("DRAFTING") */
            public: void SetCenterCross
            (
                double centerCross /** centercross */ 
            );
            /**Returns  the extension  <br> License requirements : None */
            public: double Extension
            (
            );
            /**Sets  the extension  <br> License requirements : drafting ("DRAFTING") */
            public: void SetExtension
            (
                double extension /** extension */ 
            );
            /**Returns  the display style  <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Display DisplayStyle
            (
            );
            /**Sets  the display style  <br> License requirements : drafting ("DRAFTING") */
            public: void SetDisplayStyle
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Display display /** display */ 
            );
            /**Returns  the color  <br> License requirements : None */
            public: NXOpen::NXColor * Color
            (
            );
            /**Sets  the color  <br> License requirements : drafting ("DRAFTING") */
            public: void SetColor
            (
                NXOpen::NXColor * color /** color */ 
            );
            /**Returns  the width  <br> License requirements : None */
            public: NXOpen::Annotations::OffsetCenterPointBuilder::Thickness Width
            (
            );
            /**Sets  the width  <br> License requirements : drafting ("DRAFTING") */
            public: void SetWidth
            (
                NXOpen::Annotations::OffsetCenterPointBuilder::Thickness width /** width */ 
            );
            /**Returns  the offset position, valid for position offset methods  <br> License requirements : None */
            public: NXOpen::Point3d OffsetPosition
            (
            );
            /**Sets  the offset position, valid for position offset methods  <br> License requirements : drafting ("DRAFTING") */
            public: void SetOffsetPosition
            (
                const NXOpen::Point3d & point /** point */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
