#ifndef NXOpen_CAE_ELEMENTEXTRUDEBUILDER_HXX_INCLUDED
#define NXOpen_CAE_ELEMENTEXTRUDEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_ElementExtrudeBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/CAE_ElementExtrudeBuilder.hxx>
#include <NXOpen/CAE_SelectElementsBuilder.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace CAE
    {
        class ElementExtrudeBuilder;
    }
    class Builder;
    namespace CAE
    {
        class SelectCAEEdge;
    }
    namespace CAE
    {
        class SelectCAEFaceList;
    }
    namespace CAE
    {
        class SelectElementsBuilder;
    }
    class Direction;
    class Expression;
    class Point;
    namespace CAE
    {
        class _ElementExtrudeBuilderBuilder;
        /**
            Represents a @link CAE::ElementExtrudeBuilder CAE::ElementExtrudeBuilder@endlink 
             <br> To create a new instance of this class, use @link CAE::NodeElementManager::CreateElementExtrudeBuilder CAE::NodeElementManager::CreateElementExtrudeBuilder@endlink  <br> */
        class NXOPENCPPEXPORT ElementExtrudeBuilder : public Builder
        {
            /** Dimension of element to be created */
            public: enum ElemDimType
            {
                ElemDimTypeBeam/** beam*/,
                ElemDimTypeShell/** shell*/
            };

            /**  Option to create new mesh or add to existing mesh */
            public: enum NewMeshType
            {
                NewMeshTypeCreate/** create new mesh*/,
                NewMeshTypeExisting/** add to existing mesh*/
            };

            /** Extrusion method */
            public: enum MethodType
            {
                MethodTypeVector/** along vector */,
                MethodTypePath/** along path*/,
                MethodTypeProjSurface/** project to surface*/,
                MethodTypeElemNormal/** along element normal*/
            };

            /** Distance option */
            public: enum DistanceType
            {
                DistanceTypePerCopy/** per copy distance*/,
                DistanceTypeTotal/** total distance*/
            };

            private: friend class  _ElementExtrudeBuilderBuilder;
            protected: ElementExtrudeBuilder();
            /**Returns  the element dimension option  <br> License requirements : None */
            public: NXOpen::CAE::ElementExtrudeBuilder::ElemDimType ElementDimensionOption
            (
            );
            /**Sets  the element dimension option  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetElementDimensionOption
            (
                NXOpen::CAE::ElementExtrudeBuilder::ElemDimType elementDimensionOption /** elementdimensionoption */ 
            );
            /**Returns  the element neutral name  <br> License requirements : None */
            public: NXString NeutralName
            (
            );
            /**Sets  the element neutral name  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetNeutralName
            (
                const NXString & neutralName /** neutralname */ 
            );
            /**Returns  the mesh collector name  <br> License requirements : None */
            public: NXString CollectorName
            (
            );
            /**Sets  the mesh collector name  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetCollectorName
            (
                const NXString & collectorName /** collectorname */ 
            );
            /**Returns  the new mesh option  <br> License requirements : None */
            public: NXOpen::CAE::ElementExtrudeBuilder::NewMeshType NewMeshOption
            (
            );
            /**Sets  the new mesh option  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetNewMeshOption
            (
                NXOpen::CAE::ElementExtrudeBuilder::NewMeshType newMeshOption /** newmeshoption */ 
            );
            /**Returns  the mesh name  <br> License requirements : None */
            public: NXString MeshName
            (
            );
            /**Sets  the mesh name  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetMeshName
            (
                const NXString & meshName /** meshname */ 
            );
            /**Returns  the selected elements  <br> License requirements : None */
            public: NXOpen::CAE::SelectElementsBuilder * Elements
            (
            );
            /**Returns  the number of copy  <br> License requirements : None */
            public: int NumberOfCopy
            (
            );
            /**Sets  the number of copy  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetNumberOfCopy
            (
                int numberOfCopy /** numberofcopy */ 
            );
            /**Returns  the method option  <br> License requirements : None */
            public: NXOpen::CAE::ElementExtrudeBuilder::MethodType MethodOption
            (
            );
            /**Sets  the method option  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetMethodOption
            (
                NXOpen::CAE::ElementExtrudeBuilder::MethodType methodOption /** methodoption */ 
            );
            /**Returns  the vector when extrude along vector  <br> License requirements : None */
            public: NXOpen::Direction * Vector
            (
            );
            /**Sets  the vector when extrude along vector  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetVector
            (
                NXOpen::Direction * vector /** vector */ 
            );
            /**Returns  the face when extrude by project to surface  <br> License requirements : None */
            public: NXOpen::CAE::SelectCAEFaceList * Face
            (
            );
            /**Returns  the percent offset  <br> License requirements : None */
            public: double PercentOffset
            (
            );
            /**Sets  the percent offset  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetPercentOffset
            (
                double percentOffset /** percentoffset */ 
            );
            /**Returns  the edge when extrude along path  <br> License requirements : None */
            public: NXOpen::CAE::SelectCAEEdge * Edge
            (
            );
            /** Flip the direction of extrude - not journalled  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void Flip
            (
            );
            /**Returns  the flip state from the builder  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: int FlipState
            (
            );
            /**Sets  the flip state from the builder  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetFlipState
            (
                int flipstate /** flipstate */ 
            );
            /**Returns  the distance option  <br> License requirements : None */
            public: NXOpen::CAE::ElementExtrudeBuilder::DistanceType DistanceOption
            (
            );
            /**Sets  the distance option  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetDistanceOption
            (
                NXOpen::CAE::ElementExtrudeBuilder::DistanceType distanceOption /** distanceoption */ 
            );
            /**Returns  the distance  <br> License requirements : None */
            public: NXOpen::Expression * Distance
            (
            );
            /**Returns  the twist origin  <br> License requirements : None */
            public: NXOpen::Point * TwistOrigin
            (
            );
            /**Sets  the twist origin  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetTwistOrigin
            (
                NXOpen::Point * twistOrigin /** twistorigin */ 
            );
            /**Returns  the twist angle  <br> License requirements : None */
            public: NXOpen::Expression * TwistAngle
            (
            );
            /**Returns  the label  <br> License requirements : None */
            public: int Label
            (
            );
            /**Sets  the label  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetLabel
            (
                int label /** label */ 
            );
            /**Returns  the increment  <br> License requirements : None */
            public: int Increment
            (
            );
            /**Sets  the increment  <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void SetIncrement
            (
                int increment /** increment */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
