#ifndef NXOpen_ROUTING_BENDCORNERCOLLECTION_HXX_INCLUDED
#define NXOpen_ROUTING_BENDCORNERCOLLECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Routing_BendCornerCollection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/TaggedObjectCollection.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Routing
    {
        class BendCornerCollection;
    }
    namespace Routing
    {
        class RouteManager;
    }
    namespace Routing
    {
        class BendCorner;
    }
    namespace Routing
    {
        class ControlPoint;
    }
    namespace Routing
    {
        class ISegment;
    }
    namespace Routing
    {
        /** Represents a collection of @link Routing::BendCorner Routing::BendCorner@endlink  objects.  <br> To obtain an instance of this class, refer to @link Routing::RouteManager Routing::RouteManager@endlink  <br> */
        class NXOPENCPPEXPORT BendCornerCollection : public TaggedObjectCollection
        {
            /** Option for creating a bend using a bend table or using radius or ratio */
            public: enum Type
            {
                TypeRadiusRatio/** Using radius or ratio to  
                                                                  create a bend corner. */,
                TypeTable/**  Using a bend table to create a  
                                                                  bend corner. */
            };

            private: NXOpen::Routing::RouteManager* m_owner;
            public: explicit BendCornerCollection(NXOpen::Routing::RouteManager *owner): m_owner(owner)
            {
            }
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            /** Iterator for accessing the contents of the collection. */
            class iterator
            {
            public:
                typedef Routing::BendCorner * value_type;
                /** Default constructor */
                iterator() : m_context(NULL), m_current(NULL_TAG)
                {
                }
                explicit iterator(NXOpen::Routing::BendCornerCollection *context) : m_context(context), m_current(NULL_TAG)
                {
                }
                iterator(const iterator &other)
                {
                    copy(other);
                }
                /** Copy constructor */
                iterator &operator =(const iterator &other)
                {
                    if (&other != this)
                        copy(other);
                    return *this;
                }
                /** Tests if the iterator objects on the left side and the right side of the operator are equal. */
                bool operator ==(const iterator &other) const
                {
                    return m_current == other.m_current && m_context == other.m_context;
                }
                /** Tests if the iterator objects on the left side and the right side of the operator are not equal. */
                bool operator !=(const iterator &other) const
                {
                    return !operator == (other);
                }
                /** Return the element currently pointed to by the iterator. */
                NXOPENCPPEXPORT  value_type operator * ();
                /** Points the iterator to next element. */
                iterator & operator ++()
                {
                    next();
                    return *this;
                }
                /** Points the iterator to next element. */
                iterator operator ++(int)
                {
                    iterator tmp(*this);
                    ++*this;
                    return tmp;
                }
            private:
                void copy(const iterator &other)
                {
                    m_context = other.m_context;
                    m_current = other.m_current;
                    for (int i = 0; i < sizeof(m_state)/sizeof(m_state[0]); i++)
                         m_state[i] = other.m_state[i];
                }
                NXOPENCPPEXPORT  void next();
                NXOpen::Routing::BendCornerCollection *m_context;
                tag_t m_current;
                unsigned int m_state[8];
            };
            /** Returns an iterator addressing the first element. */
            iterator begin();
            /** Returns an iterator addressing one past the last element. */
            iterator end()
            {
                return iterator(this);
            }
            /** Create a bend corner object at a Control Point.  @return  The new bend corner.  <br> License requirements : routing_combined ("Routing Combined") OR routing_electrical ("Routing Electrical") OR routing_mechanical ("Routing Mechanical") */
            public: NXOpen::Routing::BendCorner * Create
            (
                NXOpen::Routing::ControlPoint * rcp /** Route control point to bend. */,
                bool useBendRatio /** TRUE: use bend ratio calculation,
                                                               FALSE: use given radius */,
                double bendRatio /** Bend ratio only used if use_bend_ratio is 
                                                               TRUE. Must be greater than 0.5. */,
                double bendRadius /** Radius of bend corner arc, only used if 
                                                               use_bend_ratio is FALSE. Must be greater than 
                                                               0. */
            );
            /** This routine assigns a bend corner to the given input RCP object using
                        a bend table entry. This "assignment" can involve the removal of an existing
                        corner at this location and the creation of a new corner.  The
                        application view must be loaded before attempting to assign a 
                        bend corner of this type.   @return  The newly created Bend Corner  <br> License requirements : routing_combined ("Routing Combined") OR routing_electrical ("Routing Electrical") OR routing_mechanical ("Routing Mechanical") */
            public: NXOpen::Routing::BendCorner * AssignCornerByBendTable
            (
                NXOpen::Routing::ControlPoint * rcp /** Control point to assign corner to.  
                												    NULL not allowed. */,
                const NXString & bendTable /** The bend table entry that
                                                                       is used to create bend corner   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** This routine assigns a new bend corner to the given input bend corner object using
                        bend ratio. This "assignment" can involve the removal of an existing 
                        corner at this location and the creation of a new corner.  @return  The newly created Bend Corner  <br> License requirements : routing_combined ("Routing Combined") OR routing_electrical ("Routing Electrical") OR routing_mechanical ("Routing Mechanical") */
            public: NXOpen::Routing::BendCorner * AssignCornerByBendRatio
            (
                NXOpen::Routing::ControlPoint * bendCrn /** Input bend corner.  */,
                double bendRatio /** Bend ratio must be greater than 0.5. */
            );
            /** This routine assigns a new bend corner to the given input bend corner object using
                        bend radius. This "assignment" can involve the removal of an existing 
                        corner at this location and the creation of a new corner.  @return  The newly created Bend Corner  <br> License requirements : routing_combined ("Routing Combined") OR routing_electrical ("Routing Electrical") OR routing_mechanical ("Routing Mechanical") */
            public: NXOpen::Routing::BendCorner * AssignCornerByBendRadius
            (
                NXOpen::Routing::ControlPoint * bendCrn /** Input bend corner. */,
                double bendRadius /** Radius of bend corner arc. */
            );
            /** Enquire the Bend Corner that this segment represents.
                         (NULL can be returned, indicating that this segment does not
                         represent a Bend Corner.)  @return  Bend Corner that segment represents 
                                                          (NULL can be returned,indicating that 
                                                           segment does not represent a Bend Corner).  <br> License requirements : routing_combined ("Routing Combined") OR routing_electrical ("Routing Electrical") OR routing_mechanical ("Routing Mechanical") */
            public: NXOpen::Routing::BendCorner * GetBendAssociatedToSegment
            (
                NXOpen::Routing::ISegment * segment /** Segment being queried for the 
                                                               Bend Corner it represents. */
            );
            public: virtual void initialize();
        };
    }
}
#undef EXPORTLIBRARY
#endif
