#ifndef NXOpen_CAE_BEAMELEMENTINFO_HXX_INCLUDED
#define NXOpen_CAE_BEAMELEMENTINFO_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_BeamElementInfo.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_BeamSection.hxx>
#include <NXOpen/TransientObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class BeamElementInfo;
    }
    namespace CAE
    {
        class BeamSection;
    }
    namespace CAE
    {
        class FENode;
    }
    namespace CAE
    {
    }
    namespace CAE
    {
        class BeamElementInfoImpl;
        /** Represents a Beam Element Information.  <br> To obtain an instance of this class use CAE::BeamElementInfoHandler::AskElemInfo  <br> 
         <br>  Created in NX11.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  BeamElementInfo : public NXOpen::TransientObject
        {
            private: BeamElementInfoImpl * m_beamelementinfo_impl;
            /// \cond NX_NO_DOC 
            public: explicit BeamElementInfo(void *ptr);
            /// \endcond 
            /** Destroys the object 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: virtual ~BeamElementInfo();
            /**Returns  a boolean value that indicates whether the beam element is a tapered beam element. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: bool IsTapered
            (
            );
            /**Returns  the orientation node.
                        Orientation node is returned as NULL if the beam orientation is defined by a vector.
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::FENode * OrientationNode
            (
            );
            /**Returns  the orientation direction. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::BeamSection::DirectionOption OrientationDirection
            (
            );
            /**Returns  the orientation vector of the beam element.
                        
                        If the beam orientation is defined by a node, it returns the vector which points from the fore end node to the orientation node.
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Vector3d OrientationVector
            (
            );
            /**Returns  the beam orientation coordinate system.
                        
                        Axis x is from the fore end node with offset to the aft end node with offset.
                        <ol>
                        <li>
                        When the beam orientation is defined by a vector:
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionHorizontal CAE::BeamSection::DirectionOptionHorizontal@endlink ,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                         <br> 
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionVertical CAE::BeamSection::DirectionOptionVertical@endlink ,
                        axis y is to multiply across axis x and the orientation vector,
                        axis z is to multiply across axis x and axis y.
                         <br> 
                        </li>
                        <li>
                        When the beam orientation is defined by a node, the orientation vector is the vector
                        which is from the fore end node with offset to the orientation node,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                        </li>
                        </ol>
                        
                    
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Matrix3x3 OrientationCoordinateSystem
            (
            );
            /**Returns  a boolean value that indicates whether a cross section object is assigned to the fore end of the beam element.
                        
                        <ol>
                        <li>
                         <br> 
                        To a constant beam element, when a cross section is defined in the beam mesh physical properties,
                        the section is assigned to both ends of the beam element.
                         <br> 
                        </li>
                        <li>
                        To a tapered beam element:
                         <br> 
                        When two cross sections are defined to the end nodes of the beam chain in the beam mesh physical properties,
                        the fore section is assigned to the fore end of the fore beam element of the beam chain,
                        the aft section is assigned to the aft end of the aft beam element of the beam chain,
                        the section at the other ends are interpolated with these two sections.
                         <br> 
                         <br> 
                        When two cross sections are defined to each element in the beam mesh physical properties,
                        the fore section is assigned to the fore end of each element of the beam chain,
                        the aft section is assigned to the aft end of each element of the beam chain.
                         <br> 
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: bool HasSectionAssignedAtForeEnd
            (
            );
            /**Returns  a boolean value that indicates whether a cross section object is assigned to the aft end of the beam element.
                        
                        <ol>
                        <li>
                         <br> 
                        To a constant beam element, when a cross section is defined in the beam mesh physical properties,
                        the section is assigned to both ends of the beam element.
                         <br> 
                        </li>
                        <li>
                        To a tapered beam element:
                         <br> 
                        When two cross sections are defined to the end nodes of the beam chain in the beam mesh physical properties,
                        the fore section is assigned to the fore end of the fore beam element of the beam chain,
                        the aft section is assigned to the aft end of the aft beam element of the beam chain,
                        the section at the other ends are interpolated with these two sections.
                         <br> 
                         <br> 
                        When two cross sections are defined to each element in the beam mesh physical properties,
                        the fore section is assigned to the fore end of each element of the beam chain,
                        the aft section is assigned to the aft end of each element of the beam chain.
                         <br> 
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: bool HasSectionAssignedAtAftEnd
            (
            );
            /**Returns  the cross section at the fore end of the beam element.
                        
                        There are two cases that no section can be queried:
                        <ol>
                        <li>
                        No section is assigned to the beam physical property table.
                        </li>
                        <li>
                         <br> 
                        It is a tapered beam mesh. The section of the beam element is interpolated, not a real section.
                        To this case, user could access the section properties.
                         <br> 
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::BeamSection * SectionAtForeEnd
            (
            );
            /**Returns  the cross section at the aft end of the beam element.
                        
                        There are two cases that no section can be queried:
                        <ol>
                        <li>
                        No section is assigned to the beam physical property table.
                        </li>
                        <li>
                         <br> 
                        It is a tapered beam mesh. The section of the beam element is interpolated, not a real section.
                        To this case, user could access the section properties.
                         <br> 
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::BeamSection * SectionAtAftEnd
            (
            );
            /**Returns  the section properties at the fore end of the beam element.
                        
                         <br> 
                        The section properties are not generated only when cross sections are not fully defined in the beam mesh physical properties.
                         <br> 
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::BeamSection::Properties SectionPropertiesAtForeEnd
            (
            );
            /**Returns  the section properties at the aft end of the beam element.
                        
                         <br> 
                        The section properties are not generated only when cross sections are not fully defined in the beam mesh physical properties.
                         <br> 
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::CAE::BeamSection::Properties SectionPropertiesAtAftEnd
            (
            );
            /**Returns  the new position with offset of the section centroid at the fore end of the beam element in the global coordinate system. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Point3d OffsetSectionCentroidAtForeEnd
            (
            );
            /**Returns  the new position with offset of the section centroid at the aft end of the beam element in the global coordinate system. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Point3d OffsetSectionCentroidAtAftEnd
            (
            );
            /**Returns  the new position with offset of the section shear center at the fore end of the beam element in the global coordinate system. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Point3d OffsetSectionShearCenterAtForeEnd
            (
            );
            /**Returns  the new position with offset of the section shear center at the aft end of the beam element in the global coordinate system. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Point3d OffsetSectionShearCenterAtAftEnd
            (
            );
            /**Returns   @brief 
                        the neutral offset at the fore end of the beam element,
                        that is to offset the centroid of the cross section at the fore end of the beam element
                        to the fore node of the beam element in the neutral coordinate system.
                         

             
                        
                        For the neutral coordinate system, its axis x is the element axis.
                        <ol>
                        <li>
                        When the beam orientation is defined by a vector:
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionHorizontal CAE::BeamSection::DirectionOptionHorizontal@endlink ,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                         <br> 
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionVertical CAE::BeamSection::DirectionOptionVertical@endlink ,
                        axis y is to multiply across axis x and the orientation vector,
                        axis z is to multiply across axis x and axis y.
                         <br> 
                        </li>
                        <li>
                        When the beam orientation is defined by a node, the orientation vector is the vector
                        which is from the fore end node to the orientation node,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Vector3d NeutralOffsetAtForeEnd
            (
            );
            /**Returns   @brief 
                        the neutral offset at the aft end of the beam element,
                        that is to offset the centroid of the cross section at the aft end of the beam element
                        to the aft node of the beam element in the neutral coordinate system.
                         

             
                        
                        For the neutral coordinate system, its axis x is the element axis.
                        <ol>
                        <li>
                        When the beam orientation is defined by a vector:
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionHorizontal CAE::BeamSection::DirectionOptionHorizontal@endlink ,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                         <br> 
                         <br> 
                        If orientation direction is @link CAE::BeamSection::DirectionOptionVertical CAE::BeamSection::DirectionOptionVertical@endlink ,
                        axis y is to multiply across axis x and the orientation vector,
                        axis z is to multiply across axis x and axis y.
                         <br> 
                        </li>
                        <li>
                        When the beam orientation is defined by a node, the orientation vector is the vector
                        which is from the fore end node to the orientation node,
                        axis z is to multiply across axis x and the orientation vector,
                        axis y is to multiply across axis z and axis x.
                        </li>
                        </ol>
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Vector3d NeutralOffsetAtAftEnd
            (
            );
            /**Returns   @brief 
                        the language specific offset at the fore end of the beam element,
                        that is to offset the shear center of the cross section at the fore end of the beam element
                        to the fore node of the beam element in the nodal displacement coordinate system
                        when current solver is Nastran solver.
                         

             
                        
                        For other solvers, it is same with the neutral offset at the fore end of the beam element.
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Vector3d LanguageOffsetAtForeEnd
            (
            );
            /**Returns   @brief 
                        the language specific offset at the aft end of the beam element,
                        that is to offset the shear center of the cross section at the fore end of the beam element
                        to the fore node of the beam element in the nodal displacement coordinate system
                        when current solver is Nastran solver.
                         

             
                        
                        For other solvers, it is same with the neutral offset at the aft end of the beam element.
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: NXOpen::Vector3d LanguageOffsetAtAftEnd
            (
            );
            /** Returns the end releases at the fore end of the beam element, that are referred to as pin flags in Nastran.
                        
                         <br> 
                        The values of the end releases are either 0 or 1, 1 represents removing connection between
                        the fore node and selected degrees of freedom, 0 represents not removing the connection.
                         <br> 
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void GetEndReleasesAtForeEnd
            (
                std::vector<int> & endReleases /** endreleases */ 
            );
            /** Returns the end releases at the aft end of the beam element, that are referred to as pin flags in Nastran.
                        
                         <br> 
                        The values of the end releases are either 0 or 1, 1 represents removing connection between
                        the aft node and selected degrees of freedom, 0 represents not removing the connection.
                         <br> 
                        
                     
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void GetEndReleasesAtAftEnd
            (
                std::vector<int> & endReleases /** endreleases */ 
            );
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
