#ifndef NXOpen_FEATURES_SUBDIVISION_SUBDIVISIONREVOLVEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SUBDIVISION_SUBDIVISIONREVOLVEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_Subdivision_SubdivisionRevolveBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_Subdivision_SelectCageObjectData.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace Subdivision
        {
            class SubdivisionRevolveBuilder;
        }
    }
    class Builder;
    class Direction;
    class Expression;
    namespace Features
    {
        namespace Subdivision
        {
            class SelectCageObjectData;
        }
    }
    class SelectNXObject;
    namespace Features
    {
        namespace Subdivision
        {
            class _SubdivisionRevolveBuilderBuilder;
            class SubdivisionRevolveBuilderImpl;
            /** Represents a @link NXOpen::Features::Subdivision::SubdivisionRevolveBuilder NXOpen::Features::Subdivision::SubdivisionRevolveBuilder@endlink  builder.  <br> To create a new instance of this class, use @link NXOpen::Features::Subdivision::SubdivisionBodyCollection::CreateSubdivisionRevolveBuilder  NXOpen::Features::Subdivision::SubdivisionBodyCollection::CreateSubdivisionRevolveBuilder @endlink  <br> 
            Default values.
            <list type="table"> 
             
            <listheader><term> 
            Property</term>  <description> 
            Value</description> </listheader>
            <item><term> 
             
            CanSew </term> <description> 
             
            1 </description> </item> 

            <item><term> 
             
            EndAngle.Value </term> <description> 
             
            360 </description> </item> 

            <item><term> 
             
            NumOfSegments </term> <description> 
             
            8 </description> </item> 

            <item><term> 
             
            StartAngle.Value </term> <description> 
             
            0 </description> </item> 

            </list> 

             <br>  Created in NX10.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  SubdivisionRevolveBuilder : public NXOpen::Builder
            {
                /** Type of continuity. */
                public: enum ContinuityType
                {
                    ContinuityTypeSmooth/** Smooth continuity */,
                    ContinuityTypeSharp/** Sharp continuity */
                };

                private: SubdivisionRevolveBuilderImpl * m_subdivisionrevolvebuilder_impl;
                private: friend class  _SubdivisionRevolveBuilderBuilder;
                protected: SubdivisionRevolveBuilder();
                public: ~SubdivisionRevolveBuilder();
                /**Returns  the section as revolving profile. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::Subdivision::SelectCageObjectData * SectionObject
                (
                );
                /**Returns  the axis of revolution. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Direction * AxisVector
                (
                );
                /**Sets  the axis of revolution. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_subdivision (" NX SUBDIVISION") */
                public: void SetAxisVector
                (
                    NXOpen::Direction * axisVector /** axisvector */ 
                );
                /**Returns  the origin of the axis of revolution. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectNXObject * AxisPoint
                (
                );
                /**Returns  the start of angular dimension. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * StartAngle
                (
                );
                /**Returns  the end of angular dimension. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * EndAngle
                (
                );
                /**Returns  the number of segments. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: int NumOfSegments
                (
                );
                /**Sets  the number of segments. 
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_subdivision (" NX SUBDIVISION") */
                public: void SetNumOfSegments
                (
                    int numOfSegments /** numofsegments */ 
                );
                /**Returns  the value indicating if open edges of the revolve mesh can be sewn with selected input open edges.
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CanSew
                (
                );
                /**Sets  the value indicating if open edges of the revolve mesh can be sewn with selected input open edges.
                 <br>  Created in NX10.0.0.  <br>  
                 <br> License requirements : nx_subdivision (" NX SUBDIVISION") */
                public: void SetCanSew
                (
                    bool canSew /** cansew */ 
                );
                /**Returns  the continuity. The continuity is used to specify creases in the limit surface corresponding to edges
                                of the revolved region that are sewn with the primary existing region. 
                 <br>  Created in NX11.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::Subdivision::SubdivisionRevolveBuilder::ContinuityType Continuity
                (
                );
                /**Sets  the continuity. The continuity is used to specify creases in the limit surface corresponding to edges
                                of the revolved region that are sewn with the primary existing region. 
                 <br>  Created in NX11.0.0.  <br>  
                 <br> License requirements : nx_subdivision (" NX SUBDIVISION") */
                public: void SetContinuity
                (
                    NXOpen::Features::Subdivision::SubdivisionRevolveBuilder::ContinuityType continuity /** continuity */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
