#ifndef NXOpen_FEATURES_OFFSETCURVEBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_OFFSETCURVEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_OffsetCurveBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/GeometricUtilities_CurveFitData.hxx>
#include <NXOpen/GeometricUtilities_CurveFitOptions.hxx>
#include <NXOpen/GeometricUtilities_CurveOptions.hxx>
#include <NXOpen/GeometricUtilities_LawBuilder.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        class OffsetCurveBuilder;
    }
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class CurveFitData;
    }
    namespace GeometricUtilities
    {
        class CurveFitOptions;
    }
    namespace GeometricUtilities
    {
        class CurveOptions;
    }
    namespace GeometricUtilities
    {
        class LawBuilder;
    }
    class ICurve;
    class Point;
    class Section;
    namespace Features
    {
        class _OffsetCurveBuilderBuilder;
        class OffsetCurveBuilderImpl;
        /** Represents a @link NXOpen::Features::OffsetCurve NXOpen::Features::OffsetCurve@endlink  builder  <br> To create a new instance of this class, use @link NXOpen::Features::FeatureCollection::CreateOffsetCurveBuilder  NXOpen::Features::FeatureCollection::CreateOffsetCurveBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        CurveFitData.CurveJoinMethod </term> <description> 
         
        No </description> </item> 

        <item><term> 
         
        CurveFitData.Degree </term> <description> 
         
        7 </description> </item> 

        <item><term> 
         
        CurveFitData.FitMethod </term> <description> 
         
        DegreeAndSegments </description> </item> 

        <item><term> 
         
        CurveFitData.IsAdvancedFit </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        CurveFitData.IsAlignShape </term> <description> 
         
        0 </description> </item> 

        <item><term> 
         
        CurveFitData.MaximumDegree </term> <description> 
         
        7 </description> </item> 

        <item><term> 
         
        CurveFitData.MaximumSegments </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        CurveFitData.MinimumDegree </term> <description> 
         
        5 </description> </item> 

        <item><term> 
         
        CurveFitData.Segments </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        CurveFitMethod.FitOption </term> <description> 
         
        Cubic </description> </item> 

        <item><term> 
         
        CurveFitMethod.MaximumDegree </term> <description> 
         
        7 </description> </item> 

        <item><term> 
         
        CurveFitMethod.MaximumSegments </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        DraftAngle.Value </term> <description> 
         
        0.0 </description> </item> 

        <item><term> 
         
        DraftHeight.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        ExtendFactor (deprecated) </term> <description> 
         
        1.0 </description> </item> 

        <item><term> 
         
        GroupObjects </term> <description> 
         
        false </description> </item> 

        <item><term> 
         
        InputCurvesOptions.Associative </term> <description> 
         
        true </description> </item> 

        <item><term> 
         
        LawControl.EndValue.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        LawControl.Function </term> <description> 
         
        ft </description> </item> 

        <item><term> 
         
        LawControl.LawType </term> <description> 
         
        Constant </description> </item> 

        <item><term> 
         
        LawControl.Parameter </term> <description> 
         
        t </description> </item> 

        <item><term> 
         
        LawControl.StartValue.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        LawControl.Value.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        NumberOfCopies </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        Offset3dDistance.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        OffsetDistance.Value </term> <description> 
         
        5.0 (millimeters part), 0.25 (inches part) </description> </item> 

        <item><term> 
         
        RoughOffset </term> <description> 
         
        false </description> </item> 

        <item><term> 
         
        TrimMethod </term> <description> 
         
        ExtendTangents </description> </item> 

        <item><term> 
         
        Type </term> <description> 
         
        Distance </description> </item> 

        </list> 

         <br>  Created in NX5.0.0.  <br>  
        */
        class NXOPENCPP_FEATURESEXPORT  OffsetCurveBuilder : public NXOpen::Features::FeatureBuilder
        {
            /** Represents the Offset Curve trim option */
            public: enum TrimOption
            {
                TrimOptionNone/** None */,
                TrimOptionExtendTangents/** Extend Tangents */,
                TrimOptionFillet/** Fillet */
            };

            /** Represents the Offset Curve types */
            public: enum Types
            {
                TypesDistance/** Distance */,
                TypesDraft/** Draft */,
                TypesLawControl/** Law Control */,
                TypesAxial3d/** 3D Axial */
            };

            private: OffsetCurveBuilderImpl * m_offsetcurvebuilder_impl;
            private: friend class  _OffsetCurveBuilderBuilder;
            protected: OffsetCurveBuilder();
            public: ~OffsetCurveBuilder();
            /**Returns  the offset type 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::OffsetCurveBuilder::Types Type
            (
            );
            /**Sets  the offset type 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetType
            (
                NXOpen::Features::OffsetCurveBuilder::Types type /** type */ 
            );
            /**Returns  the curves to offset 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Section * CurvesToOffset
            (
            );
            /**Returns  the point on offset plane 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Point * PointOnOffsetPlane
            (
            );
            /**Sets  the point on offset plane 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetPointOnOffsetPlane
            (
                NXOpen::Point * pointOnOffsetPlane /** pointonoffsetplane */ 
            );
            /**Returns  the distance 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * OffsetDistance
            (
            );
            /**Returns  the height 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * DraftHeight
            (
            );
            /**Returns  the angle 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * DraftAngle
            (
            );
            /**Returns  the Law builder 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * LawControl
            (
            );
            /**Returns  the offset3d 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Expression * Offset3dDistance
            (
            );
            /**Returns  the direction 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Direction * AxialOffsetDirection
            (
            );
            /**Sets  the direction 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetAxialOffsetDirection
            (
                NXOpen::Direction * direction /** direction */ 
            );
            /**Returns  the number of copies 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: int NumberOfCopies
            (
            );
            /**Sets  the number of copies 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetNumberOfCopies
            (
                int numberOfCopies /** numberofcopies */ 
            );
            /**Returns  the reverse direction 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: bool ReverseDirection
            (
            );
            /**Sets  the reverse direction 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetReverseDirection
            (
                bool reverseDirection /** reversedirection */ 
            );
            /**Returns  the input curves 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::CurveOptions * InputCurvesOptions
            (
            );
            /**Returns  the trim 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Features::OffsetCurveBuilder::TrimOption TrimMethod
            (
            );
            /**Sets  the trim 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetTrimMethod
            (
                NXOpen::Features::OffsetCurveBuilder::TrimOption trim /** trim */ 
            );
            /**Returns  the extend factor 
             <br>  @deprecated Deprecated in NX11.0.0.  Extend factor functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX11.0.0.  Extend factor functionality is no longer supported.") double ExtendFactor
            (
            );
            /**Sets  the extend factor 
             <br>  @deprecated Deprecated in NX11.0.0.  Extend factor functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: NX_DEPRECATED("Deprecated in NX11.0.0.  Extend factor functionality is no longer supported.") void SetExtendFactor
            (
                double extendFactor /** extendfactor */ 
            );
            /**Returns  the group objects 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: bool GroupObjects
            (
            );
            /**Sets  the group objects 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetGroupObjects
            (
                bool groupObjects /** groupobjects */ 
            );
            /**Returns  the rough offset 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: bool RoughOffset
            (
            );
            /**Sets  the rough offset 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetRoughOffset
            (
                bool roughOffset /** roughoffset */ 
            );
            /**Returns  the curve fit method 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::CurveFitOptions * CurveFitMethod
            (
            );
            /**Returns  the curve fit settings 
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::GeometricUtilities::CurveFitData * CurveFitData
            (
            );
            /**Returns  the distance tolerance 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: double Tolerance
            (
            );
            /**Sets  the distance tolerance 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void SetTolerance
            (
                double tolerance /** tolerance */ 
            );
            /** To compute offset direction. To compute offset direction whenever it is required or needs to be updated. 
             <br>  Created in NX7.5.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void ComputeOffsetDirection
            (
                NXOpen::Vector3d* offsetDirection /** direction of offset */,
                NXOpen::Point3d* startPoint /** start point of direction */
            );
            /** To compute offset direction on the seed entity at the given seed point. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
            public: void ComputeOffsetDirection
            (
                NXOpen::ICurve * seedEntity /** seed entity that is part of section of offset curve builder */,
                const NXOpen::Point3d & seedPoint /** seed point on the seed entity at which to compute the offset direction */,
                NXOpen::Vector3d* offsetDirection /** direction of offset at seed point on seed entity */,
                NXOpen::Point3d* startPoint /** start point of entities in section of offset curve */
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
