#ifndef NXOpen_CAE_SELECTFENODE_HXX_INCLUDED
#define NXOpen_CAE_SELECTFENODE_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_SelectFENode.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
#include <NXOpen/InferSnapType.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace CAE
    {
        class SelectFENode;
    }
    namespace CAE
    {
        class FENode;
    }
    namespace GeometricUtilities
    {
        class IComponentBuilder;
    }
    class View;
    namespace CAE
    {
        class _SelectFENodeBuilder;
        /** Represents a single object selection.
        */
        class NXOPENCPPEXPORT SelectFENode : public TaggedObject, public virtual GeometricUtilities::IComponentBuilder
        {
            private: friend class  _SelectFENodeBuilder;
            protected: SelectFENode();
            /**Sets  the object being selected
                 <br> License requirements : None */
            public: void SetValue
            (
                NXOpen::CAE::FENode * selection /** selected object */
            );
            /**Returns  the object being selected
                 <br> License requirements : None */
            public: NXOpen::CAE::FENode * Value
            (
            );
            /** The object being selected with the object's view and object's point
                 <br> License requirements : None */
            public: void SetValue
            (
                NXOpen::CAE::FENode * selection /** selected object */,
                NXOpen::View * view /** selected object view*/,
                const NXOpen::Point3d & point /** selected object point*/
            );
            /** The object being selected with the object's view and point.
                 <br> License requirements : None */
            public: void GetValue
            (
                NXOpen::CAE::FENode ** selection /** selected object */,
                NXOpen::View ** view /** selected object view*/,
                NXOpen::Point3d* point /** selected object point*/
            );
            /** The object being selected with the objects view and objects point and snap information.
                 <br> License requirements : None */
            public: void SetValue
            (
                NXOpen::InferSnapType::SnapType snap_type /**  snap point type*/,
                NXOpen::CAE::FENode * selection1 /** first selected object */,
                NXOpen::View * view1 /** first selected object view*/,
                const NXOpen::Point3d & point1 /** first selected object point*/,
                NXOpen::CAE::FENode * selection2 /** second selected object */,
                NXOpen::View * view2 /** second selected object view*/,
                const NXOpen::Point3d & point2 /** second selected object point*/
            );
            /** The object being selected with the objects view and point and snap information.
                 <br> License requirements : None */
            public: void GetValue
            (
                NXOpen::InferSnapType::SnapType* snap_type /**  snap point type*/,
                NXOpen::CAE::FENode ** selection1 /** first selected object */,
                NXOpen::View ** view1 /** first selected object view*/,
                NXOpen::Point3d* point1 /** first selected object point*/,
                NXOpen::CAE::FENode ** selection2 /** second selected object */,
                NXOpen::View ** view2 /** second selected object view*/,
                NXOpen::Point3d* point2 /** second selected object point*/
            );
            /** Returns true if the inputs to the component are sufficient for 
                        commit to be called.  For example, if the component requires
                        you to set some property, this method will return false if
                        you haven't set it.  This method throws a not-yet-implemented
                        NXException for some components.
                     @return  Was self validation successful  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: virtual bool Validate
            (
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
