#ifndef NXOpen_FEATURES_GLOBALSHAPINGBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_GLOBALSHAPINGBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_GlobalShapingBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_GlobalShapingBuilder.hxx>
#include <NXOpen/GeometricUtilities_LawBuilder.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class GlobalShapingBuilder;
    }
    class Direction;
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    namespace GeometricUtilities
    {
        class FeatureOptions;
    }
    namespace GeometricUtilities
    {
        class LawBuilder;
    }
    class Point;
    class ScCollector;
    class Section;
    namespace Features
    {
        class _GlobalShapingBuilderBuilder;
        /**
            Represents a @link Features::GlobalShaping Features::GlobalShaping@endlink  builder
             <br> To create a new instance of this class, use @link Features::FeatureCollection::CreateGlobalShapingBuilder Features::FeatureCollection::CreateGlobalShapingBuilder@endlink  <br> */
        class NXOPENCPPEXPORT GlobalShapingBuilder : public Features::FeatureBuilder
        {

            public: enum DeformationTypeValues
            {
                DeformationTypeValuesToPoint/** to point */ ,
                DeformationTypeValuesToCurves/** to curves */ ,
                DeformationTypeValuesOpenRegion/** open region */ ,
                DeformationTypeValuesWallDeformation/** wall deformation */ ,
                DeformationTypeValuesOverbend/** overbend */ ,
                DeformationTypeValuesMatchToSheet/** match to sheet */ ,
                DeformationTypeValuesStretchToPoint/** stretch to point */ ,
                DeformationTypeValuesStretchToCurve/** stretch to curve */ ,
                DeformationTypeValuesUnknown/** unknown */ 
            };


            public: enum PointMethodType
            {
                PointMethodTypeOffsetFromSheet/** offset from sheet */ ,
                PointMethodTypePointDefined/** point defined */ 
            };


            public: enum OffsetMethod
            {
                OffsetMethodConstant/** constant */ ,
                OffsetMethodLawControlled/** law controlled */ ,
                OffsetMethodCurveDefined/** curve defined */ 
            };


            public: enum RotationMethod
            {
                RotationMethodConstant/** constant */ ,
                RotationMethodLawControlled/** law controlled */ 
            };


            public: enum DirectionMethodType
            {
                DirectionMethodTypeSameAsProjection/** same as projection */ ,
                DirectionMethodTypeNormalToSheet/** normal to sheet */ 
            };


            public: enum TransitionType
            {
                TransitionTypeFunction1/** function1 */ ,
                TransitionTypeFunction2/** function2 */ ,
                TransitionTypeLaw/** law */ 
            };


            public: enum BodyMethod
            {
                BodyMethodSolid/** solid */ ,
                BodyMethodSheet/** sheet */ 
            };

            private: friend class  _GlobalShapingBuilderBuilder;
            protected: GlobalShapingBuilder();
            /**Returns  the deformation type  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::DeformationTypeValues DeformationType
            (
            );
            /**Sets  the deformation type  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDeformationType
            (
                NXOpen::Features::GlobalShapingBuilder::DeformationTypeValues deformationType /** deformationtype */ 
            );
            /**Returns  the sheet to deform  <br> License requirements : None */
            public: NXOpen::ScCollector * SheetToDeform
            (
            );
            /**Returns  the region to deform  <br> License requirements : None */
            public: NXOpen::ScCollector * RegionToDeform
            (
            );
            /**Returns  the bend curve  <br> License requirements : None */
            public: NXOpen::Section * BendCurve
            (
            );
            /**Returns  the region limit curve  <br> License requirements : None */
            public: NXOpen::ScCollector * RegionLimitCurve
            (
            );
            /**Returns  the region edge curve  <br> License requirements : None */
            public: NXOpen::ScCollector * RegionEdgeCurve
            (
            );
            /**Returns  the first region limit curve  <br> License requirements : None */
            public: NXOpen::ScCollector * FirstRegionLimitCurve
            (
            );
            /**Returns  the second region limit curve  <br> License requirements : None */
            public: NXOpen::ScCollector * SecondRegionLimitCurve
            (
            );
            /**Returns  the first region offset curve  <br> License requirements : None */
            public: NXOpen::ScCollector * FirstRegionOffsetCurve
            (
            );
            /**Returns  the second region offset curve  <br> License requirements : None */
            public: NXOpen::ScCollector * SecondRegionOffsetCurve
            (
            );
            /**Returns  the target sheet  <br> License requirements : None */
            public: NXOpen::ScCollector * TargetSheet
            (
            );
            /**Returns  the target point  <br> License requirements : None */
            public: NXOpen::Point * TargetPoint
            (
            );
            /**Sets  the target point  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTargetPoint
            (
                NXOpen::Point * targetPoint /** targetpoint */ 
            );
            /**Returns  the target point method  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::PointMethodType TargetPointMethod
            (
            );
            /**Sets  the target point method  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTargetPointMethod
            (
                NXOpen::Features::GlobalShapingBuilder::PointMethodType targetPointMethod /** targetpointmethod */ 
            );
            /**Returns  the target point offset  <br> License requirements : None */
            public: NXOpen::Expression * TargetPointOffset
            (
            );
            /**Returns  the target curve  <br> License requirements : None */
            public: NXOpen::Section * TargetCurve
            (
            );
            /**Returns  the target curve offset type  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::OffsetMethod TargetCurveOffsetType
            (
            );
            /**Sets  the target curve offset type  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTargetCurveOffsetType
            (
                NXOpen::Features::GlobalShapingBuilder::OffsetMethod targetCurveOffsetType /** targetcurveoffsettype */ 
            );
            /**Returns  the target curve offset  <br> License requirements : None */
            public: NXOpen::Expression * TargetCurveOffset
            (
            );
            /**Returns  the target curve offset law  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * TargetCurveOffsetLaw
            (
            );
            /**Returns  the first target curve  <br> License requirements : None */
            public: NXOpen::ScCollector * FirstTargetCurve
            (
            );
            /**Returns  the first target curve offset  <br> License requirements : None */
            public: NXOpen::Expression * FirstTargetCurveOffset
            (
            );
            /**Returns  the projection direction  <br> License requirements : None */
            public: NXOpen::Direction * ProjectionDirection
            (
            );
            /**Sets  the projection direction  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetProjectionDirection
            (
                NXOpen::Direction * projectionDirection /** projectiondirection */ 
            );
            /**Returns  the stretch direction  <br> License requirements : None */
            public: NXOpen::Direction * StretchDirection
            (
            );
            /**Sets  the stretch direction  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetStretchDirection
            (
                NXOpen::Direction * stretchDirection /** stretchdirection */ 
            );
            /**Returns  the second target curve  <br> License requirements : None */
            public: NXOpen::ScCollector * SecondTargetCurve
            (
            );
            /**Returns  the second target curve offset  <br> License requirements : None */
            public: NXOpen::Expression * SecondTargetCurveOffset
            (
            );
            /**Returns  the deformation direction method  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::DirectionMethodType DeformationDirectionMethod
            (
            );
            /**Sets  the deformation direction method  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDeformationDirectionMethod
            (
                NXOpen::Features::GlobalShapingBuilder::DirectionMethodType deformationDirectionMethod /** deformationdirectionmethod */ 
            );
            /**Returns  the deformation direction reverse  <br> License requirements : None */
            public: bool DeformationDirectionReverse
            (
            );
            /**Sets  the deformation direction reverse  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDeformationDirectionReverse
            (
                bool deformationDirectionReverse /** deformationdirectionreverse */ 
            );
            /**Returns  the rotation angle type  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::RotationMethod RotationAngleType
            (
            );
            /**Sets  the rotation angle type  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRotationAngleType
            (
                NXOpen::Features::GlobalShapingBuilder::RotationMethod rotationAngleType /** rotationangletype */ 
            );
            /**Returns  the rotation angle value  <br> License requirements : None */
            public: NXOpen::Expression * RotationAngle
            (
            );
            /**Returns  the rotation angle law  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * RotationAngleLaw
            (
            );
            /**Returns  the rotation angle reverse direction  <br> License requirements : None */
            public: bool RotationAngleReverseDirection
            (
            );
            /**Sets  the rotation angle reverse direction  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetRotationAngleReverseDirection
            (
                bool rotationAngleReverseDirection /** rotationanglereversedirection */ 
            );
            /**Returns  the transition options  <br> License requirements : None */
            public: NXOpen::Features::GlobalShapingBuilder::TransitionType TransitionOptions
            (
            );
            /**Sets  the transition options  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTransitionOptions
            (
                NXOpen::Features::GlobalShapingBuilder::TransitionType transitionOptions /** transitionoptions */ 
            );
            /**Returns  the transition law  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::LawBuilder * TransitionLaw
            (
            );
            /**Returns  the transition shape control  <br> License requirements : None */
            public: double TransitionShapeControl
            (
            );
            /**Sets  the transition shape control  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetTransitionShapeControl
            (
                double transitionShapeControl /** transitionshapecontrol */ 
            );
            /**Returns  the feature options  <br> License requirements : None */
            public: NXOpen::GeometricUtilities::FeatureOptions * FeatureOptions
            (
            );
            /**Returns  the modify input sheet  <br> License requirements : None */
            public: bool ModifyInputSheet
            (
            );
            /**Sets  the modify input sheet  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetModifyInputSheet
            (
                bool modifyInputSheet /** modifyinputsheet */ 
            );
            /**Returns  the distance tolerance  <br> License requirements : None */
            public: double DistanceTolerance
            (
            );
            /**Sets  the distance tolerance  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetDistanceTolerance
            (
                double distanceTolerance /** distancetolerance */ 
            );
            /**Returns  the angle tolerance  <br> License requirements : None */
            public: double AngleTolerance
            (
            );
            /**Sets  the angle tolerance  <br> License requirements : solid_modeling ("SOLIDS MODELING") */
            public: void SetAngleTolerance
            (
                double angleTolerance /** angletolerance */ 
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
