#ifndef NXOpen_LINE_HXX_INCLUDED
#define NXOpen_LINE_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Line.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Curve.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    class Line;
    class Curve;
    class _LineBuilder;
    /** Represents a line curve.  <br> To create a new instance of this class, use @link CurveCollection::CreateLine CurveCollection::CreateLine@endlink  <br> */
    class NXOPENCPPEXPORT Line : public Curve
    {
        private: friend class  _LineBuilder;
        protected: Line();
        /**Returns  the start point of the line  <br> License requirements : None */
        public: NXOpen::Point3d StartPoint
        (
        );
        /** <b>Deprecated</b>:<br>
        &nbsp;&nbsp;&nbsp;Use @link StartPoint() StartPoint@endlink instead.
        @deprecated
        */
        public: NXOpen::Point3d GetStartPoint
        (
        ) { return this->StartPoint(); }
        /**Returns  the end point of the line  <br> License requirements : None */
        public: NXOpen::Point3d EndPoint
        (
        );
        /** <b>Deprecated</b>:<br>
        &nbsp;&nbsp;&nbsp;Use @link EndPoint() EndPoint@endlink instead.
        @deprecated
        */
        public: NXOpen::Point3d GetEndPoint
        (
        ) { return this->EndPoint(); }
        /** Sets the start point of the line  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetStartPoint
        (
            const NXOpen::Point3d & start_point /** start point */ 
        );
        /** Sets the end point of the line  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetEndPoint
        (
            const NXOpen::Point3d & end_point /** end point */ 
        );
        /** Sets the start and end points of the line  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: void SetEndpoints
        (
            const NXOpen::Point3d & start_point /** the start point */,
            const NXOpen::Point3d & end_point /** the end point */
        );
    };
}
#undef EXPORTLIBRARY
#endif
