#ifndef NXOpen_SKETCHCOLLECTION_HXX_INCLUDED
#define NXOpen_SKETCHCOLLECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     SketchCollection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/ConvertToFromReferenceBuilder.hxx>
#include <NXOpen/InferredConstraintsBuilder.hxx>
#include <NXOpen/SketchAlongPathBuilder.hxx>
#include <NXOpen/SketchAutoConstrainBuilder.hxx>
#include <NXOpen/SketchCornerBuilder.hxx>
#include <NXOpen/SketchDimensionBuilder.hxx>
#include <NXOpen/SketchInDraftingBuilder.hxx>
#include <NXOpen/SketchInPlaceBuilder.hxx>
#include <NXOpen/SketchMirrorBuilder.hxx>
#include <NXOpen/SketchOffset.hxx>
#include <NXOpen/SketchOffsetBuilder.hxx>
#include <NXOpen/SketchProjectBuilder.hxx>
#include <NXOpen/SketchQuickExtendBuilder.hxx>
#include <NXOpen/SketchQuickTrimBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/TaggedObjectCollection.hxx>
#include <NXOpen/type.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    class SketchCollection;
    class Part;
    class Sketch;
    class ConvertToFromReferenceBuilder;
    namespace Features
    {
        class Feature;
    }
    namespace Features
    {
        class TrimCurveBuilder;
    }
    class IReferenceAxis;
    class ISurface;
    class InferredConstraintsBuilder;
    class NXObject;
    class SketchAlongPathBuilder;
    class SketchAutoConstrainBuilder;
    class SketchCornerBuilder;
    class SketchDimensionBuilder;
    class SketchDimensionalConstraint;
    class SketchInDraftingBuilder;
    class SketchInPlaceBuilder;
    class SketchIntersectionCurve;
    class SketchIntersectionCurveBuilder;
    class SketchIntersectionPoint;
    class SketchIntersectionPointBuilder;
    class SketchMirrorBuilder;
    class SketchOffset;
    class SketchOffsetBuilder;
    class SketchProjectBuilder;
    class SketchQuickExtendBuilder;
    class SketchQuickTrimBuilder;
    class SmartObject;
    class Spline;
    /** Represents a collection of sketches  <br> To obtain an instance of this class, refer to @link Part Part@endlink  <br> */
    class NXOPENCPPEXPORT SketchCollection : public TaggedObjectCollection
    {
        private: NXOpen::Part* m_owner;
        public: explicit SketchCollection(NXOpen::Part *owner): m_owner(owner)
        {
        }
        public: 
        /**Returns the tag of this object.  */
        tag_t Tag() const; 
        /** Iterator for accessing the contents of the collection. */
        class iterator
        {
        public:
            typedef Sketch * value_type;
            /** Default constructor */
            iterator() : m_context(NULL), m_current(NULL_TAG)
            {
            }
            explicit iterator(NXOpen::SketchCollection *context) : m_context(context), m_current(NULL_TAG)
            {
            }
            iterator(const iterator &other)
            {
                copy(other);
            }
            /** Copy constructor */
            iterator &operator =(const iterator &other)
            {
                if (&other != this)
                    copy(other);
                return *this;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are equal. */
            bool operator ==(const iterator &other) const
            {
                return m_current == other.m_current && m_context == other.m_context;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are not equal. */
            bool operator !=(const iterator &other) const
            {
                return !operator == (other);
            }
            /** Return the element currently pointed to by the iterator. */
            NXOPENCPPEXPORT  value_type operator * ();
            /** Points the iterator to next element. */
            iterator & operator ++()
            {
                next();
                return *this;
            }
            /** Points the iterator to next element. */
            iterator operator ++(int)
            {
                iterator tmp(*this);
                ++*this;
                return tmp;
            }
        private:
            void copy(const iterator &other)
            {
                m_context = other.m_context;
                m_current = other.m_current;
                for (int i = 0; i < sizeof(m_state)/sizeof(m_state[0]); i++)
                     m_state[i] = other.m_state[i];
            }
            NXOPENCPPEXPORT  void next();
            NXOpen::SketchCollection *m_context;
            tag_t m_current;
            unsigned int m_state[8];
        };
        /** Returns an iterator addressing the first element. */
        iterator begin();
        /** Returns an iterator addressing the last element. */
        iterator end()
        {
            return iterator(this);
        }
        /**
            Creates a sketch
             @return  the new sketch  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Sketch * CreateSketch
        (
            const NXString & name /** Name of the sketch.  The name will be converted to upper case. If this is an empty string or NULL, a name will be provided by the system.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
            NXOpen::ISurface * attachment_plane /** A face or datum plane that the sketch will be attached to.  Must be planar. */,
            NXOpen::IReferenceAxis * reference_axis /** Can be a datum axis, edge, datum plane, face, or NULL.
                                                                    If it is an edge, the edge must be a line segment.  If it is a face, the
                                                                    face must be a plane.  If NULL, the reference_direction is used instead */,
            const NXOpen::Vector3d & reference_direction /** If reference_axis is NULL,
                                                          this parameter sets the reference direction of the sketch.
                                                          In this case, this parameter must not be (0,0,0).
                                                          If reference_axis is not NULL
                                                          and this parameter is not (0,0,0), this parameter
                                                          determines whether the reference direction should be
                                                          in the same direction as reference_axis
                                                          or in the opposite direction. If this parameter is (0,0,0),
                                                          this parameter is not used.  */,
            NXOpen::AxisOrientation reference_axis_orientation /** indicates whether the reference axis is horizontal or vertical */,
            NXOpen::Sense reference_axis_sense /** Ignored unless reference_direction
                                       is (0,0,0) and reference_axis is an edge or datum axis.
                                       This parameter indicates whether the reference axis should
                                       be in the same direction as reference_axis or in the opposite
                                       direction */,
            NXOpen::PlaneNormalOrientation normal_orientation /** whether the sketch's Z-axis should be outward or inward */
        );
        /**
            Creates a sketch. This function takes in an argument for the view to create the sketch in a
            drafting member view.
             @return  the new sketch  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Sketch * CreateSketch
        (
            const NXString & name /** Name of the sketch.  The name will be converted to upper case. If this is an empty string or NULL, a name will be provided by the system.   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
            NXOpen::ISurface * attachment_plane /** A face or datum plane that the sketch will be attached to.  Must be planar. */,
            NXOpen::IReferenceAxis * reference_axis /** Can be a datum axis, edge, datum plane, face, or NULL.
                                                                    If it is an edge, the edge must be a line segment.  If it is a face, the
                                                                    face must be a plane.  If NULL, the reference_direction is used instead */,
            const NXOpen::Vector3d & reference_direction /** If reference_axis is NULL,
                                                          this parameter sets the reference direction of the sketch.
                                                          In this case, this parameter must not be (0,0,0).
                                                          If reference_axis is not NULL
                                                          and this parameter is not (0,0,0), this parameter
                                                          determines whether the reference direction should be
                                                          in the same direction as reference_axis
                                                          or in the opposite direction. If this parameter is (0,0,0),
                                                          this parameter is not used.  */,
            NXOpen::AxisOrientation reference_axis_orientation /** indicates whether the reference axis is horizontal or vertical */,
            NXOpen::Sense reference_axis_sense /** Ignored unless reference_direction
                                       is (0,0,0) and reference_axis is an edge or datum axis.
                                       This parameter indicates whether the reference axis should
                                       be in the same direction as reference_axis or in the opposite
                                       direction */,
            NXOpen::PlaneNormalOrientation normal_orientation /** whether the sketch's Z-axis should be outward or inward */,
            NXOpen::NXObject * view /** View of the drafting view in which the sketch needsto be created */
        );
        /** Finds the @link  Sketch   Sketch @endlink  with the given name.

            An exception will be thrown if no object can be found with the given name.
             @return  Sketch with this name  <br> License requirements : None */
        public: NXOpen::Sketch * FindObject
        (
            const NXString & name /** The name of the @link Sketch Sketch@endlink    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
        );
        /** Returns the sketch that owns the specified geometry  @return  The sketch that owns the geometry  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Sketch * GetOwningSketch
        (
            NXOpen::SmartObject * geometry /** geometry */ 
        );
        /** Creates the builder for intersection curve  @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchIntersectionCurveBuilder * CreateIntersectionCurveBuilder
        (
            NXOpen::SketchIntersectionCurve * operation /** operation */ 
        );
        /** Creates the builder for intersection point  @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchIntersectionPointBuilder * CreateIntersectionPointBuilder
        (
            NXOpen::SketchIntersectionPoint * operation /** operation */ 
        );
        /** Creates a @link SketchProjectBuilder SketchProjectBuilder@endlink   @return  ProjectBuilder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchProjectBuilder * CreateProjectBuilder
        (
            NXOpen::Features::Feature * operation /** The feature for the @link SketchProjectBuilder SketchProjectBuilder@endlink  to be edited,
                                                                       if NULL then create a new one */
        );
        /** Creates a @link SketchCornerBuilder SketchCornerBuilder@endlink   @return  CornerBuilder object  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchCornerBuilder * CreateCornerBuilder
        (
        );
        /** Creates a @link SketchAutoConstrainBuilder SketchAutoConstrainBuilder@endlink   @return  Sketch Auto-Constrain Builder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchAutoConstrainBuilder * CreateAutoConstrainBuilder
        (
        );
        /** Creates a @link SketchOffsetBuilder SketchOffsetBuilder@endlink   @return   <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchOffsetBuilder * CreateSketchOffsetBuilder
        (
            NXOpen::SketchOffset * off_con /** Offset constraint */
        );
        /** Creates a @link ConvertToFromReferenceBuilder ConvertToFromReferenceBuilder@endlink   @return  Sketch ConvertToFromReferenceBuilder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::ConvertToFromReferenceBuilder * CreateConvertToFromReferenceBuilder
        (
        );
        /** Creates a @link InferredConstraintsBuilder InferredConstraintsBuilder@endlink   @return  InferredConstraintsBuilder object <br> License requirements : None */
        public: NXOpen::InferredConstraintsBuilder * CreateInferredConstraintsBuilder
        (
        );
        /** Creates a @link SketchMirrorBuilder SketchMirrorBuilder@endlink   @return  SketchMirrorBuilder object  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchMirrorBuilder * CreateSketchMirrorBuilder
        (
        );
        /** Creates a @link Features::TrimCurveBuilder Features::TrimCurveBuilder@endlink   @return  Trim Curve Builder object  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::Features::TrimCurveBuilder * CreateTrimCurveBuilder
        (
            NXOpen::Spline * spline /** spline */ 
        );
        /** Creates a @link SketchDimensionBuilder SketchDimensionBuilder@endlink   @return  DimensionBuilder object  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchDimensionBuilder * CreateDimensionBuilder
        (
            NXOpen::SketchDimensionalConstraint * constraint /** The sketch dimensional constraint to be edited. */
        );
        /** Creates a @link SketchQuickExtendBuilder SketchQuickExtendBuilder@endlink   @return  Sketch Quick-Extend Builder object  <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchQuickExtendBuilder * CreateQuickExtendBuilder
        (
        );
        /** Creates a @link SketchQuickTrimBuilder SketchQuickTrimBuilder@endlink   @return  Sketch QuickTrim Builder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchQuickTrimBuilder * CreateQuickTrimBuilder
        (
        );
        /** Creates a @link SketchInPlaceBuilder SketchInPlaceBuilder@endlink   @return  SketchInPlaceBuilder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchInPlaceBuilder * CreateSketchInPlaceBuilder
        (
            NXOpen::Sketch * operation /** The @link Sketch Sketch@endlink  to reattach or NULL to create                                                          a new one */
        );
        /** Creates a @link SketchAlongPathBuilder SketchAlongPathBuilder@endlink   @return  SketchAlongPathBuilder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchAlongPathBuilder * CreateSketchAlongPathBuilder
        (
            NXOpen::Sketch * operation /** The @link Sketch Sketch@endlink  to reattach or NULL to create                                                          a new one */
        );
        /** Creates a @link SketchInDraftingBuilder SketchInDraftingBuilder@endlink   @return  SketchInDraftingBuilder object <br> License requirements : solid_modeling ("SOLIDS MODELING") OR drafting ("DRAFTING") */
        public: NXOpen::SketchInDraftingBuilder * CreateSketchInDraftingBuilder
        (
        );
        public: virtual void initialize();
    };
}
#undef EXPORTLIBRARY
#endif
