#ifndef NXOpen_TOOLING_STANDARDPARTPOSITIONBUILDER_HXX_INCLUDED
#define NXOpen_TOOLING_STANDARDPARTPOSITIONBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Tooling_StandardPartPositionBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Tooling_ConceptStandardPartRecord.hxx>
#include <NXOpen/Tooling_StandardPartData.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_tooling_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Tooling
    {
        class StandardPartPositionBuilder;
    }
    namespace Assemblies
    {
        class Component;
    }
    class Builder;
    class Expression;
    class NXObject;
    class Point;
    namespace Tooling
    {
        class ConceptStandardPartRecord;
    }
    namespace Tooling
    {
        class StandardPartData;
    }
    namespace Tooling
    {
        class _StandardPartPositionBuilderBuilder;
        class StandardPartPositionBuilderImpl;
        /** Represents a StandardPartPositionBuilder to add or edit a standard part in the selected plane with specified position.  <br> To create a new instance of this class, use @link NXOpen::Tooling::StandardPartPositionCollection::CreateStandardPartPositionBuilder  NXOpen::Tooling::StandardPartPositionCollection::CreateStandardPartPositionBuilder @endlink  <br> 
        Default values.
        <list type="table"> 
         
        <listheader><term> 
        Property</term>  <description> 
        Value</description> </listheader>
        <item><term> 
         
        AssociativePosition </term> <description> 
         
        1 </description> </item> 

        <item><term> 
         
        DxIncrement </term> <description> 
         
        1.0 </description> </item> 

        <item><term> 
         
        DyIncrement </term> <description> 
         
        1.0 </description> </item> 

        <item><term> 
         
        OffsetPositionDx.Value </term> <description> 
         
        0.0 (millimeters part), 0.0 (inches part) </description> </item> 

        <item><term> 
         
        OffsetPositionDy.Value </term> <description> 
         
        0.0 (millimeters part), 0.0 (inches part) </description> </item> 

        </list> 

         <br>  Created in NX8.5.0.  <br>  
        */
        class NXOPENCPP_TOOLINGEXPORT  StandardPartPositionBuilder : public NXOpen::Builder
        {
            private: StandardPartPositionBuilderImpl * m_standardpartpositionbuilder_impl;
            private: friend class  _StandardPartPositionBuilderBuilder;
            protected: StandardPartPositionBuilder();
            public: ~StandardPartPositionBuilder();
            /**Returns  the reference point position. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: NXOpen::Point * ReferencePosition
            (
            );
            /**Sets  the reference point position. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetReferencePosition
            (
                NXOpen::Point * refPos /** refpos */ 
            );
            /** The offset point position. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetOffsetPosition
            (
                const NXOpen::Point3d & position /** position */ 
            );
            /** Sets the reference point to the selected face center. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetFaceCenter
            (
            );
            /**Returns  the dimension in X direction from reference point to offset point. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: NXOpen::Expression * OffsetPositionDx
            (
            );
            /**Returns  the dimension in Y direction from reference point to offset point. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: NXOpen::Expression * OffsetPositionDy
            (
            );
            /**Returns  the associative status between standardpart and the offset point. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: bool AssociativePosition
            (
            );
            /**Sets  the associative status between standardpart and the offset point. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetAssociativePosition
            (
                bool associativePosition /** associativeposition */ 
            );
            /**Returns  the increment in X direction when a standard part is dragged. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: double DxIncrement
            (
            );
            /**Sets  the increment in X direction when a standard part is dragged. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetDxIncrement
            (
                double dxIncrement /** dxincrement */ 
            );
            /**Returns  the increment in Y direction when a standard part is dragged. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: double DyIncrement
            (
            );
            /**Sets  the increment in Y direction when a standard part is dragged. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetDyIncrement
            (
                double dyIncrement /** dyincrement */ 
            );
            /** Sets the view to the selected face plane or X-Y plane of WCS. 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void PlaneView
            (
            );
            /** Reads the standard part data from the given concept point or symbol. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void ReadStandardPartRecordFromConceptObject
            (
                NXOpen::NXObject * conceptObject /** conceptobject */ 
            );
            /** Inserts a concept point or a symbol. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void InsertConceptObject
            (
                const NXOpen::Point3d & offsetPoint /** offsetpoint */ ,
                const NXOpen::Matrix3x3 & positionMatrix /** positionmatrix */ 
            );
            /** Edits the position of the concept object. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void EditPositionOfConceptObject
            (
                const NXOpen::Point3d & offsetPoint /** offsetpoint */ 
            );
            /** Reposition the added component or the added symbol. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void RepositionComponentOrSymbol
            (
                const NXOpen::Point3d & toPoint /** topoint */ ,
                const NXOpen::Matrix3x3 & toMatrix /** tomatrix */ 
            );
            /** Sets standard part client data and initialize position data. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void SetStandardPartClientData
            (
                NXOpen::Tooling::StandardPartData * pClietData /** Standard part client data */
            );
            /** Creates a linked face based on the user selected face. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void CreateLinkedPositionFace
            (
            );
            /** Add a new component or an instance part. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void AddStandardPart
            (
            );
            /** Repositions the added component and updates its dimensions . 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void UpdateAddedComponent
            (
                NXOpen::Assemblies::Component * addedOcc /** addedocc */ ,
                const NXOpen::Point3d & offsetPoint /** offsetpoint */ 
            );
            /** Modifies the clone setting according to the part installation type 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            public: void PerformCloneSetting
            (
                int installationType /** installationtype */ ,
                const NXString & clonePartName /** clonepartname */ 
            );
            /** Modifies the clone setting according to the part installation type 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR nx_electrode_wizard ("NX Electrode Wizard") OR prog_die_wizard ("UG/Progressive Die Wizard") */
            void PerformCloneSetting
            (
                int installationType /** installationtype */ ,
                const char * clonePartName /** clonepartname */ 
            );
            /** Gets standard part concept data  @return  A @link NXOpen::Tooling::ConceptStandardPartRecord NXOpen::Tooling::ConceptStandardPartRecord@endlink  instance 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Tooling::ConceptStandardPartRecord * GetConceptPartData
            (
            );
            /** Sets standard part concept data. 
             <br>  Created in NX2007.0.0.  <br>  
             <br> License requirements : ug_mold_design ("UG MOLD") OR prog_die_wizard ("UG/Progressive Die Wizard") OR ug_die_design ("Die Design") */
            public: void SetConceptPartData
            (
                NXOpen::Tooling::ConceptStandardPartRecord * conceptPartData /** A @link NXOpen::Tooling::ConceptStandardPartRecord NXOpen::Tooling::ConceptStandardPartRecord@endlink  instance */
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
