#ifndef NXOpen_WELD_GROOVEBUILDER_HXX_INCLUDED
#define NXOpen_WELD_GROOVEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Weld_GrooveBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/WeldAssistant.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/libnxopencpp_weld_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Weld
    {
        class GrooveBuilder;
    }
    class Expression;
    class Face;
    namespace Features
    {
        class FeatureBuilder;
    }
    class ScCollector;
    class Section;
    namespace Weld
    {
        class _GrooveBuilderBuilder;
        class GrooveBuilderImpl;
        /** Represents a Groove Weld feature  <br> To create a new instance of this class, use @link NXOpen::Weld::WeldManager::CreateWeldGrooveBuilder  NXOpen::Weld::WeldManager::CreateWeldGrooveBuilder @endlink  <br> 
         <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder NXOpen::Weld::WeldGrooveBuilder@endlink instead. <br>  

         <br>  Created in NX5.0.0.  <br>  
        */
        class NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilderinstead.") NXOPENCPP_WELDEXPORT  GrooveBuilder : public NXOpen::Features::FeatureBuilder
        {
            private: GrooveBuilderImpl * m_groovebuilder_impl;
            private: friend class  _GrooveBuilderBuilder;
            protected: GrooveBuilder();
            public: ~GrooveBuilder();
            /**Returns  the output type. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") NXOpen::Weld::OutputType OutputType
            (
            );
            /**Sets  the output type. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetOutputType
            (
                NXOpen::Weld::OutputType outputType /** output type */ 
            );
            /**Returns  the first set of faces 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::FaceSet1 NXOpen::Weld::WeldGrooveBuilder::FaceSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::FaceSet1instead.") NXOpen::ScCollector * FirstFaceset
            (
            );
            /**Sets  the first set of faces 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::FaceSet1 NXOpen::Weld::WeldGrooveBuilder::FaceSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::FaceSet1instead.") void SetFirstFaceset
            (
                NXOpen::ScCollector * faceCollector /** face collector */ 
            );
            /**Returns  the first set top edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet1 NXOpen::Weld::WeldGrooveBuilder::EdgeSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet1instead.") NXOpen::Section * FirstFacesetTopEdges
            (
            );
            /**Sets  the first set top edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet1 NXOpen::Weld::WeldGrooveBuilder::EdgeSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet1instead.") void SetFirstFacesetTopEdges
            (
                NXOpen::Section * section /** section */ 
            );
            /**Returns  the first set bottom edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet1 NXOpen::Weld::WeldGrooveBuilder::EdgeSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet1instead.") NXOpen::Section * FirstFacesetBottomEdges
            (
            );
            /**Sets  the first set bottom edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet1 NXOpen::Weld::WeldGrooveBuilder::EdgeSet1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet1instead.") void SetFirstFacesetBottomEdges
            (
                NXOpen::Section * section /** section */ 
            );
            /**Returns  the first set help point. If multiple solutions exist, the desired solution 
                    used will be the one closest to this point 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SeedPoint1 NXOpen::Weld::WeldGrooveBuilder::SeedPoint1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SeedPoint1instead.") NXOpen::Point3d FirstFacesetHelpPoint
            (
            );
            /**Sets  the first set help point. If multiple solutions exist, the desired solution 
                    used will be the one closest to this point 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint1 NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint1@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint1instead.") void SetFirstFacesetHelpPoint
            (
                const NXOpen::Point3d & helpPoint /** help point */ 
            );
            /**Returns  the side of the faceset to build the groove feature. The feature will
                    be built opposite the face closest to the help point 
                    
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") bool IsFirstFacesetNormalReversed
            (
            );
            /**Sets  the side of the faceset to build the groove feature. The feature will
                    be built opposite the face closest to the help point 
                    
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetFirstFacesetNormalReversed
            (
                bool reversed /** reversed */ 
            );
            /**Returns  the second set of faces 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::FaceSet2 NXOpen::Weld::WeldGrooveBuilder::FaceSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::FaceSet2instead.") NXOpen::ScCollector * SecondFaceset
            (
            );
            /**Sets  the second set of faces 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::FaceSet2 NXOpen::Weld::WeldGrooveBuilder::FaceSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::FaceSet2instead.") void SetSecondFaceset
            (
                NXOpen::ScCollector * faceCollector /** face collector */ 
            );
            /**Returns  the second set top edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet2 NXOpen::Weld::WeldGrooveBuilder::EdgeSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet2instead.") NXOpen::Section * SecondFacesetTopEdges
            (
            );
            /**Sets  the second set top edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet2 NXOpen::Weld::WeldGrooveBuilder::EdgeSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet2instead.") void SetSecondFacesetTopEdges
            (
                NXOpen::Section * edgeCollector /** edge collector */ 
            );
            /**Returns  the second set bottom edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet2 NXOpen::Weld::WeldGrooveBuilder::EdgeSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet2instead.") NXOpen::Section * SecondFacesetBottomEdges
            (
            );
            /**Sets  the second set bottom edges to extend 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeSet2 NXOpen::Weld::WeldGrooveBuilder::EdgeSet2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeSet2instead.") void SetSecondFacesetBottomEdges
            (
                NXOpen::Section * edgeCollector /** edge collector */ 
            );
            /**Returns  the second set help point. If multiple solutions exist, the desired solution 
                    used will be the one closest to this point 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SeedPoint2 NXOpen::Weld::WeldGrooveBuilder::SeedPoint2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SeedPoint2instead.") NXOpen::Point3d SecondFacesetHelpPoint
            (
            );
            /**Sets  the second set help point. If multiple solutions exist, the desired solution 
                    used will be the one closest to this point 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint2 NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint2@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetSeedPoint2instead.") void SetSecondFacesetHelpPoint
            (
                const NXOpen::Point3d & helpPoint /** help point */ 
            );
            /**Returns  the side of the faceset to build the groove feature. The feature will
                    be built opposite the face closest to the help point 
                    
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") bool IsSecondFacesetNormalReversed
            (
            );
            /**Sets  the side of the faceset to build the groove feature. The feature will
                    be built opposite the face closest to the help point 
                    
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetSecondFacesetNormalReversed
            (
                bool reversed /** reversed */ 
            );
            /** Sets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetFirstFacesetStartAdjacentFaces
            (
                const std::vector<NXOpen::Face *> & objects /** objects */ 
            );
            /** Gets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with.  @return  the adjacent face reference objects 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") std::vector<NXOpen::Face *> GetFirstFacesetStartAdjacentFaces
            (
            );
            /** Sets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetFirstFacesetEndAdjacentFaces
            (
                const std::vector<NXOpen::Face *> & objects /** objects */ 
            );
            /** Gets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with.  @return  the adjacent face reference objects 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") std::vector<NXOpen::Face *> GetFirstFacesetEndAdjacentFaces
            (
            );
            /** Sets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetSecondFacesetStartAdjacentFaces
            (
                const std::vector<NXOpen::Face *> & objects /** objects */ 
            );
            /** Gets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with.  @return  the adjacent face reference objects 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") std::vector<NXOpen::Face *> GetSecondFacesetStartAdjacentFaces
            (
            );
            /** Sets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with. 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetSecondFacesetEndAdjacentFaces
            (
                const std::vector<NXOpen::Face *> & objects /** objects */ 
            );
            /** Gets the adjacent faces of the target solid. These faces are used to
                    trim the groove weld solid with.  @return  the adjacent face reference objects 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") std::vector<NXOpen::Face *> GetSecondFacesetEndAdjacentFaces
            (
            );
            /**Returns  the contour contour shape. This is the shape on the top of the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::ContourType NXOpen::Weld::WeldGrooveBuilder::ContourType@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::ContourTypeinstead.") NXOpen::Weld::WeldContourShape ContourShape
            (
            );
            /**Sets  the contour contour shape. This is the shape on the top of the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::ContourType NXOpen::Weld::WeldGrooveBuilder::ContourType@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::ContourTypeinstead.") void SetContourShape
            (
                NXOpen::Weld::WeldContourShape contourShape /** contour shape */ 
            );
            /**Returns  the shape of the groove weld to create 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Types NXOpen::Weld::WeldGrooveBuilder::Types@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Typesinstead.") NXOpen::Weld::WeldGrooveShape GrooveShape
            (
            );
            /**Sets  the shape of the groove weld to create 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Types NXOpen::Weld::WeldGrooveBuilder::Types@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Typesinstead.") void SetGrooveShape
            (
                NXOpen::Weld::WeldGrooveShape grooveShape /** groove shape */ 
            );
            /** Gets the contour height needed to describe groove weld shape  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::ContourHeight NXOpen::Weld::WeldGrooveBuilder::ContourHeight@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::ContourHeightinstead.") NXOpen::Expression * GetContourHeight
            (
            );
            /** Sets the contour height needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::ContourHeight NXOpen::Weld::WeldGrooveBuilder::ContourHeight@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::ContourHeightinstead.") void SetContourHeight
            (
                const NXString & contourHeight /** contour height */ 
            );
            /** Sets the contour height needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::ContourHeight NXOpen::Weld::WeldGrooveBuilder::ContourHeight@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetContourHeight
            (
                const char * contourHeight /** contour height */ 
            );
            /** Gets the root opening height needed to describe groove weld  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::RootOpening NXOpen::Weld::WeldGrooveBuilder::RootOpening@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::RootOpeninginstead.") NXOpen::Expression * GetRootOpening
            (
            );
            /** Sets the root opening height needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetRootOpening NXOpen::Weld::WeldGrooveBuilder::SetRootOpening@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetRootOpeninginstead.") void SetRootOpening
            (
                const NXString & rootOpening /** root opening */ 
            );
            /** Sets the root opening height needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetRootOpening NXOpen::Weld::WeldGrooveBuilder::SetRootOpening@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetRootOpening
            (
                const char * rootOpening /** root opening */ 
            );
            /** Gets the root penetration needed to describe groove weld  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::RootPenetration NXOpen::Weld::WeldGrooveBuilder::RootPenetration@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::RootPenetrationinstead.") NXOpen::Expression * GetRootPenetration
            (
            );
            /** Sets the root penetration needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetRootPenetration NXOpen::Weld::WeldGrooveBuilder::SetRootPenetration@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetRootPenetrationinstead.") void SetRootPenetration
            (
                const NXString & rootPenetration /** root penetration */ 
            );
            /** Sets the root penetration needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetRootPenetration NXOpen::Weld::WeldGrooveBuilder::SetRootPenetration@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetRootPenetration
            (
                const char * rootPenetration /** root penetration */ 
            );
            /** Gets the groove angle needed to describe groove weld  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveAngle NXOpen::Weld::WeldGrooveBuilder::GrooveAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::GrooveAngleinstead.") NXOpen::Expression * GetGrooveAngle
            (
            );
            /** Sets the groove angle needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveAngle NXOpen::Weld::WeldGrooveBuilder::GrooveAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::GrooveAngleinstead.") void SetGrooveAngle
            (
                const NXString & grooveAngle /** groove angle */ 
            );
            /** Sets the groove angle needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveAngle NXOpen::Weld::WeldGrooveBuilder::GrooveAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetGrooveAngle
            (
                const char * grooveAngle /** groove angle */ 
            );
            /** Gets the groove radius needed to describe groove weld  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveRadius NXOpen::Weld::WeldGrooveBuilder::GrooveRadius@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::GrooveRadiusinstead.") NXOpen::Expression * GetGrooveRadius
            (
            );
            /** Sets the groove radius needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveRadius NXOpen::Weld::WeldGrooveBuilder::GrooveRadius@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::GrooveRadiusinstead.") void SetGrooveRadius
            (
                const NXString & grooveAngle /** groove angle */ 
            );
            /** Sets the groove radius needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::GrooveRadius NXOpen::Weld::WeldGrooveBuilder::GrooveRadius@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetGrooveRadius
            (
                const char * grooveAngle /** groove angle */ 
            );
            /** Gets the penetration depth needed to describe groove weld  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::PenetrationDepthinstead.") NXOpen::Expression * GetPenetrationDepth
            (
            );
            /** Sets the penetration depth needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::PenetrationDepthinstead.") void SetPenetrationDepth
            (
                const NXString & penetrationDepth /** penetration depth */ 
            );
            /** Sets the penetration depth needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth NXOpen::Weld::WeldGrooveBuilder::PenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetPenetrationDepth
            (
                const char * penetrationDepth /** penetration depth */ 
            );
            /** Gets the second penetration depth needed to describe groove weld. This is only needed if face heights are different.  @return  expression 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepthinstead.") NXOpen::Expression * GetSecondPenetrationDepth
            (
            );
            /** Sets the penetration depth needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepthinstead.") void SetSecondPenetrationDepth
            (
                const NXString & secondPenetrationDepth /** second penetration depth */ 
            );
            /** Sets the penetration depth needed to describe groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth NXOpen::Weld::WeldGrooveBuilder::SecondPenetrationDepth@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetSecondPenetrationDepth
            (
                const char * secondPenetrationDepth /** second penetration depth */ 
            );
            /**Returns  the groove creation type 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EdgeType NXOpen::Weld::WeldGrooveBuilder::EdgeType@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EdgeTypeinstead.") NXOpen::Weld::WeldGrooveType GrooveType
            (
            );
            /**Sets  the groove creation type 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetEdgeType NXOpen::Weld::WeldGrooveBuilder::SetEdgeType@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetEdgeTypeinstead.") void SetGrooveType
            (
                NXOpen::Weld::WeldGrooveType grooveType /** groove type */ 
            );
            /**Returns  the process type 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") NXOpen::Weld::WeldRootUpdate RootUpdate
            (
            );
            /**Sets  the process type 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetRootUpdate
            (
                NXOpen::Weld::WeldRootUpdate rootUpdate /** root update */ 
            );
            /**Returns  the field weld status. If true then this is a field weld,
                    if false it is not. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Characteristics NXOpen::Weld::WeldGrooveBuilder::Characteristics@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Characteristicsinstead.") bool IsFieldWeld
            (
            );
            /**Sets  the field weld status. If true then this is a field weld,
                    if false it is not. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Characteristics NXOpen::Weld::WeldGrooveBuilder::Characteristics@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Characteristicsinstead.") void SetFieldWeld
            (
                bool fieldWeld /** field weld */ 
            );
            /**Returns  the the extension method for the top edges 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") NXOpen::Weld::WeldGrooveExtension TopExtension
            (
            );
            /**Sets  the the extension method for the top edges 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetTopExtension
            (
                NXOpen::Weld::WeldGrooveExtension extensionType /** extension type */ 
            );
            /**Returns  the extension method for the bottom edges 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") NXOpen::Weld::WeldGrooveExtension BottomExtension
            (
            );
            /**Sets  the extension method for the bottom edges 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetBottomExtension
            (
                NXOpen::Weld::WeldGrooveExtension extensionType /** extension type */ 
            );
            /**Returns  the number of connected parts. Either one for two. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SingleFaceSet NXOpen::Weld::WeldGrooveBuilder::SingleFaceSet@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SingleFaceSetinstead.") int NumberRequiredFaceSets
            (
            );
            /**Sets  the number of connected parts. Either one for two. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetSingleFaceSet NXOpen::Weld::WeldGrooveBuilder::SetSingleFaceSet@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetSingleFaceSetinstead.") void SetNumberRequiredFaceSets
            (
                int numberRequiredFaceSets /** number required face sets */ 
            );
            /**Returns  the distance from the start of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartDistance NXOpen::Weld::WeldGrooveBuilder::StartDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::StartDistanceinstead.") NXOpen::Expression * DistanceFromStart
            (
            );
            /** Set the distance from the start of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartDistance NXOpen::Weld::WeldGrooveBuilder::StartDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::StartDistanceinstead.") void SetDistanceFromStart
            (
                const NXString & startDistance /** start distance */ 
            );
            /** Set the distance from the start of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartDistance NXOpen::Weld::WeldGrooveBuilder::StartDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetDistanceFromStart
            (
                const char * startDistance /** start distance */ 
            );
            /**Returns  the distance from the end of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndDistance NXOpen::Weld::WeldGrooveBuilder::EndDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EndDistanceinstead.") NXOpen::Expression * DistanceFromEnd
            (
            );
            /** Sets the distance from the end of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndDistance NXOpen::Weld::WeldGrooveBuilder::EndDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EndDistanceinstead.") void SetDistanceFromEnd
            (
                const NXString & endDistance /** end distance */ 
            );
            /** Sets the distance from the end of the faces to build the groove weld 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndDistance NXOpen::Weld::WeldGrooveBuilder::EndDistance@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetDistanceFromEnd
            (
                const char * endDistance /** end distance */ 
            );
            /**Returns  the taper angle at the start. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartAngle NXOpen::Weld::WeldGrooveBuilder::StartAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::StartAngleinstead.") NXOpen::Expression * TaperAtStart
            (
            );
            /** Sets the taper angle at the start. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartAngle NXOpen::Weld::WeldGrooveBuilder::StartAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::StartAngleinstead.") void SetTaperAtStart
            (
                const NXString & startTaper /** start taper */ 
            );
            /** Sets the taper angle at the start. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::StartAngle NXOpen::Weld::WeldGrooveBuilder::StartAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetTaperAtStart
            (
                const char * startTaper /** start taper */ 
            );
            /**Returns  the taper angle at the end. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndAngle NXOpen::Weld::WeldGrooveBuilder::EndAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EndAngleinstead.") NXOpen::Expression * TaperAtEnd
            (
            );
            /** Sets the taper angle at the end. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndAngle NXOpen::Weld::WeldGrooveBuilder::EndAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::EndAngleinstead.") void SetTaperAtEnd
            (
                const NXString & endTaper /** end taper */ 
            );
            /** Sets the taper angle at the end. A positive number will taper towards
                    the inside of the weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::EndAngle NXOpen::Weld::WeldGrooveBuilder::EndAngle@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetTaperAtEnd
            (
                const char * endTaper /** end taper */ 
            );
            /**Returns  the method 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::CreateSkipWelds NXOpen::Weld::WeldGrooveBuilder::CreateSkipWelds@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::CreateSkipWeldsinstead.") NXOpen::Weld::WeldArcMethod Method
            (
            );
            /**Sets  the method 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetCreateSkipWelds NXOpen::Weld::WeldGrooveBuilder::SetCreateSkipWelds@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetCreateSkipWeldsinstead.") void SetMethod
            (
                NXOpen::Weld::WeldArcMethod method /** method */ 
            );
            /**Returns  the is spacing option. This is used when creating skip welds to 
                    compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Method NXOpen::Weld::WeldGrooveBuilder::Method@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Methodinstead.") bool IsSpacing
            (
            );
            /**Sets  the is spacing option. This is used when creating skip welds to 
                    compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetMethod NXOpen::Weld::WeldGrooveBuilder::SetMethod@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetMethodinstead.") void SetSpacing
            (
                bool isSpacing /** is spacing */ 
            );
            /**Returns  the is number of segments option. This is used when creating skip welds to
                   compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Method NXOpen::Weld::WeldGrooveBuilder::Method@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Methodinstead.") bool IsNumberOfSegments
            (
            );
            /**Sets  the is number of segments option. This is used when creating skip welds to
                   compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetMethod NXOpen::Weld::WeldGrooveBuilder::SetMethod@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetMethodinstead.") void SetNumberOfSegments
            (
                bool isNumberOfSegments /** is number of segments */ 
            );
            /**Returns  the is segment length option. This is used when creating skip welds to
                   compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Method NXOpen::Weld::WeldGrooveBuilder::Method@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Methodinstead.") bool IsSegmentLength
            (
            );
            /**Sets  the is segment length option. This is used when creating skip welds to
                   compute the spacing between them. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetMethod NXOpen::Weld::WeldGrooveBuilder::SetMethod@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetMethodinstead.") void SetSegmentLength
            (
                bool isSegmentLength /** is segment length */ 
            );
            /**Returns  the desired spacing between skip welds. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Spacing NXOpen::Weld::WeldGrooveBuilder::Spacing@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Spacinginstead.") NXOpen::Expression * SpacingDistance
            (
            );
            /** Sets the desired spacing between skip welds. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Spacing NXOpen::Weld::WeldGrooveBuilder::Spacing@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::Spacinginstead.") void SetSpacingDistance
            (
                const NXString & spacingDistance /** spacing distance */ 
            );
            /** Sets the desired spacing between skip welds. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::Spacing NXOpen::Weld::WeldGrooveBuilder::Spacing@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetSpacingDistance
            (
                const char * spacingDistance /** spacing distance */ 
            );
            /**Returns  the number of weld welds for a skip weld.  
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::NumberOfWeldsinstead.") NXOpen::Expression * NumberOfSegments
            (
            );
            /** Sets the desired number of segments for the groove weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::NumberOfWeldsinstead.") void SetNumberOfSegments
            (
                const NXString & numSegments /** num segments */ 
            );
            /** Sets the desired number of segments for the groove weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds NXOpen::Weld::WeldGrooveBuilder::NumberOfWelds@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetNumberOfSegments
            (
                const char * numSegments /** num segments */ 
            );
            /**Returns  the segment length for a skip weld.  
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SegmentLength NXOpen::Weld::WeldGrooveBuilder::SegmentLength@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SegmentLengthinstead.") NXOpen::Expression * SegmentLength
            (
            );
            /** Sets the desired segment lengh for the skip weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SegmentLength NXOpen::Weld::WeldGrooveBuilder::SegmentLength@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SegmentLengthinstead.") void SetSegmentLength
            (
                const NXString & segmentLength /** segment length */ 
            );
            /** Sets the desired segment lengh for the skip weld. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SegmentLength NXOpen::Weld::WeldGrooveBuilder::SegmentLength@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            void SetSegmentLength
            (
                const char * segmentLength /** segment length */ 
            );
            /**Returns  the sequence number for the groove feature. Each groove feature contains a solid.
                    If multiple groove wels are to be created, you must specify the sequence of the groove weld you want.
                    For example if you are expecting 3 welds to be created. You must create 3 groove weld features.
                    The features will have sequence numbers 0,1 and 2.  
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") int SequenceNumber
            (
            );
            /**Sets  the sequence number for the groove feature. Each groove feature contains a solid.
                    If multiple groove wels are to be created, you must specify the sequence of the groove weld you want.
                    For example if you are expecting 3 welds to be created. You must create 3 groove weld features.
                    The features will have sequence numbers 0,1 and 2.  
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetSequenceNumber
            (
                int sequenceNumber /** sequence number */ 
            );
            /**Returns  the output geometry type 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") NXOpen::Weld::WeldFeatureOutput OutputGeometryType
            (
            );
            /**Sets  the output geometry type 
             <br>  @deprecated Deprecated in NX9.0.0.  This functionality is no longer supported. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  This functionality is no longer supported.") void SetOutputGeometryType
            (
                NXOpen::Weld::WeldFeatureOutput outputGeometryType /** output geometry type */ 
            );
            /**Returns  the apply edge preportion indicator. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::PrepareEdges NXOpen::Weld::WeldGrooveBuilder::PrepareEdges@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::PrepareEdgesinstead.") NXOpen::Weld::WeldPrepareEdges PrepareEdges
            (
            );
            /**Sets  the apply edge preportion indicator. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetPrepareEdges NXOpen::Weld::WeldGrooveBuilder::SetPrepareEdges@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetPrepareEdgesinstead.") void SetPrepareEdges
            (
                NXOpen::Weld::WeldPrepareEdges prepareEdges /** prepare edges */ 
            );
            /**Returns  the taper method to use if tapering is specified. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::TaperMethod NXOpen::Weld::WeldGrooveBuilder::TaperMethod@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::TaperMethodinstead.") NXOpen::Weld::WeldTaperMethod TaperMethod
            (
            );
            /**Sets  the taper method to use if tapering is specified. 
             <br>  @deprecated Deprecated in NX9.0.0.  Use @link NXOpen::Weld::WeldGrooveBuilder::SetTaperMethod NXOpen::Weld::WeldGrooveBuilder::SetTaperMethod@endlink instead. <br>  

             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : ugweld ("UG WELD") */
            public: NX_DEPRECATED("Deprecated in NX9.0.0.  Use NXOpen::Weld::WeldGrooveBuilder::SetTaperMethodinstead.") void SetTaperMethod
            (
                NXOpen::Weld::WeldTaperMethod taperMethod /** taper method */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
